.\" $Id: athinfo.access.5,v 1.2 1999-04-13 21:15:33 ghudson Exp $
.\"
.\" Copyright 1998, 1999 by the Massachusetts Institute of Technology.
.\"
.\" Permission to use, copy, modify, and distribute this
.\" software and its documentation for any purpose and without
.\" fee is hereby granted, provided that the above copyright
.\" notice appear in all copies and that both that copyright
.\" notice and this permission notice appear in supporting
.\" documentation, and that the name of M.I.T. not be used in
.\" advertising or publicity pertaining to distribution of the
.\" software without specific, written prior permission.
.\" M.I.T. makes no representations about the suitability of
.\" this software for any purpose.  It is provided "as is"
.\" without express or implied warranty.
.TH ATHINFO.ACCESS 5 "13 April 1999"
.SH NAME
athinfo.access \- Control access to athinfo queries
.SH SYNOPSIS
.B /etc/athena/athinfo.access
.SH DESCRIPTION
The file
.B /etc/athena/athinfo.access
controls whether the athinfo daemon (see
.BR athinfod (8))
will answer requests for a given query.  Blank lines and lines
beginning with '#' are ignored.  Each line begins with the word
"enabled" or "disabled" and continues with either a query name or "*"
to match all queries.  A specific match ("enable foo" or "disable foo"
when the query is "foo") takes priority over a glob match ("enable *"
or "disable *").  If no lines match the query, then it is disabled (so
"disable *" effectively does nothing).
.SH EXAMPLE
The following example enables all queries except for "routes".
.PP
.RS
.nf
enable *
disable routes
.fi
.RE
.SH "SEE ALSO"
.BR athinfod (8),
.BR athinfo.defs (5)
.SH AUTHOR
Greg Hudson, MIT Information Systems
.br
Copyright 1998 by the Massachusetts Institute of Technology.
