.TH MITVPN-CONNECT 8 "11 March 2010" "debathena-mit-vpn-config" 
.SH NAME
mitvpn-connect \- Connect to the MIT VPN
.SH SYNOPSIS
.nf
.B mitvpn-connect 
.sp
.SH DESCRIPTION
.BR mitvpn-connect
runs openconnect on the user's behalf, with a connection script that
sets some sane default routes.

.SH SEE ALSO

http://www.infradead.org/openconnect.html

.SH AUTHOR
SIPB Debathena Project (http://debathena.mit.edu)

