.TH "mkfontdesc" "1" "September 2000" "teTeX" "teTeX" 
.PP 
.SH "NAME" 
mkfontdesc \- utility to create PK font description files
.PP 
.SH "SYNOPSIS" 
.PP 
\fBmkfontdesc\fP
.PP 
.SH "DESCRIPTION" 
.PP 
\fBmkfontdesc\fP creates font description files for PK (bitmap) fonts\&.
.PP 
.SH "FILES" 
.PP 
.IP "\fI\fI$TEXMFMAIN\fP/fonts/fontdesc\fP" 
output file
.IP "\fI\fI$TEXMFMAIN\fP/fonts/fontdesc\&.bak\fP" 
backup of output file
.PP 
.SH "SEE ALSO" 
.PP 
\fBkpsetool\fP(1)\&.
.PP 
Web page: <http://tug\&.cs\&.umb\&.edu/tetex/>
.PP 
.SH "DIAGNOSTICS" 
.PP 
"Ooops! font-directory $pk does not exist\&.
.br 
Need to change value for $TEXMFMAIN?"
.PP 
.SH "BUGS" 
.PP 
Report bugs to <tetex@dbs\&.uni-hannover\&.de> (mailing list)\&.
.PP 
.SH "AUTHOR" 
.PP 
\fBmkfontdesc\fP was written by Roland Meier, and modified by Thomas Esser 
<te@dbs\&.uni-hannover\&.de>\&.
.PP 
This manual page was written by C\&.M\&. Connelly
<c@eskimo\&.com>, for
the Debian GNU/Linux system\&.  It may be used by other distributions
without contacting the author\&.  Any mistakes or omissions in the
manual page are my fault; inquiries about or corrections to this
manual page should be directed to me (and not to the primary author)\&.
