.TH "dnonblock.h" 3 "7 Apr 2004" "Version 0.6" "libdaemon" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dnonblock.h \- Contains a single function used to change a file descriptor to non-blocking mode using fcntl().  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBdaemon_nonblock\fP (int fd, int b)"
.br
.RI "\fIChange the passed file descriptor to non-blocking or blocking mode, depending on b. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Contains a single function used to change a file descriptor to non-blocking mode using fcntl(). 


.PP
Definition in file \fBdnonblock.h\fP.
.SH "Function Documentation"
.PP 
.SS "int daemon_nonblock (int fd, int b)"
.PP
Change the passed file descriptor to non-blocking or blocking mode, depending on b. \fBParameters:\fP
.RS 4
\fIfd\fP The file descriptor to manipulation 
.br
\fIb\fP TRUE if non-blocking mode should be enabled, FALSE if it should be disabled 
.RE
.PP
\fBReturns:\fP
.RS 4
Zero on success, nonzero on failure. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for libdaemon from the source code.
