# $Id: Makefile.athena,v 1.3 1997-01-30 22:27:25 ghudson Exp $

SHELL=/bin/sh

prepare:
	imake "-I$$XCONFIGDIR" -DUseInstalled "-DCONFIGDIR=$$XCONFIGDIR"

clean:
	${MAKE} clean

all:
	${MAKE} config.h all

check:

install:
	${MAKE} install install.man "DESTDIR=$$SRVD"
