#!/sbin/sh
# Undo any undesired changes resulting from the installation of OS pkgs.
# $Id: oschanges,v 1.20 2004-05-05 03:08:06 zacheiss Exp $

# The SUNWcsr package undoes our inittab mod, so restore it.
cp -p /srvd/etc/inittab $UPDATE_ROOT/etc && [ ${UPDATE_ROOT:-/} = / ] && \
  /etc/telinit q

# The SUNWcsr package installs the stock /etc/default/init when not in
# UPDATE mode.
cp -p /srvd/etc/default/init $UPDATE_ROOT/etc/default

# removed
rm -f $UPDATE_ROOT/etc/rc2.d/S25tsaldog
rm -f $UPDATE_ROOT/etc/rc2.d/S76nscd
rm -f $UPDATE_ROOT/etc/rc2.d/S85power
rm -f $UPDATE_ROOT/etc/rc2.d/S88sendmail
rm -f $UPDATE_ROOT/etc/rc2.d/S89bdconfig
rm -f $UPDATE_ROOT/etc/rc2.d/S95IIim
rm -f $UPDATE_ROOT/etc/rc2.d/S99audit
rm -f $UPDATE_ROOT/etc/rc2.d/S80lp
rm -f $UPDATE_ROOT/etc/rc2.d/S90wbem
rm -f $UPDATE_ROOT/etc/rc2.d/S94skiserv
rm -f $UPDATE_ROOT/etc/rc3.d/S76snmpdx
rm -f $UPDATE_ROOT/etc/rc3.d/S77dmi

# Make sure /tmp is a symlink.  /var/rtmp is created by the install.
if [ ! -h $UPDATE_ROOT/tmp ]; then
  rm -rf $UPDATE_ROOT/tmp
  ln -s var/rtmp $UPDATE_ROOT/tmp
fi
