#!/sbin/sh
# Copy some files and remove some files after the os pkgs were installed

# copied from AFS
rm -f $UPDATE_ROOT/usr/ucblib/libucb.so.1
rm -f $UPDATE_ROOT/usr/ucblib/libucb.so
cp -p /os/usr/ucblib/libucb.so.1 $UPDATE_ROOT/usr/ucblib
ln -s libucb.so.1 $UPDATE_ROOT/usr/ucblib/libucb.so



# removed
rm -f $UPDATE_ROOT/etc/rc2.d/S85power
rm -f $UPDATE_ROOT/etc/rc2.d/S88sendmail
rm -f $UPDATE_ROOT/etc/rc2.d/S89bdconfig
rm -f $UPDATE_ROOT/etc/rc2.d/S99audit
rm -f $UPDATE_ROOT/etc/rc2.d/S80lp
rm -f $UPDATE_ROOT/etc/rc3.d/S76snmpdx
rm -f $UPDATE_ROOT/etc/rc3.d/S77dmi
rm -f $UPDATE_ROOT/etc/rc3.d/S76nscd


rm -f $UPDATE_ROOT/usr/openwin/lib/X11/fonts/75dpi/*
rm -f $UPDATE_ROOT/usr/openwin/lib/X11/fonts/misc/*
cp -p -r /os/usr/openwin/lib/X11/fonts/75dpi/* $UPDATE_ROOT/usr/openwin/lib/X11/fonts/75dpi/
cp -p -r /os/usr/openwin/lib/X11/fonts/misc/* $UPDATE_ROOT/usr/openwin/lib/X11/fonts/misc/
rm -f $UPDATE_ROOT/usr/openwin/server/lib/libtypesclr.so*
rm -f $UPDATE_ROOT/usr/openwin/server/lib/libfont.so*
cp -p /os/usr/openwin/server/lib/libfont.so.1 $UPDATE_ROOT/usr/openwin/server/lib/
cp -p /os/usr/openwin/server/lib/libtypesclr.so.0 $UPDATE_ROOT/usr/openwin/server/lib/
ln -s ../libfont.so.1 $UPDATE_ROOT/usr/openwin/server/lib/libfont.so
ln -s ../libtypesclr.so.0 $UPDATE_ROOT/usr/openwin/server/lib/libtypesclr.so

# Generate windex file so apropos works
catman -w -M /usr/openwin/share/man:/usr/dt/share/man:/usr/share/man
