# $Id: Makefile.athena,v 1.28 2004-03-11 15:21:26 ghudson Exp $

SHELL=/bin/sh

dist:
	cp "$$CONFIG_SITE" config.site.athena

prepare:
	rm -f src/config.cache
	cd src && CONFIG_SITE=`pwd`/../config.site.athena  \
		SS_LIB="-lss -lcurses" ./configure --without-hesiod \
		--with-system-et --with-system-ss --enable-shared \
		--without-tcl

clean:
	cd src && ${MAKE} clean

all:
	cd src && ${MAKE} all

check:

install:
	cd src && ${MAKE} install DESTDIR="$$SRVD"
