# $Id: Makefile.athena,v 1.14 1998-07-15 18:33:45 ghudson Exp $

SHELL=/bin/sh
ATHETCDIR=/usr/athena/etc
ATHINCDIR=/usr/athena/include

prepare:
	rm -f src/config.cache
	cd src && ./configure --with-krb4=yes

clean:
	cd src && ${MAKE} clean

all:
	cd src && ${MAKE} depend all

check:

install:
	cd src && ${MAKE} install DESTDIR="$$SRVD"
