# $Id: Makefile.athena,v 1.3 1997-01-30 22:30:35 ghudson Exp $

SHELL=/bin/sh

prepare:
	imake "-I$$XCONFIGDIR" -DUseInstalled "-DCONFIGDIR=$$XCONFIGDIR"
	${MAKE} Makefiles

clean:
	${MAKE} clean

all:
	${MAKE} includes depend all

check:

install:
	${MAKE} install install.man
