.ll 6i
.TH TRACK 1 "4 November 1986"
.UC 4
.SH NAME
.B track
-- maintain files between machines
.SH SYNOPSIS
.B track
[
.B \- FSTcdfimnpqsuvwx
]
subscriptionlist
.SH DESCRIPTION
.I subscriptionlist
contains a list of files to be maintained across machines. 
.B track
supports a
.I librarian/subscriber
model of file update.
If
.B track
is invoked with the
.B \-w
option (i.e. as the
.I librarian
machine), then the
.I subscriptionlist
is used to create a 
.I statfile
containing status information about the files that are available to
other machines.
If
.B track
is invoked without
.B \-w
(i.e. as the
.I subscriber
machine), then the
.I subscriptionlist
is used to decide what files are to be considered for possible updating.
The librarian machine is specified as an NFS mount-point with the -F option.
The default librarian is /srvd.
.PP
The most commonly-used options are:
.TP
.B \-F
Specify the source ( librarian) root-directory or mount-point.
The default value is /srvd.
.TP
.B \-T
specify the destination root directory, or mount-point. The default is /.
.TP
.B \-c
Compare checksums of regular files, when updating.
This slows the update,
but the checksums serve to detect file-system corruption.
.TP
.B \-d<dirname>
change the local working directory (i.e. the directory on the local machine) to
.I dirname.
A working directory is the place where
.B track
will look for
.I statfiles
and
.I subscriptionlists.
.B Track
must have permission to write in its local working directory.
The default is /mnt/etc/athena/lib, where /mnt is the librarian mount-point.
.TP
.B \-f
Force the update.  Don't be gentle about what is destroyed.  Normally
.B track
is very cautious about files being destroyed by an update.
.TP
.B \-n
Do nothing, just produce a list of files that need updating (disabled by \-w),
and the anticipated consequences of doing the update.
.TP
.B \-s <statfile>
.B \-s -
use the named file as the statfile, or use stdout if "-s -" is used.
.TP
.B \-v
Produces a very verbose description of what is happening during the update:
which files get updated, and why. This output goes to stderr.
.TP
.B \-w
write out a
.I statfile.
This is flag is always used by the
.I librarian
machine and never used by the
.I subscriber
machine(s).
.PP
The less commonly-used options:
.TP
.B \-i
Include devices and special files in update. 
.TP
.B \-m[recipient]
( Currently broken) Mail stdout and stderr to the recipient.
The default recipient is root.
.TP
.B \-p
Parse only and produce a verbose description of the fields in the
.I subscriptionlist. The output goes to stderr.
This can be useful when
.B track
complains about syntax errors
in the subscription-list.
.TP
.B \-q
Be quiet, i.e. don't complain about non-fatal errors.
The most common non-fatal error occurs when the
.I librarian
and/or network are unreachable.
.TP
.B \-u
Unconditionally copy files (i.e. older files can overwrite newer files)
.TP
.B \-x
display debugging information ( minimal).
.TP
.B \-S <max_path_depth>
Specify deeper path stacks; this is an internal implementation parameter.
.B Track
is supposed to tell you when to use -S, and how to use it.
Since the default depth accomodates pathnames with ~50 components,
this option is seldom used.
.SH EXAMPLES
.in 8
.ti -8
track \-p daily
.ti -4
Parse the
.I subscriptionlist
named "daily" and print a verbose
listing of the contents. This command is very helpful when trying to debug
freshly modified
.I subscriptionlists. 
.ti -8
track \-w hourly 
.ti -4
Act as the
.I librarian
and output a
.I statfile
for the
.I subscriptionlist
named "hourly".
.sp 1
.ti -8
track \-w \-q hourly 
.ti -4
Same as above, but non-fatal errors will be ignored.
.sp 1
.ti -8
attach paris:root
track daily -F/paris/root
.ti -4
Act as a
.I subscriber
machine and get the updates from root directory on the machine named "paris".
.sp 1
.ti -8
track \-n daily
.ti -4
Act as a
.I subscriber,
but do not perform any updates.
Instead, print a listing of the updates that should be made.  This is analogous
to "make \-n".  Invoking 
.B track
with the
.B \-n
flag is a safe way to preview what will happen before
.B track
is turned loose on a new machine.
.sp 1
.ti -8
track \-u daily
.ti -4
Act as a
.I subscriber,
except update files from the
.I librarian
even if the versions on this machine are newer than the versions
on the
.I librarian.
.sp 1
.ti -8
track \-u \-m \-q daily
.ti -4
Same as the above, except ignore non-fatal errors.
These are the arguments most often given when
.B track
is executed by
.B cron(8)
on a
.I subscriber
machine.
.in -8
.SH FILES
 .../track/*
.br
 .../track/slists
.I subscriptionlist_name 
.br
 .../track/stats
.I subscriptionlist_name . librarian_machine_name
.SH SEE ALSO
subscriptionlist(5), statfile(5), permissions(5), cron(8)
.PP
When Network File Systems Aren't Enough: Automatic File Distribution Revisited
.br
.ti 5
by Daniel Nachbar
