.\" $Id: larvnet.clusters.5,v 1.2 1999-04-13 21:23:25 ghudson Exp $
.\"
.\" Copyright 1998, 1999 by the Massachusetts Institute of Technology.
.\"
.\" Permission to use, copy, modify, and distribute this
.\" software and its documentation for any purpose and without
.\" fee is hereby granted, provided that the above copyright
.\" notice appear in all copies and that both that copyright
.\" notice and this permission notice appear in supporting
.\" documentation, and that the name of M.I.T. not be used in
.\" advertising or publicity pertaining to distribution of the
.\" software without specific, written prior permission.
.\" M.I.T. makes no representations about the suitability of
.\" this software for any purpose.  It is provided "as is"
.\" without express or implied warranty.
.\"
.TH LARVNET.CLUSTERS 5 "13 April 1999"
.SH NAME
larvnet.clusters \- larvnetd cluster status report file
.SH SYNOPSIS
.B /var/athena/larvnet.clusters
.SH DESCRIPTION
The file
.B /var/athena/larvnet.clusters
contains status information about cluster machines.  It is written by
.BR larvnetd (8)
and typically presented to the user by
.BR cviewd (8).
.PP
The report is divided into two sections, separated by a divider line
beginning with a dash.  The first section is a list of architecture
names, one per line.  The second section is a list of cluster status
lines, one per line, each with the following space-separated fields:
.TP 3
*
The cluster name
.TP 3
*
The word "public" or "private", depending on whether the cluster is
included in a public cluster group in
.BR larvnet.conf (5).
.TP 3
*
The cluster phone, according to 
.BR larvnet.conf (5)
.TP 3
*
For each architecture listed in the first section, two numbers giving
the number of free and total machines of that architecture in the
cluster.
.SH EXAMPLE
The following example reports on machines of three architectures in
two clusters, one private and one public.  In the SIPB cluster, there
is one Indy and one O2 free out of a total of one Ultra-1, one Indy,
and two O2s, while in the W20-575 cluster there is one free Indy out
of 24 and no Ultra-1s or O2s.
.PP
.RS
.nf
ULTRA-1
INDY
O2
---
SIPB private 3-7788 0 1 1 1 1 2
W20-575 public 3-0103 0 0 1 24 0 0
.fi
.RE
.SH SEE ALSO
.BR larvnetd (8),
.BR cviewd (8),
.BR larvnet.conf (5)
.SH AUTHOR
Greg Hudson, MIT Information Systems
.br
Copyright 1998, 1999 by the Massachusetts Institute of Technology.
