# $Id: Makefile.athena,v 1.2 1999-12-16 01:59:36 danw Exp $

SHELL=/bin/sh

prepare:
	imake "-I$$XCONFIGDIR" -DUseInstalled "-DCONFIGDIR=$$XCONFIGDIR" \
		-DMWM_ONLY
	${MAKE} Makefiles

clean:
	${MAKE} clean

all:
	${MAKE} includes depend all

check:

install:
	${MAKE} install install.man DESTDIR="$$SRVD"
