# $Id: Makefile.athena,v 1.1 2000-11-26 05:32:19 ghudson Exp $

.PHONY: dist

dist:
	cp ${CONFIG_SITE} ./config.site.athena

prepare:
	cd build_unix && \
		CONFIG_SITE=`pwd`/../config.site.athena \
		../dist/configure --enable-compat185 

check:
	# Do nothing for check.

clean all:
	cd build_unix && ${MAKE} $@

install:
	cd build_unix && ${MAKE} DESTDIR=${SRVD} $@
