# $Id: Makefile.athena,v 1.3 2002-02-14 15:48:29 ghudson Exp $

.PHONY: dist

dist:
	cp ${CONFIG_SITE} ./config.site.athena

prepare:
	rm -f build_unix/config.cache
	cd build_unix && CONFIG_SITE=`pwd`/../config.site.athena \
	  ../dist/configure --enable-compat185 --enable-shared

check:
	# Do nothing for check.

clean all:
	cd build_unix && ${MAKE} $@

install:
	cd build_unix && \
	  ${MAKE} prefix="$$SRVD/usr/athena" install install_static
