\PstPolygon
\PstPolygon[PolyNbSides=11]
\PstPolygon[PolyOffset=2]
\PstPolygon[linecolor=red,PolyIntermediatePoint=0.2]
\PstPolygon[linestyle=dashed,PolyCurves,PolyOffset=2,
            PolyIntermediatePoint=0.75]
\PstPolygon[unit=2,PolyNbSides=9,PolyOffset=2]
\PstPolygon[unit=2,PolyNbSides=27,PolyOffset=7,PolyCurves,
            PolyIntermediatePoint=0.1]
