#!/bin/sh
#
# Gives you an interactive shell with Debathena repositories configured

if [ -z "$1" ] || [ -z "$2" ]; then
    echo "usage: daschroot <dist> <arch>"
    exit 1
fi
dist="$1"
arch="$2"
shift 2

if ! schroot -c "$dist-$arch-sbuild" -i >/dev/null; then
    exit $?
fi

session=$(schroot -c "$dist-$arch-sbuild" -b)
schroot -c "$session" -r -u root -- env SBUILD_BUILD_CONF_DISTRIBUTION="$dist" "$(readlink -f "$(dirname "$0")/chroot-sources")"
schroot -c "$session" -r "$@"
schroot -c "$session" -e
