#!/bin/sh

# Usage: upgrade-schroot SCHROOTNAME ...

# Updates the system packages in one or more schroots.

for i in "$@"; do
    sbuild-update "$@"
    sbuild-distupgrade "$@"
    sbuild-clean -c -r "$@"
done
