#!/bin/sh

# Usage: upgrade-schroot SCHROOTNAME ...

# Updates the system packages in one or more schroots.

for i in "$@"; do
    schroot -u root -c "$i" -- sh -c 'apt-get update && apt-get -y dist-upgrade && apt-get clean'
done
