#!/bin/sh

# This script runs as root at the end of a lightdm login session.
# See 'session-cleanup-script' in lightdm.conf

PATH=/sbin:/bin:/usr/sbin:/usr/bin

DIR=/usr/share/debathena-lightdm-config/session-cleanup.d

for i in `run-parts --list $DIR`; do
    . "$i"
done

