.\" $Id: gettime.8,v 1.1 1997-12-15 00:35:49 cfields Exp $
.\"
.\" Copyright 1997 by the Massachusetts Institute of Technology.
.\"
.\" Permission to use, copy, modify, and distribute this
.\" software and its documentation for any purpose and without
.\" fee is hereby granted, provided that the above copyright
.\" notice appear in all copies and that both that copyright
.\" notice and this permission notice appear in supporting
.\" documentation, and that the name of M.I.T. not be used in
.\" advertising or publicity pertaining to distribution of the
.\" software without specific, written prior permission.
.\" M.I.T. makes no representations about the suitability of
.\" this software for any purpose.  It is provided "as is"
.\" without express or implied warranty.
.\"
.TH GETTIME 8 "13 Dec 1997"
.SH NAME
gettime \- synchronize system clock with remote host
.SH SYNOPSIS
.B gettime
[
.B \-g granularity
] [
.B \-s
] 
.B hostname
.fi
.SH DESCRIPTION
.I gettime
is a simple program used to retrieve the time from a remote host
(specified by the required
.B hostname
argument) using the UDP Time Protocol defined in RFC868. It displays
the time acquired on the standard output. If the
.B \-s
option is specified and
.I gettime
is being run as root, the clock of the local workstation will also be
set. If the
.B \-g
option is specified as well, the time will only be set if the
workstation clock is more than
.B granularity
seconds out of synchronization with the remote host.
.I gettime
attempts to retrieve the time five times, with a five second timeout
on each attempt.

.SH AUTHOR
Craig Fields, MIT Information Systems
.br
Copyright (c) 1997 Massachusetts Institute of Technology
