#!/bin/sh

CONFIG=/etc/config
SETCONFIG="/sbin/chkconfig -f"
debug=1

configbool()
{
  if [ $debug = 1 ]; then
    echo $SETCONFIG "$1" "$2"
  else
    $SETCONFIG "$1" "$2"
  fi
}

configopt()
{
  if [ $debug = 1 ]; then
    echo "echo $2 > $CONFIG/$1"
  else
    echo "$2" > "$CONFIG/$1"
  fi
}

syncvar()
{
    case "$2" {
	true|on)
	    configbool "$1" on
	    ;;
	false|off)
	    configbool "$1" off
	    ;;
	*)
	    configopt "$1" "$2"
	    ;;
    }
}

remove()
{
  if [ $debug = 1 ]; then
    echo rm -f "$1"
  else
    rm -f "$1"
  fi
}

move()
{
  if [ $debug = 1 ]; then
    echo mv "$1" "$2"
  else
    mv "$1" "$2"
  fi
}

put()
{
  if [ $debug = 1 ]; then
    echo echo "$2 > $1"
  else
    echo "$2" > "$1"
  fi
}

. /etc/athena/rc.conf

syncvar timed $TIMESRV

if [ "${AFSCLIENT}" != "false" ]; then

	syncvar afsml true
	syncvar afsclient true

	if [ "${AFSCLIENT}" = "true" ]; then
		AFSCLIENT=4
	fi

	if [ "${TIMECLIENT}" = "false" ]; then
		AFSTIME = "-nosettime"
	fi

	syncvar afsd.options "$AFSTIME -stat 2000 -dcache 800 -daemons $AFSCLIENT -volumes 70"

else
	syncvar afsml false
	syncvar afsclient false
fi

if [ "${NFSSRV}" != "false" -o "${NFSCLIENT}" != "false" ]; then

	syncvar nfs true

	case "${NFSCLIENT}" {
	    true|false)
		remove $CONFIG/biod.options
		;;
	    *)
		syncvar biod.options "${NFSCLIENT}"
		;;
	}

	case "${NFSSRV}" {
	    true)
		remove $CONFIG/nfsd.options
		;;
	    false)
		syncvar nfsd.options 0
		;;
	    *)
		syncvar nfsd.options "${NFSSRV}"
		;;
	}
fi

if [ "${SENDMAIL}" = "false" ]; then
	move /etc/rc2.d/S50mail /etc/rc2.d/s50mail
else
	move /etc/rc2.d/s50mail /etc/rc2.d/S50mail
fi

syncvar snmpd $SNMP

if [ "${SAVECORE}" != "false" ]; then
  if [ "${SAVECORE}" = "true" ]; then
    minfree=30000000
  else
    minfree = ${SAVECORE}
  fi
else
    minfree=10000000000
fi
put /var/adm/crash/minfree $minfree

syncvar acct ${ACCOUNT}

syncvar quotacheck ${QUOTAS}
syncvar quotas ${QUOTAS}
