# $Id: Makefile.athena,v 1.2 1999-11-03 19:40:11 tb Exp $

SHELL=/bin/sh

prepare:
	rm -f Makefile
	imake -Iconfig -DTOPDIR=`pwd` -DUseInstalled
	${MAKE} Makefiles

clean:
	${MAKE} clean

all:
	${MAKE} includes depend all TOP=`pwd`

check:

install:
	${MAKE} install DESTDIR="$$SRVD" TOP=`pwd`
