# $Id: Makefile.athena,v 1.1 2000-11-08 19:55:47 ghudson Exp $

dist:
	# Do nothing.

prepare:
	./configure --enable-shared --enable-static --prefix=/usr/athena

clean:
	${MAKE} clean

all:
	${MAKE} all

check:

install:
	${MAKE} install DESTDIR="$$SRVD"
