# $Id: Makefile.athena,v 1.1 1996-10-13 04:29:15 ghudson Exp $

SHELL=/bin/sh

configure: force
	CC="$$COMPILER" ./configure

force:

clean:
	${MAKE} clean

all:
	${MAKE} all

check:

install:
	${MAKE} install DESTDIR="$$SRVD"
