#
# Copyright 2002 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
#ident	"$Id: Makefile,v 1.1.1.1 2003-02-14 19:55:13 rbasch Exp $"
#

CORE_DEPTH = ../../../..
include ../Makefile.com

DATAFILES += pkgdepend

all:: $(FILES)
publish:: all pkg

include ../Makefile.targ
