.\" $Id: access.5,v 1.4 1998-05-13 01:23:14 danw Exp $
.\"
.\" Copyright 1998 by the Massachusetts Institute of Technology.
.\"
.\" Permission to use, copy, modify, and distribute this
.\" software and its documentation for any purpose and without
.\" fee is hereby granted, provided that the above copyright
.\" notice appear in all copies and that both that copyright
.\" notice and this permission notice appear in supporting
.\" documentation, and that the name of M.I.T. not be used in
.\" advertising or publicity pertaining to distribution of the
.\" software without specific, written prior permission.
.\" M.I.T. makes no representations about the suitability of
.\" this software for any purpose.  It is provided "as is"
.\" without express or implied warranty.
.\"
.TH ACCESS 5 "4 April 1998"
.SH NAME
/etc/athena/access \- Athena login access control file
.SH DESCRIPTION
The file
.I /etc/athena/access
controls which users are allowed to log into an Athena system, and
also specifies which accounts are to be treated as local accounts.
.PP
Each line in
.I /etc/athena/access
contains two whitespace-separated fields and optionally some
additional text.  Lines beginning with "#" are ignored.  The first
field of a line is a username, "*inpasswd" to match any username in
the local passwd file, or "*" to match any username. (Ordering of
lines in the file is unimportant: the most specific matching line will
be used to determine a user's privileges.)  The second field is a
list of access bits: "l" for local login access, "r" for remote login
access, and "L" if the account should be considered local
(i.e. Athena-specific login activities should be suppressed for this
account).  A dash may be used as a placeholder for the access bits if
none are appropriate.  If whitespace and additional text is given
after the access bits, the additional text may be displayed to the
user by login programs if the user is not allowed to log in.
.SH SEE ALSO
al_get_access(3), al_login_allowed(3), al_is_local_acct(3)
.SH AUTHOR
Greg Hudson, MIT Information Systems
.br
Copyright 1998 by the Massachusetts Institute of Technology.
