.\" $Id: al_get_access.3,v 1.1 1998-05-07 17:11:25 ghudson Exp $
.\"
.\" Copyright 1998 by the Massachusetts Institute of
.\" Technology.
.\"
.\" Permission to use, copy, modify, and distribute this
.\" software and its documentation for any purpose and without
.\" fee is hereby granted, provided that the above copyright
.\" notice appear in all copies and that both that copyright
.\" notice and this permission notice appear in supporting
.\" documentation, and that the name of M.I.T. not be used in
.\" advertising or publicity pertaining to distribution of the
.\" software without specific, written prior permission.
.\" M.I.T. makes no representations about the suitability of
.\" this software for any purpose.  It is provided "as is"
.\" without express or implied warranty.
.\"
.TH AL_GET_ACCESS 3 "5 May 1998"
.SH NAME
al_get_access \- Read access bits and text for a user in the access file
.SH SYNOPSIS
.nf
.B #include <al.h>
.PP
.B int al_get_access(const char *\fIusername\fP, char **\fIaccess\fP,
.B	char **\fItext\fP)
.PP
.B cc file.c -lal -lhesiod
.fi
.SH DESCRIPTION
This function reads the access bits and explanatory text for a user
in the Athena access control file
.I /etc/athena/access
(see access(5)).  On successful return, the variable pointed to by
.I access
is set to the string of access bits for
.IR username ,
and the variable pointed to by
.I text
is set to the explanatory text, or to NULL if no explanatory text is
given on the appropriate line.  The caller may pass NULL for either
.I access
or
.I text
if it does not care about one or the other piece of information.  The
caller must free the returned strings when it is done using them.
.SH RETURN VALUES
.I al_get_access
may return the following values:
.TP 15
.I AL_SUCCESS
Access information was successfully read.
.TP 15
.I AL_ENOENT
The access file does not exist.
.TP 15
.I AL_EPERM
The access file could not be read due to a permissions problem.
.TP 15
.I AL_ENOUSER
There is no entry for
.I username
in the access file.
.TP 15
.I AL_ENOMEM
Memory was exhausted.
.SH SEE ALSO
al_login_allowed(3), al_is_local_acct(3)
.SH AUTHOR
Greg Hudson, MIT Information Systems
.br
Copyright 1998 by the Massachusetts Institute of Technology.
