.\" $Id: al_login_allowed.3,v 1.2 1998-01-26 06:35:52 danw Exp $
.\"
.\" Copyright 1997 by the Massachusetts Institute of Technology.
.\"
.\" Permission to use, copy, modify, and distribute this
.\" software and its documentation for any purpose and without
.\" fee is hereby granted, provided that the above copyright
.\" notice appear in all copies and that both that copyright
.\" notice and this permission notice appear in supporting
.\" documentation, and that the name of M.I.T. not be used in
.\" advertising or publicity pertaining to distribution of the
.\" software without specific, written prior permission.
.\" M.I.T. makes no representations about the suitability of
.\" this software for any purpose.  It is provided "as is"
.\" without express or implied warranty.
.\"
.TH AL_LOGIN_ALLOWED 3 "18 September 1997"
.SH NAME
al_login_allowed \- Determine if a user is allowed to log in
.SH SYNOPSIS
.nf
.B #include <al.h>
.PP
.B int al_login_allowed(const char *\fIusername\fP, int \fIisremote\fP,
.B 	char **\fIfiletext\fP)
.PP
.B cc file.c -lal -lhesiod
.fi
.SH DESCRIPTION
This function determines whether the user
.I username
is allowed to log in according to the Athena security model.  A user
may be denied access if:
.TP 2
*
.I /etc/nologin
exists and
.I username
is not listed as having uid 0 in the local passwd file.
.TP 2
*
.I /etc/nocreate
exists and
.I username
is not listed in the local passwd file.
.TP 2
*
.I /etc/noremote
exists,
.I isremote
is nonzero, and
.I username
is not listed in the local passwd file.
.TP 2
*
.I username
is not listed in the local passwd file and there is no Hesiod passwd
entry for
.IR username .
.TP 2
*
.I username
is not listed in the local passwd file and the Hesiod passwd entry for
.I username
has the same uid as some entry in the local passwd file.
.PP
If the user is denied login due to one of the three login files in
.IR /etc ,
then the variable pointed to by
.I filetext
is set to an allocated string (which must be freed by the caller)
containing the text of the relevant file.  Otherwise, the variable
pointed to by
.I filetext
is set to NULL. If the caller doesn't care about the contents of these
files, it can pass NULL for
.IR filetext .
.SH RETURN VALUES
.I al_login_allowed
may return the following values:
.TP 15
.I AL_SUCCESS
The user may log in.
.TP 15
.I AL_ENOUSER
There is no local or Hesiod passwd entry for
.IR username .
.TP 15
.I AL_EBADHES
The Hesiod passwd entry for
.I username
conflicts with a local passwd entry.
.TP 15
.I AL_ENOLOGIN
The user may not log in because of
.IR /etc/nologin .
.TP 15
.I AL_ENOREMOTE
The user may not log in because of
.IR /etc/noremote .
.TP 15
.I AL_ENOCREATE
The user may not log in because of
.IR /etc/nocreate .
.TP 15
.I AL_ENOMEM
Memory was exhausted.
.SH SEE ALSO
al_acct_create(3), al_strerror(3)
.SH AUTHOR
Greg Hudson, MIT Information Systems
.br
Copyright 1997 by the Massachusetts Institute of Technology.
