.\" $Id: al_strerror.3,v 1.1 1997-10-21 01:54:14 ghudson Exp $
.\"
.\" Copyright 1997 by the Massachusetts Institute of Technology.
.\"
.\" Permission to use, copy, modify, and distribute this
.\" software and its documentation for any purpose and without
.\" fee is hereby granted, provided that the above copyright
.\" notice appear in all copies and that both that copyright
.\" notice and this permission notice appear in supporting
.\" documentation, and that the name of M.I.T. not be used in
.\" advertising or publicity pertaining to distribution of the
.\" software without specific, written prior permission.
.\" M.I.T. makes no representations about the suitability of
.\" this software for any purpose.  It is provided "as is"
.\" without express or implied warranty.
.\"
.TH AL_STRERROR 3 "18 September 1997"
.SH NAME
al_strerror, al_free_errmem \- Obtain a string representation of a
login library error or warning code
.SH SYNOPSIS
.nf
.B #include <al.h>
.PP
.B const char *al_strerror(int \fIcode\fP, char **\fImemptr\fP)
.B void al_free_errmem(char *\fImem\fP)
.PP
.B cc file.c -lal
.fi
.SH DESCRIPTION
The
.I al_strerror
function obtains a string representation of the error or warning code
.IR code .
It may allocate memory for the returned string and place a pointer to
the allocated memory in the variable pointed to by
.IR memptr .
The caller must invoke
.I al_free_errmem
with the variable pointed to by
.I memptr
after the error string is used.
.SH SEE ALSO
al_login_allowed(3), al_acct_create(3), al_acct_revert(3)
.SH AUTHOR
Greg Hudson, MIT Information Systems
.br
Copyright 1997 by the Massachusetts Institute of Technology.
