.\" $Id: rpmupdate.8,v 1.1 2000-02-29 22:18:01 ghudson Exp $
.\"
.\" Copyright 2000 by the Massachusetts Institute of Technology.
.\"
.\" Permission to use, copy, modify, and distribute this
.\" software and its documentation for any purpose and without
.\" fee is hereby granted, provided that the above copyright
.\" notice appear in all copies and that both that copyright
.\" notice and this permission notice appear in supporting
.\" documentation, and that the name of M.I.T. not be used in
.\" advertising or publicity pertaining to distribution of the
.\" software without specific, written prior permission.
.\" M.I.T. makes no representations about the suitability of
.\" this software for any purpose.  It is provided "as is"
.\" without express or implied warranty.
.TH RPMUPDATE 8 "29 Feb 2000"
.SH NAME
rpmupdate \- Update workstation from one RPM list to another
.SH SYNOPSIS
.B rpmupdate [-np] \fIoldlist\fP \fInewlist\fP
.SH DESCRIPTION
.B rpmupdate
is normally invoked by
.BR update_ws (8)
to update an Athena Red Hat workstation from one list of RPMs to
another.
.B rpmupdate
accepts the following options:
.TP 5
.B \-n
Display what package updates would occur, but do not actually perform
them.
.TP 5
.B \-p
Apply the public workstation rules to decide what updates to perform,
instead of the private workstation rules.  If this option is
specified, the information in
.I oldlist
is not used.
.PP
The files
.I oldlist
and
.I newlist
should each contain a list of RPM pathnames, possibly followed by
whitespace and an epoch number.  The RPM pathnames may be relative to
the current directory and must include the package name, version, and
release of the RPM in the canonical format; for example, the line:
.PP
.RS
redhat-6.1/RedHat/RPMS/kdebase-1.1.2-10.i386.rpm 2
.RE
.PP
would indicate an RPM with a package name of kdebase, a version of
1.1.2, a release of 10, and an epoch of 2.  If the epoch number is not
included, it is assumed that the RPM does not have one.
.PP
After reading the old list, new list, and installed list of RPMs, 
.B rpmupdate
decides which packages to erase, install, and update according to
either the public or private workstation rules.  The public
workstation rules are:
.IP *
If a locally installed package is not at the same epoch, version, and
release as the package in the new list, the package in the new list is
installed.
.IP *
If a locally installed package is not present in the new list, the
package is removed.
.PP
The private workstation rules are:
.IP *
If a locally installed package is at the same epoch, version, and
release as the package in the old list, or if a package is present in
the new list but is not locally installed and is not present in the
old list, apply the public workstation rules to this package.
.IP *
If the new list contains an upgrade for a locally installed package,
install the upgrade.
.PP
Thus, on private workstations, packages which are in sync with the
existing release will remain in sync with the new release, but a
package from the release list which has been erased on a private
workstation will stay erased, a package which has been locally
upgraded will stay upgraded until the release has a newer version
available, and a package which has been locally installed will stay
installed.
.SH "SEE ALSO"
.BR update_ws (8)
.SH AUTHOR
Greg Hudson, MIT Information Systems
.br
Copyright 2000 by the Massachusetts Institute of Technology.
