#!/bin/sh

PATH=/etc:/usr/ucb:/bin:/usr/bin:.:/etc/athena:/bin/athena:/usr/athena
export PATH
SHELL=/bin/echo
export SHELL

attach -q -n -h library

/usr/bin/X11/xset -display :0 fp= "/usr/lib/X11/fonts/misc/,/usr/lib/X11/fonts/75dpi/,/usr/lib/X11/fonts/100dpi/"

/mit/library/bin/library -timeout -geometry 80x25+270+270

detach -q library

exit 0
