#!/bin/sh
# Script to bounce the packs on an Athena workstation
#
#	$Source: /afs/dev.mit.edu/source/repository/athena/etc/xdm/conf/reactivate,v $
#	$Author: probe $
#	$Header: /afs/dev.mit.edu/source/repository/athena/etc/xdm/conf/reactivate,v 1.3 1990-11-19 06:51:31 probe Exp $

PATH=/bin:/usr/ucb:/usr/bin; export PATH

umask 22
. /etc/rc.conf

case "${SYSTEM}" in
ULTRIX*)
	cp=/bin/cp
	partition=/var
	;;
*)
	cp=/bin/cp -p
	partition=/site
esac

if [ "${USER+x}" = x ]; then
	quiet=-q
else
	echo Reactivating workstation...
	quiet=
fi

# Flush all NFS uid mappings
/bin/athena/nfsid $quiet -p -a

# Perform an update if appropriate (do this early in the sequence)
if [ -f /srvd/auto_update ] ; then 
	/srvd/auto_update reactivate
fi

# Tell the Zephyr hostmanager to reset state
if [ -f /etc/athena/zhm.pid ] ; then 
	kill -HUP `cat /etc/athena/zhm.pid`
fi

# Then clean temporary areas (including temporary home directories)
/bin/mv /tmp/.X11-unix ${partition}/.X11-unix
/bin/rm -rf /tmp/
/bin/mv ${partition}/.X11-unix /tmp/.X11-unix
if [ -f /usr/bin/find ] ;  then
	(cd /usr/tmp; find . -mtime +4 -exec /bin/rm -f {} \; )
fi

# Next, restore password, group, and AFS-cell files
if [ -f /etc/passwd.local ] ; then
	${cp} /etc/passwd.local /etc/ptmp
	/bin/mv -f /etc/ptmp /etc/passwd
fi
if [ -f /etc/group.local ] ; then
	${cp} /etc/group.local /etc/gtmp
	/bin/mv -f /etc/gtmp /etc/group
fi
if [ -f /afs/athena.mit.edu/service/CellServDB ] ; then
	${cp} /afs/athena.mit.edu/service/CellServDB \
		   /usr/vice/etc/CellServDB.public
fi
if [ -f /afs/athena.mit.edu/service/aklog ] ; then
	${cp} /afs/athena.mit.edu/service/aklog \
		   /bin/athena/aklog
fi

# punt any processes owned by users not in /etc/passwd
/etc/athena/cleanup

# Finally, detach all remote filesystems
/bin/athena/detach -O -h -n $quiet -a


# Now start activate again

/etc/athena/save_cluster_info

if [ -f /etc/clusterinfo.bsh ] ; then
	. /etc/clusterinfo.bsh
else
	if [ "${RVDCLIENT}" = "true" ]; then
		echo "Can't find library servers."		>${OUTPUT}
		exit 1
	fi
fi

if [ "${RVDCLIENT}" = "true" ]; then
	if [ "${USRLIB}" = "" ]; then
		/bin/athena/attach	$quiet -h -n -o hard  $SYSLIB
	else
		/bin/athena/attach	$quiet -h -n -o hard  $SYSLIB \
					$quiet -h -n -o hard  $USRLIB
	fi
fi

# set font path now that we're activated
if [ -f /usr/bin/X11/xset ]; then
	/usr/bin/X11/xset -display :0 fp= "/usr/lib/X11/fonts/misc/,/usr/lib/X11/fonts/75dpi/,/usr/lib/X11/fonts/100dpi/"
fi

if [ -f /usr/athena/access_off ]; then /usr/athena/access_off; fi

if [ -f /etc/athena/reactivate.local ]; then
	/etc/athena/reactivate.local
fi

exit 0
