#!/bin/sh 

#	Top level Xsession file for all users
#
#	$Header: /afs/dev.mit.edu/source/repository/athena/etc/xdm/conf/Xsession,v 1.6 1991-06-28 20:23:34 probe Exp $
#	$Source: /afs/dev.mit.edu/source/repository/athena/etc/xdm/conf/Xsession,v $
#	$Author: probe $
#

trap 'kdestroy; exit 0' 1 2 15

initlib="/usr/athena/lib/init"
defsession=$1
defsessioncmd="$2"

case $defsession in
1|4)
	if [ -f .xsession ]; then
		session=".xsession"
	else
		session="$initlib/xsession"
	fi
	;;
2)
	NOCALLS=1; export NOCALLS
	session="$initlib/xsession"
	;;
3)
	session="xterm -ls -geometry 80x24+280+220 -display :0.0"
	;;
5)
	session="$defsessioncmd"
	;;
esac

# Set the tty characteristics of the parent (console window)
# Redirect stdin since some versions of stty use it instead of stdout.
stty dec 0<&1 
$session

status=$?
if [ $status != 0 ]; then
		echo ERROR:
		echo "Xsession returned non-zero status."
		echo ""
		echo 'Select the login option to "Ignore your customizations"'
		echo 'to login and repair your dot files.'
		kdestroy			# destroy tickets.
		sleep 10
		exit $status
fi


# Cannot detach homedir here, since this script is executed in the users
# homedir.

kdestroy				# destroy tickets.
cd /tmp
detach $USER
unlog
sleep 3					# let them see any messages (quickly)
exit 0
