# $Id: Makefile.athena,v 1.2 2002-02-17 21:04:57 ghudson Exp $

dist:

prepare:
	${MAKE} setup CFG="--prefix=/usr/athena"

clean:
	${MAKE} clean

all:
	${MAKE}

check:

install: force
	${MAKE} install DESTDIR="$$SRVD"

force:
