.TH SCROLLKEEPER-REBUILDDB 8 "Dec 5, 2001" "scrollkeeper"
.SH NAME
scrollkeeper-rebuilddb \- rebuild the scrollkeeper document catalog database
.SH SYNOPSIS
.B "scrollkeeper-rebuilddb"
[-p  
.IR path
]
[-v]
[-q]

.SH DESCRIPTION
This rebuilds the ScrollKeeper database from the original OMF metadata
files and documents.  Under normal situations, this tool is not
necessary.  It is useful however if the database becomes corrupt, which
could be caused by interruption of ScrollKeeper during an update of
the database.

Errors and warnings are logged to /var/log/scrollkeeper.log.

.SH OPTIONS
.TP
.I \-p \fIpath\fP 
Use \fIpath\fP as the ScrollKeeper database directory.
.TP
.I \-v 
Verbose.  Show warnings and error messages in addition to 
logging them to /var/log/scrollkeeper.log.
.TP
.I \-q
Run in quiet mode, suppressing output of all but the most serious warning and
error messages to STDOUT.  Note that most output to the log file will be
unchanged.

.SH FILES
.PD 0
.B /var/lib/scrollkeeper/scrollkeeper_docs
.br
.B /var/lib/scrollkeeper/TOC/<docnumber>
.br
.B /var/lib/scrollkeeper/<locale>/scrollkeeper_cl.xml
.br
.B /var/lib/scrollkeeper/<locale>/scrollkeeper_extended_cl.xml
.br
.B /var/log/scrollkeeper.log

.SH AUTHOR
Laszlo Kovacs   <laszlo.kovacs@sun.com>
.br
Dan Mueth       <d-mueth@uchicago.edu>

.SH SEE ALSO
scrollkeeper-config(1),
scrollkeeper-gen-seriesid(1),
scrollkeeper.conf(5),
scrollkeeper(7),
scrollkeeper-preinstall(8),
scrollkeeper-update(8) 

