# $Id: Makefile.athena,v 1.3 2000-03-31 14:59:12 ghudson Exp $

SHELL=/bin/sh

dist:

prepare:
	rm -f build/config.cache
	cd build && CFLAGS='-g -I/usr/include/db1' LIBS=-ldb1 \
		./configure --disable-curses --disable-db \
		--prefix=/usr --bindir=/bin

clean:
	cd build && ${MAKE} clean

all:
	cd build && ${MAKE} all

check:

install:
	cd build && ${MAKE} install DESTDIR="$$SRVD"
