#undef EEL_POSSIBLE_FONT_DIRECTORIES
#undef EEL_BUILD_MESSAGE
#undef EEL_SOURCE_DIRECTORY
#undef ENABLE_NLS
#undef ENABLE_PROFILER
#undef HAVE_CATGETS
#undef HAVE_GETTEXT
#undef HAVE_LC_MESSAGES
#undef HAVE_STPCPY
#undef GNOME_EXPLICIT_TRANSLATION_DOMAIN
#undef GETTEXT_PACKAGE
#undef HAVE_BIND_TEXTDOMAIN_CODESET
#undef HAVE_RENDER
#define HAVE_GTK_MULTIHEAD /* needed for egg-screen-exec.c */
