# $Id: Makefile.athena,v 1.3 1996-10-14 16:53:30 ghudson Exp $

SHELL=/bin/sh

configure: force
	./configure --site=athena

force:

clean:
	${MAKE} clean

all:
	${MAKE} depend all CC="$$COMPILER"

check:

install:
	${MAKE} install DESTDIR="$$SRVD"
