# $Id: Makefile.athena,v 1.1 1996-10-12 22:05:40 ghudson Exp $

SHELL=/bin/sh

configure:
	CC="$$COMPILER" ./configure --site=athena

clean:
	${MAKE} clean

all:
	${MAKE} depend all

check:

install:
	${MAKE} install install.man DESTDIR="$$SRVD"
