# $Id: Makefile.athena,v 1.2 1996-10-13 04:28:57 ghudson Exp $

SHELL=/bin/sh

configure: force
	CC="$$COMPILER" ./configure --site=athena

force:

clean:
	${MAKE} clean

all:
	${MAKE} depend all

check:

install:
	${MAKE} install DESTDIR="$$SRVD"
