/*
 * This file was generated by orbit-idl - DO NOT EDIT!
 */

#include <string.h>
#include "sample-service.h"

#if ( (TC_IMPL_TC_Trilobite_Eazel_Sample_0 == 's') \
&& (TC_IMPL_TC_Trilobite_Eazel_Sample_1 == 'a') \
&& (TC_IMPL_TC_Trilobite_Eazel_Sample_2 == 'm') \
&& (TC_IMPL_TC_Trilobite_Eazel_Sample_3 == 'p') \
&& (TC_IMPL_TC_Trilobite_Eazel_Sample_4 == 'l') \
&& (TC_IMPL_TC_Trilobite_Eazel_Sample_5 == 'e') \
&& (TC_IMPL_TC_Trilobite_Eazel_Sample_6 == '_') \
&& (TC_IMPL_TC_Trilobite_Eazel_Sample_7 == 's') \
&& (TC_IMPL_TC_Trilobite_Eazel_Sample_8 == 'e') \
&& (TC_IMPL_TC_Trilobite_Eazel_Sample_9 == 'r') \
&& (TC_IMPL_TC_Trilobite_Eazel_Sample_10 == 'v') \
&& (TC_IMPL_TC_Trilobite_Eazel_Sample_11 == 'i') \
&& (TC_IMPL_TC_Trilobite_Eazel_Sample_12 == 'c') \
&& (TC_IMPL_TC_Trilobite_Eazel_Sample_13 == 'e') \
) && !defined(TC_DEF_TC_Trilobite_Eazel_Sample)
#define TC_DEF_TC_Trilobite_Eazel_Sample 1
const struct CORBA_TypeCode_struct TC_Trilobite_Eazel_Sample_struct = {
   
      {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},

   CORBA_tk_objref, "Sample", "IDL:Trilobite/Eazel/Sample:1.0",
   0, 0,
   NULL,
   NULL,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
CORBA_unsigned_long Trilobite_Eazel_Sample__classid = 0;
