.\" $Header: /afs/dev.mit.edu/source/repository/athena/etc/xdm/xlogin/timeout.1,v 1.1 1990-11-16 16:03:54 mar Exp $
.TH DM 8 "16 November 1990"
.ds ]W MIT Project Athena
.SH NAME
.nf
timeout \- run an application and force it to exit if the user is inactive
.fi
.SH SYNOPSIS
.nf
timeout seconds application command line
.fi
.SH DESCRIPTION
\fITimeout\fR will execute the specified command line.  Note that the
user's search path will not be used in starting the application, so
the complete path to the program must be specified.  If the user does
not type anything for \fIseconds\fR seconds, \fItimeout\fR will kill
the application and then exit itself.  If the application exits before
it has been idle too long, \fItimeout\fR will exit as well.

.SH EXAMPLE
.nf
timeout 60 /usr/athena/olh -tty
.fi
This will run OnLine Help in terminal mode, and force it to quit if
the user goes for more than 1 minute without typing anything.

.SH DIAGNOSTICS
.nf
timeout: Failed to exec application ...
.fi
This is printed if it can't find the application.  Make sure you
specify the complete path name.

.nf
MAX IDLE TIME REACHED.
.fi
This is printed just before \fItimeout\fR kills the application.

.SH AUTHOR
Mark Rosenstein, MIT Project Athena
.br
Copyright (c) 1990 Massachusetts Institute of Technology
