.\" $Header: /afs/dev.mit.edu/source/repository/athena/etc/xdm/xlogin/xlogin.8,v 1.4 1991-06-28 20:27:32 probe Exp $
.TH XLOGIN 8 "16 November 1990"
.ds ]W MIT Project Athena
.SH NAME
xlogin \- open X login window with pre-login options and screen saver
.SH SYNOPSIS
.nf
xlogin -config \fIdirectory\fR [X-options]
.fi
.SH DESCRIPTION
\fIXlogin\fR is used to login users on the display head of a
workstation.  It handles a number of login options, applications that
can be run without logging in, and a screensaver mode.  It also
handles reactivating the workstation while it is idle.

If the user requests a console login, \fIXlogin\fR will exit with
status 2.  On successful login, it will exec the session script.  On
fatal errors or non recoverable login failures, it will exit.
.SH OPTIONS
The following command line options are available in addition to the
usual X toolkit options and the resource file:
.IP -config \fIdirectory\fR
Names the directory the resource files are found in.  It will first
load \fBXlogin\fR from that directory, then if \fBXlogin.local\fR
exists, resources in this file will override those in the first file.
.IP -save \fIseconds\fR
Amount of idle time before the screen saver kicks in
.IP -move \fIseconds\fR
How often the message on the screen saver moves around the screen
.IP -blink \fImilliseconds\fR
How long to wait between show successive frames while blinking the
owl's eyes.
.IP -reactivate \fIscript\fR
Name of script to run to reactivate the workstation.  This is only run
while no one is logged in.
.IP -idle \fIseconds\fR
How long to let the machine lie idle before attempting to reactivate it.
.IP -wait
How long to wait for a reactivation to finish before giving up and
continuing.
.IP -restart
How long to spend in screensaver state before exiting so that the X
server will be restarted.
.IP -tty
Name of the tty to log the user in on.
.IP -session
Name of the global session script to run when logging the user in.
.SH RESOURCES
There are keyboard accelerators for the menu items.  The six
things on the "Login Options" menu may be selected using keys F1
through F6, respectively.  The first nine things on the "Other
Options" menu may be selected using keys SHIFT-F1 through SHIFT-F9.
The "Page Up" or "Prev Screen" key will display the console window,
while the "Page Down" or "Next Screen" key will remove it.  CONTROL-P
will shutdown the window system.

The following resources correspond to the options named above:
.IP *saveTimeout
Amount of idle time before the screen saver kicks in
.IP *moveTimeout
How often the message on the screen saver moves around the screen
.IP *blinkTimeout
How long to wait between show successive frames while blinking the
owl's eyes.
.IP *reactivateProg
Name of script to run to reactivate the workstation.  This is only run
while no one is logged in.
.IP *reactivateTimeout
How long to let the machine lie idle before attempting to reactivate it.
.IP *activateTimeout
How long to wait for a reactivation to finish before giving up and
continuing.
.IP *restartTimeout
How long to spend in screensaver state before exiting so that the X
server will be restarted.
.IP *loginTty
Name of the tty to log the user in on.
.IP *sessionScript
Name of the global session script to run when logging the user in.
.SH "SEE ALSO"
dm(8), console(8)
.SH AUTHORS
Mark Rosenstein, Chris VanHaren, Craig Fields of MIT Project Athena
.br
Copyright (c) 1990 Massachusetts Institute of Technology
.SH BUGS
Does not handle screensaver for multi-screened X servers.
