#!/bin/sh
set -e

name=nmh
daversionappend=debathena1

dir=$(cd "$(dirname "$0")"; pwd)

hack_package () {
    cp -a "$dir/nmh-mbx_close.dpatch" debian/patches/
    echo nmh-mbx_close.dpatch >> debian/patches/00list
    append_description <<EOF
 .
 This package was rebuilt for the Debathena project to add a patch
 to avoid losing mail if close() fails (as it can in AFS if you run
 over quota) when writing mailbox files.
EOF
    add_changelog 'Avoid losing mail if close() fails, as it can in AFS.'
    add_debathena_provides
    munge_sections
}

. ../common/debathenificator.sh
