# $Id: Makefile.athena,v 1.3 1996-11-20 15:44:03 ghudson Exp $

SHELL=/bin/sh

prepare:
	rm -f config.cache
	./configure --with-x-toolkit --sharedstatedir=/var/tmp --with-pop \
		--with-hesiod --with-kerberos

clean:
	${MAKE} clean

all:
	${MAKE} all

check:

install:
	${MAKE} install "DESTDIR=$$SRVD"
