# $Id: Makefile.athena,v 1.2 1996-10-13 21:31:35 ghudson Exp $

SHELL=/bin/sh

configure: force
	rm -f config.cache
	./configure --with-x-toolkit --sharedstatedir=/var/tmp --with-pop \
		--with-hesiod --with-kerberos

force:

clean:
	${MAKE} clean

all:
	${MAKE} all

check:

install:
	${MAKE} install "DESTDIR=$$SRVD"
