.\" This file uses -man macros.
.\" 
.TH BOS "" "30 April 1990" " " ""
.SH NAME
bos - suite of commands for contacting the AFS Basic OverSeer (BOS) Server.
.SH SYNOPSIS
.B bos <\fIoption\fR>
.PP
Each of the the following operation codes is a valid <\fIoption\fR> and has its own set of associated arguments.  See the "OPTIONS" section below for syntax definitions.
.PP
.I addhost       
- add host to cell dbase
.br
.I addkey
- add keys to key dbase (kvno 999 is bcrypt)
.br
.I adduser
- add users to super-user list
.br
.I apropos
- search by help text
.br
.I create
- create a new server instance
.br
.I delete
- delete a server instance
.br
.I exec
- execute shell command on server
.br
.I getdate
- get dates for programs
.br
.I getrestart
- get restart times
.br
.I help
- get help on commands
.br
.I install
- install program
.br
.I listhosts
- get cell host list
.br
.I listkeys
- list keys
.br
.I listusers
- list super-users
.br
.I prune
- prune server files
.br
.I removehost
- remove host from cell dbase
.br
.I removekey
- remove keys from key dbase
.br
.I removeuser
- remove users from super-user list
.br
.I restart
- restart all processes
.br
.I salvage
- salvage partition or volumes
.br
.I setauth
- set authentication required flag
.br
.I setcellname
- set cell name
.br
.I setrestart
- set restart times
.br
.I shutdown
- shutdown all processes
.br
.I start
- start running a server
.br
.I startup
- start all processes
.br
.I status
- show server instance status
.br
.I stop
- halt a server instance
.br
.I uninstall
- uninstall program
.SH DESCRIPTION
The commands in the \fBbos\fR suite are an interface to the \fIBasic OverSeer (BOS) Server\fR, an AFS server process that aids system administrators and operators in the efficient administration of AFS.  There are \fBbos\fR commands that allow system administrators to start and stop server processes at will, check on server process status, install new binaries for server processes, and maintain files of system configuration information.
.SH OPTIONS
.I addhost 
- add host to cell dbase
.br
syntax: bos addhost -server <machine name>  -host <host name>+ [-cell <cell name>] [-noauth]  [-help]
.PP
.I addkey 
- add keys to key dbase (kvno 999 is bcrypt)
.br
syntax: bos addkey  -server <machine name>  -key <key>   -kvno <key version number> [-cell <cell name>]  [-noauth]  [-help]
.PP
.I adduser 
- add users to super-user list
.br
syntax: bos adduser  -server <machine name>  -user <user names>+ [-cell <cell name>]  [-noauth]  [-help]
.PP
.I apropos 
- search by help text
.br
syntax: bos apropos -topic <help string>  [-help]
.PP
.I create 
- create a new server instance
.br
syntax: bos create  -server <machine name>  -instance <server process name> -type <server type>  -cmd <command lines>+ [-cell <cell name>] [-noauth]  [-help]
.PP
.I delete  
- delete a server instance
.br
syntax: bos delete  -server <machine name>  -instance <server process name>+  [-cell <cell name>]  [-noauth]  [-help]           
.PP
.I exec 
- execute shell command on server
.br
syntax: bos exec  -server <machine name>  -cmd <command to execute>  [-cell <cell name>]  [-noauth]  [-help]          
.PP
.I getdate  
- get dates for programs 
.br
syntax: bos getdate  -server <machine name>  -file <files to check>+  [-dir <destination dir>]  [-cell <cell name>]  [-noauth]  [-help] 
.PP
.I getrestart 
- get restart times
.br 
syntax: bos getrestart  -server <machine name>  [-cell <cell name>]  [-noauth]  [-help]
.PP
.I help 
- get help on commands
.br
syntax: bos help  [-topic <help string>+]  [-help]
.PP
.I install 
- install program
.br
syntax: bos install  -server <machine name>  -file <files to install>+  [-dir <destination dir>]  [-cell <cell name>]  [-noauth]  [-help]
.PP              
.I listhosts 
- get cell host list
.br
syntax: bos listhosts  -server <machine name>  [-cell <cell name>]  [-noauth]  [-help] 
.br
alias:
.I bos getcell 
.PP
.I listkeys 
- list keys
.br 
syntax: bos listkeys  -server <machine name>  [-cell <cell name>]  [-noauth]  [-help]
.PP
.I listusers 
- list super-users
.br
syntax: bos listusers  -server <machine name>  [-cell <cell name>]  [-noauth]  [-help]
.PP
.I prune 
- prune server files
.br
syntax: bos prune  -server <machine name>  [-bak]  [-old]  [-core]  [-all]  [-cell <cell name>]  [-noauth]  [-help]
.PP
.I removehost 
- remove host from cell dbase
.br
syntax: bos removehost  -server <machine name>  -host <host name>+  [-cell <cell name>]  [-noauth]  [-help]
.PP
.I removekey 
- remove keys from key dbase
.br
syntax: bos removekey -server <machine name>  -kvno <key version number>+  [-cell <cell name>]  [-noauth]  [-help]
.PP
.I removeuser 
- remove users from super-user list
.br
syntax: bos removeuser  -server <machine name>  -user <user names>+  [-cell <cell name>]  [-noauth]  [-help]
.PP
.I restart 
- restart all processes
.br
syntax: bos restart  -server <machine name>  [-instance <instances>+]  [-bosserver]  [-cell <cell name>]  [-noauth]  [-help]
.PP
.I salvage 
- salvage partition or volumes
.br
syntax: bos salvage  -server <machine name>  [-partition <salvage partition>] [-volume <salvage volume number>] [-file <salvage log output file>]  [-all] [-cell <cell name>] [-noauth]  [-help]
.PP
.I setauth 
- set authentication required flag
.br
syntax: bos setauth  -server <machine name>  -authrequired <on or off:authentication
required for admin requests>  [-cell <cell name>] [-noauth]  [-help]
.PP
.I setcellname 
- set cell name
.br
syntax: bos setcellname  -server <machine name>  -name <cell name>  [-cell <cell name>]  [-noauth]  [-help]
.PP
.I setrestart 
- set restart times
.br
syntax: bos setrestart  -server <machine name>  -time <time to restart server> [-general]  [-newbinary]  [-cell <cell name>]  [-noauth]  [-help]
.PP
.I shutdown 
- shutdown all processes
.br
syntax: bos shutdown  -server <machine name>  [-instance <instances>+] [-wait]  [-cell <cell name>]  [-noauth]  [-help]
.PP                 
.I start 
- start running a server
.br
syntax: bos start  -server <machine name>  -instance <server process name>+  [-cell <cell name>]  [-noauth]  [-help]                   
.PP
.I startup 
- start all processes
.br
syntax: bos startup  -server <machine name>  [-instance <instances>+]  [-cell <cell name>]  [-noauth]  [-help] 
.PP
.I status 
- show server instance status
.br
syntax: bos status  -server <machine name>  [-instance <server process name>+]  [-long]  [-cell <cell name>]  [-noauth]  [-help] 
.PP
.I stop 
- halt a server instance
.br
syntax: bos stop  -server <machine name>  -instance <server process name>+  [-wait]  [-cell <cell name>]  [-noauth]  [-help]
.PP
.I uninstall  
- uninstall program
.br
syntax: bos uninstall  -server <machine name>  -file <files to uninstall>+  [-dir <destination dir>]  [-cell <cell name>]  [-noauth]  [-help]



