.\" This file uses -man macros.
.\"	@(#)printf.3s	6.3 (Berkeley) 6/5/86
.\"
.TH Tokens 1V "Nov 30, 1987" "PRPQ 5799-CGZ: IBM 4.3/RT, Rel 1 " " "
.SH NAME
tokens - Get information about the set of tokens held by the Andrew Cache Manager.
.SH SYNOPSIS
.B tokens
.SH DESCRIPTION
This command enables users to query the Andrew Cache Manager for information about the set of authentication tokens it holds.  At most one token per cell is remembered for a user.  Printed for each token is the user ID, the cell name in which it's valid and its expiration time.
.SH "SEE ALSO"
.PP
log(1), login(1), su(1), unlog(1)
