.TH ADD 1 "9 August 1991"
.ds ]W MIT Project Athena
.SH NAME
add - attach a filesystem, add it to your path and manpath
.SH SYNOPSIS
add filesystemname
.SH DESCRIPTION
\fIadd\fR is an alias provided by the standard Athena dotfiles.  It is
intended to make the process of using software that is stored in remote
filesystems easier.  It takes one argument, the name of a filesystem to
\fIadd\fR.

Typing "alias add" will reveal that renew simply executes the series
of commands:

.ti 10
set dir = `attach -p \!*` && \\
.ti 12
        if ("$PATH" =~ *"$dir/$bindir"*) rehash && \\
.ti 12
        extend PATH $dir/$bindir && \\
.ti 12
        extend MANPATH $dir/man && \\
.ti 12
        unset dir

The alias first \fIattach\fRes the filesytem named on the command-line,
finds out where it attaches to (using the -p option to \fIattach\fR),
adds that path with the appropriate binary directory (vaxbin, rtbin,
etc.) to your search path, and adds the man dir to your MANPATH, so that
\fIman\fR can find manpages that may be installed in that filesystem.
.SH FILES
.PP
/usr/athena/lib/init/cshrc    global Athena cshrc file
.br
~/.cshrc                      users's cshrc file
.SH "SEE ALSO"
attach(1), man(1), csh(1)
