.TH ADD 1 "9 August 1991"
.ds ]W MIT Project Athena
.SH NAME
add - attach a filesystem, add it to your path and manpath
.SH SYNOPSIS
add [-v] filesystemname
.SH DESCRIPTION
\fIadd\fR is an alias provided by the standard Athena dotfiles.  It is
intended to make the process of using software that is stored in remote
filesystems easier.  It requires one argument, the name of a filesystem to
\fIadd\fR.  It also has an optional argument, \fI-v\fR, which will
cause it to be verbose and print out what it is doing.

\fIadd\fR may be used interactively while logged in, or in your
~/.environment file.

Typing "alias add" will reveal that add is some shell script which
uses \fIattach\fR and modifies your PATH and MANPATH environment
variables.  It makes use of \fIextend\fR which is another alias
provided by Athena.  \fIAdd\fR first parses its arguments.  Then it
invokes \fIattach\fR.  If it is to be verbose, it will invoke it
twice: once to display the message, and again to find out where the
locker is mounted.  Next it adds the appropriate binary directory
(vaxbin, etc) to your search path so that you can find programs in the
locker, and adds the man directory to your MANPATH so that \fIman\fR
can find manpages that may be installed in that filesystem.
.SH FILES
.PP
/usr/athena/lib/init/cshrc    global Athena cshrc file
.br
~/.cshrc                      users's cshrc file
.SH "SEE ALSO"
attach(1), man(1), csh(1)
