# $Id: Makefile.athena,v 1.1 2003-02-14 23:14:35 zacheiss Exp $

SHELL=/bin/sh

dist:
	cp "$$CONFIG_SITE" config.site.athena

prepare:
	rm -f src/config.cache
	cd src && CONFIG_SITE=`pwd`/../config.site.athena ./configure

clean:
	cd src && ${MAKE} clean

all:
	cd src && ${MAKE} all

install:
	cd src && ${MAKE} install DESTDIR="$$SRVD"
