# $Id: Makefile.athena,v 1.8.4.1 1999-11-29 14:55:21 tb Exp $

SHELL=/bin/sh

prepare:
	rm -f config.cache
	PERL=/usr/athena/bin/perl ./configure --disable-suid-ssh \
		--with-kerberos5=${ATHTOOLROOT}/usr/athena \
		--enable-kerberos-tgt-passing \
		--with-libwrap=${ATHTOOLROOT}/usr/athena/lib \
		--with-rsh=/usr/athena/bin/rsh

clean:
	${MAKE} clean

all:
	${MAKE} depend all

check:

install:
	${MAKE} install install_prefix="$$SRVD"
