# $Id: Makefile.athena,v 1.2 1997-11-18 19:32:49 danw Exp $

SHELL=/bin/sh

prepare:
	rm -f config.cache
	./configure --disable-suid-ssh --sbindir=/etc/athena \
		--with-kerberos5=${ATHTOOLROOT}/usr/athena \
		--enable-kerberos-tgt-passing

clean:
	${MAKE} clean

all:
	${MAKE} depend all

check:

install:
	${MAKE} install install_prefix="$$SRVD"
