.\"  -*- nroff -*-
.\"
.\" ssh-keygen.1
.\"
.\" Author: Tatu Ylonen <ylo@cs.hut.fi>
.\"
.\" Copyright (c) 1995 Tatu Ylonen <ylo@cs.hut.fi>, Espoo, Finland
.\"                    All rights reserved
.\"
.\" Created: Sat Apr 22 23:55:14 1995 ylo
.\"
.\" $Id: ssh-keygen.1,v 1.1.1.1 1997-10-17 22:26:00 danw Exp $
.\" $Log: not supported by cvs2svn $
.\" Revision 1.9  1997/04/27 21:59:09  kivinen
.\" 	Added F-SECURE stuff.
.\"
.\" Revision 1.8  1997/03/25 05:42:26  kivinen
.\" 	Small changes from Sakari. Changed ylo's email to @ssh.fi.
.\"
.\" Revision 1.7  1996/10/03 23:27:59  ylo
.\" 	A minor clarification.
.\"
.\" Revision 1.6  1996/10/03 23:27:02  ylo
.\" 	Fixed a typo.
.\"
.\" Revision 1.5  1996/10/03 16:54:57  ttsalo
.\" 	New feature: updating the keyfiles' cipher type.
.\"
.\" Revision 1.4  1996/09/29 01:00:38  ylo
.\" 	Updated to use 3DES.
.\"
.\" Revision 1.3  1996/08/06 07:55:01  ylo
.\" 	Added a note about empty passphrases.
.\"
.\" Revision 1.2  1996/05/30 16:10:50  ylo
.\" 	Documented -f.
.\"
.\" Revision 1.1.1.1  1996/02/18 21:38:13  ylo
.\" 	Imported ssh-1.2.13.
.\"
.\" Revision 1.3  1995/08/29  22:30:01  ylo
.\" 	Improved manual pages from Andrew Macpherson.
.\"
.\" Revision 1.2  1995/07/13  01:36:30  ylo
.\" 	Removed "Last modified" header.
.\" 	Added cvs log.
.\"
.\" $Endlog$
.\"
.nr CO 0
.ie \n(CO .TH SSH-KEYGEN 1 "November 8, 1995" "F-SECURE SSH" "F-SECURE SSH"
.el .TH SSH-KEYGEN 1 "November 8, 1995" "SSH" "SSH"

.SH NAME
ssh-keygen \- authentication key pair generation

.SH SYNOPSIS
.LP
.B ssh-keygen
[\c
.BI \-b \ bits\c
]
[\c
.BI \-f \ file\c
]
[\c
.BI \-N \ new_passphrase\c
]
[\c
.BI \-C \ comment\c
]

.B "ssh-keygen \-p
[\c
.BI \-P \ old_passphrase\c
]
[\c
.BI \-N \ new_passphrase\c
]

.B "ssh-keygen \-c
[\c
.BI \-P \ passphrase\c
]
[\c
.BI \-C \ comment\c
]

.B "ssh-keygen \-u
[\c
.BI \-f \ file\c
]
[\c
.BI \-P \ passphrase\c
]

.SH DESCRIPTION 
.LP
.B Ssh-keygen
generates and manages authentication keys for 
.BR ssh (1).
Normally each user wishing to use
.B ssh
with RSA authentication runs this once to create the authentication
key in
.IR \&$HOME/\s+2.\s0ssh/identity ".
Additionally, the system administrator may use this to generate host keys.
.LP
Normally this program generates the key and asks for a file in which
to store the private key.  The public key is stored in a file with the
same name but ".pub" appended.  The program also asks for a
passphrase.  The passphrase may be empty to indicate no passphrase
(host keys must have empty passphrase), or it may be a string of
arbitrary length.  Good passphrases are 10-30 characters long and are
not simple sentences or otherwise easily guessable (English
prose has only 1-2 bits of entropy per word, and provides very bad
passphrases).  The passphrase can be changed later by using the
.B \-p
option.
.LP
There is no way to recover a lost passphrase.  If the passphrase is
lost or forgotten, you will have to generate a new key and copy the
corresponding public key to other machines.
.LP
USING GOOD, UNGUESSABLE PASSPHRASES IS STRONGLY RECOMMENDED.  EMPTY
PASSPHRASES SHOULD NOT BE USED UNLESS YOU UNDERSTAND WHAT YOU ARE DOING.
.LP
There is also a comment field in the key file that is only for
convenience to the user to help identify the key.  The comment can
tell what the key is for, or whatever is useful.  The comment is
initialized to user@host when the key is created, but can be changed
using the
.B \-c
option.
.LP
The cipher to be used when encrypting keys with a passphrase is
defined in ssh.h. Using the
.B \-u
option, keys encrypted in any supported cipher can be updated to
use this default cipher.

.SH OPTIONS
.TP 0.6i
.BI \-b \ bits
Specifies the number of bits in the key to create.  Minimum is 512
bits.  Generally 1024 bits is considered sufficient, and key sizes
above that no longer improve security but make things slower.  The
default is 1024 bits.
.TP
.B \-c
Requests changing the comment in the private and public key files.
The program will prompt for the file containing the private keys, for
passphrase if the key has one, and for the new comment.
.TP
.B \-f
Specifies the file name in which to load/store the key.
.TP
.B \-p
Requests changing the passphrase of a private key file instead of
creating a new private key.  The program will prompt for the file
containing the private key, for the old passphrase, and twice for the
new passphrase.
.TP
.B \-u
Requests that the key's cipher is changed to the current default
cipher (determined at compile-time - currently 3DES).
.TP
.B \-C
Provides the new comment.
.TP
.B \-N
Provides the new passphrase.
.TP
.B \-P
Provides the (old) passphrase.

.SH FILES
.TP 0.6i
.I \&$HOME/\s+2.\s0ssh/random_seed
Used for seeding the random number generator.  This file should not be
readable by anyone but the user.  This file is created the first time
the program is run, and is updated every time.
.TP
.I \&$HOME/\s+2.\s0ssh/identity
Contains the RSA authentication identity of the user.  This file
should not be readable by anyone but the user.  It is possible to
specify a passphrase when generating the key; that passphrase will be
used to encrypt the private part of this file using 3DES.  This file
is not automatically accessed by
.BR ssh-keygen ",
but it is offered as the default file for the private key.
.TP
.I \&$HOME/\s+2.\s0ssh/identity.pub
Contains the public key for authentication.  The contents of this file
should be added to \f4$HOME/\s+2.\s0ssh/authorized_keys\f1 on all machines
where you wish to log in using RSA authentication.  There is no
need to keep the contents of this file secret.

.SH AUTHOR
.LP
Tatu Ylonen <ylo@ssh.fi>

.SH SEE ALSO
.LP
.BR ssh (1),
.BR sshd (8),
.BR ssh-agent (1),
.BR ssh-add (1)
