# $Id: Makefile,v 1.3 1996-10-12 20:14:24 ghudson Exp $

SHELL=/bin/sh
ATHBINDIR=/usr/athena/bin

all:

check:

install:
	-mkdir -p ${DESTDIR}${ATHBINDIR}
	rm -f ${DESTDIR}${ATHBINDIR}/perl
	ln -s /usr/sbin/perl ${DESTDIR}${ATHBINDIR}/perl

clean:

distclean:
