.\" 
.\" $Id: pfrom.man,v 1.1.1.1 1996-09-06 00:47:09 ghudson Exp $
.\" $Source: /afs/dev.mit.edu/source/repository/third/cns/src/email/pfrom/pfrom.man,v $
.\" $Author: ghudson $
.\"
.TH PFROM 1 "March 10, 1991"
.UC 4
.SH NAME
pfrom \- who is my mail from?
.SH SYNOPSIS
.B pfrom
[
.B \-s
sender
] [
.B \-h 
host
] [
.B \-v
] [
.B \-d
]
.SH DESCRIPTION
The 
.I pfrom 
program prints out the mail header lines in your incoming mail
to show you who your mail is from.  It does this without
retrieving the mail from the post office.
If the 
.I \-s 
option is given, then only headers for mail sent by
.I sender
are printed.
If the 
.I \-h
option is given, then 
.I host
is consulted instead of your default post office.  The
.I \-v
option puts
.I pfrom
into verbose mode, and the 
.I \-d
option puts 
.I pfrom
into debug mode.
.SH "AUTHOR"
Theodore Ts'o
.SH "SEE ALSO"
\fIPost Office Protocol (revised)\fR (aka RFC\-819 with revisions)

