#!/bin/sh
if [ -z "$DEBATHENA_SENDMAIL_AUTH" ]; then
    if klist -s 2&>/dev/null; then
	DEBATHENA_SENDMAIL_AUTH=yes
    fi
fi
if [ "$DEBATHENA_SENDMAIL_AUTH" = "yes" ]; then
    kuser=$(klist 2>/dev/null | sed -n 's/^Default principal: \(.*\)@ATHENA\.MIT\.EDU/\1/ p')
    if [ -z "$kuser" ]; then
	echo "Could not find valid ATHENA.MIT.EDU Kerberos tickets." >&2
	exit 1
    fi
    exec msmtp --host=outgoing.mit.edu --port=587 --auth=gssapi --user="$kuser" --auto-from=on --maildomain=mit.edu "$@"
else
    exec msmtp --host=outgoing.mit.edu --port=25 --auth=off --auto-from=on --maildomain=mit.edu "$@"
fi
