.TH NEWALIASES 1 "11 March 2010" "debathena-msmtp-mta" "Athena Electronic Mail"
.SH NAME
newaliases \- Placeholder newaliases script
.SH SYNOPSIS
.nf
.B newaliases
.sp
.SH DESCRIPTION
.BR newaliases
is a placeholder, and is provided only because debathena-msmtp-mta
provides mail-transport-agent.  It doesn't really do anything, though
it will warn you if you're bitbucketing root's mail.

.SH SEE ALSO

msmtp(1)

.SH AUTHOR
SIPB Debathena Project (http://debathena.mit.edu)

