.TH SENDMAIL 8 "11 March 2010" "debathena-msmtp-mta" "Athena Electronic Mail"
.SH NAME
sendmail \- A script which invokes msmtp in order to send mail
.SH SYNOPSIS
.nf
.B sendmail [\fIflags\fP] [\fIaddress ...\fP]
.sp
.SH DESCRIPTION
.BR sendmail
sends a message to one or more recipients.  Flags and addresses are
passed to msmtp, which is invoked with the requisite options.  The
message is sent authenticated, and will fail if tickets are not
available.  Fallback to unauthenticated SMTP can be permitted by setting
the variable \fIDEBATHENA_SENDMAIL_AUTH\fP to "fallback".  If
authentication is forced, but no valid Kerberos tickets can be found to
authenticate the user, the script will exit with status 1.  See mstmp(1)
for possible values for \fIflags\fP.

.SH BUGS

If you don't supply a \fIFrom:\fP line in the body of your e-mail,
msmtp will construct one.  If you have tickets, it will construct it
from the principal, with any instances removed, and append
\fI@MIT.EDU\fP.  If you currently have tickets from a keytab
(e.g. host/some-hostname.mit.edu@ATHENA.MIT.EDU), that will result in
your mail having a \fIFrom:\fP address of \fIhost@mit.edu\fP.  Don't
do that.

Note that even if you specify a \fIFrom:\fP line, the
\fIReturn-Path\fP will be set to the msmtp-constructed address, and
thus you might miss bounces or other errors.  While you can specify
\fIErrors-To:\fP, and most MTAs will honor it, it's discouraged (per
RFC 2076).  You can force a Return-Path or From by setting the
environment variable \fIDEBATHENA_SENDMAIL_FROM\fP.  The contents of the
variable are passed verbatim.

Really, this is not an MTA.  In the time it took you to read this
section, you could have installed postfix or exim.  Just sayin'.

.SH SEE ALSO

msmtp(1)

.SH AUTHOR
SIPB Debathena Project (http://debathena.mit.edu)

