.TH OLC 1 "7 June 2010" "debathena-olc" "On-Line Consulting"
.SH NAME
olc \- A placeholder script for the old OLC client
.SH SYNOPSIS
.nf
.B olc
.sp
.SH DESCRIPTION
.BR olc
is a placeholder script.  It exists merely to tell people that it no
longer exists.

.SH SEE ALSO

Proceedings of the 17th Annual ACM SIGUCCS Conference 

.SH AUTHOR
Jonathan Reed <jdreed@mit.edu>, Debathena Project

