.\" $Id: credentials.5,v 1.2 1999-04-13 21:21:13 ghudson Exp $
.\"
.\" Copyright 1998, 1999 by the Massachusetts Institute of Technology.
.\"
.\" Permission to use, copy, modify, and distribute this
.\" software and its documentation for any purpose and without
.\" fee is hereby granted, provided that the above copyright
.\" notice appear in all copies and that both that copyright
.\" notice and this permission notice appear in supporting
.\" documentation, and that the name of M.I.T. not be used in
.\" advertising or publicity pertaining to distribution of the
.\" software without specific, written prior permission.
.\" M.I.T. makes no representations about the suitability of
.\" this software for any purpose.  It is provided "as is"
.\" without express or implied warranty.
.TH CREDENTIALS 5 "13 April 1999"
.SH NAME
credentials \- knfs credentials input file format
.SH SYNOPSIS
.B /var/athena/credentials
.SH DESCRIPTION
The
.B credentials
file is read by
.IR mkcred (1)
to generate db files needed by the Kerberized NFS mountd.
.PP
The file consists of an arbitrary number of lines of the format:
.RS 8
.B username:uid:primary gid:gid:gid:...
.RE
The first three fields are required. (The primary gid will normally be
101 (mit) for Athena users.) After the three required fields there can
be any number of supplementary gids (including none), although
.I mkcred
may ignore later gids if the size of the list exceeds the OS-defined
limit.
.PP
The colon after the last gid on a line may be omitted.
.SH "SEE ALSO"
mkcred(1)
.SH AUTHOR
MIT Information Systems
.br
Copyright 1998, 1999 by the Massachusetts Institute of Technology.
