#!/bin/sh

dist:
	cp "$$CONFIG_SITE" config.site.athena

prepare:
	LDFLAGS="-L/usr/athena/lib -Wl,-R/usr/athena/lib -Wl,-R/usr/athena/lib/mozilla" CONFIG_SITE=`pwd`/config.site.athena ./configure --disable-perl

clean:
	${MAKE} clean

all:
	${MAKE} all

check:

install:
	${MAKE} install DESTDIR="$$SRVD"
	cd "$$SRVD/usr/athena/bin" && mv gaim gaim.real
	install -c -m 755 athena-gaim "$$SRVD/usr/athena/bin/gaim"
