=head1 NAME

jstat - display Jwgc status

=head1 SYNOPSIS

jstat [ -h ] [ -d <flags> ]

=head1 DESCRIPTION

I<Jstat> is used to display the current status of I<jwgc>'s connection to
the Jabber server.  It lists out the services available from the Jabber
server you are connected to, some information about your connection
to the Jabber server, and some various statistics.

I<Jstat> understands the following options:

-h             Displays usage information.

-d <flags>     Debugging output.  Run without <flags> for usage.     

=head1 AUTHOR

Daniel Henninger <jadestorm@users.sourceforge.net>

=head1 COPYRIGHT

Copyright (c) 2002 Daniel Henninger. All right reserved.
This program is free software; you can redistribute it
and/or modify it under the terms explained in the B<LICENSE>
file that comes with the I<jwgc> distribution.

=head1 SEE ALSO

jwgc(1), jwrite(1), jctl(1), jlocate(1)
