#!/bin/sh

# Sets the Athena root password based on a hashed value stored in AFS.

pfile=/afs/athena.mit.edu/system/config/passwd/athena10/rootpw
if [ -r $pfile ]; then
    pw=$(cat $pfile)
    if [ -n "$pw" ]; then
	usermod -p "$pw" root
    fi
fi
