/*
 * This file was generated by orbit-idl - DO NOT EDIT!
 */

#include <string.h>
#include "eazel-inventory-service-interface.h"

#if ( (TC_IMPL_TC_Trilobite_Eazel_InventoryUploadCallback_0 == 'e') \
&& (TC_IMPL_TC_Trilobite_Eazel_InventoryUploadCallback_1 == 'a') \
&& (TC_IMPL_TC_Trilobite_Eazel_InventoryUploadCallback_2 == 'z') \
&& (TC_IMPL_TC_Trilobite_Eazel_InventoryUploadCallback_3 == 'e') \
&& (TC_IMPL_TC_Trilobite_Eazel_InventoryUploadCallback_4 == 'l') \
&& (TC_IMPL_TC_Trilobite_Eazel_InventoryUploadCallback_5 == '_') \
&& (TC_IMPL_TC_Trilobite_Eazel_InventoryUploadCallback_6 == 'i') \
&& (TC_IMPL_TC_Trilobite_Eazel_InventoryUploadCallback_7 == 'n') \
&& (TC_IMPL_TC_Trilobite_Eazel_InventoryUploadCallback_8 == 'v') \
&& (TC_IMPL_TC_Trilobite_Eazel_InventoryUploadCallback_9 == 'e') \
&& (TC_IMPL_TC_Trilobite_Eazel_InventoryUploadCallback_10 == 'n') \
&& (TC_IMPL_TC_Trilobite_Eazel_InventoryUploadCallback_11 == 't') \
&& (TC_IMPL_TC_Trilobite_Eazel_InventoryUploadCallback_12 == 'o') \
&& (TC_IMPL_TC_Trilobite_Eazel_InventoryUploadCallback_13 == 'r') \
&& (TC_IMPL_TC_Trilobite_Eazel_InventoryUploadCallback_14 == 'y') \
&& (TC_IMPL_TC_Trilobite_Eazel_InventoryUploadCallback_15 == '_') \
&& (TC_IMPL_TC_Trilobite_Eazel_InventoryUploadCallback_16 == 's') \
&& (TC_IMPL_TC_Trilobite_Eazel_InventoryUploadCallback_17 == 'e') \
&& (TC_IMPL_TC_Trilobite_Eazel_InventoryUploadCallback_18 == 'r') \
&& (TC_IMPL_TC_Trilobite_Eazel_InventoryUploadCallback_19 == 'v') \
&& (TC_IMPL_TC_Trilobite_Eazel_InventoryUploadCallback_20 == 'i') \
&& (TC_IMPL_TC_Trilobite_Eazel_InventoryUploadCallback_21 == 'c') \
&& (TC_IMPL_TC_Trilobite_Eazel_InventoryUploadCallback_22 == 'e') \
&& (TC_IMPL_TC_Trilobite_Eazel_InventoryUploadCallback_23 == '_') \
&& (TC_IMPL_TC_Trilobite_Eazel_InventoryUploadCallback_24 == 'i') \
&& (TC_IMPL_TC_Trilobite_Eazel_InventoryUploadCallback_25 == 'n') \
&& (TC_IMPL_TC_Trilobite_Eazel_InventoryUploadCallback_26 == 't') \
&& (TC_IMPL_TC_Trilobite_Eazel_InventoryUploadCallback_27 == 'e') \
&& (TC_IMPL_TC_Trilobite_Eazel_InventoryUploadCallback_28 == 'r') \
&& (TC_IMPL_TC_Trilobite_Eazel_InventoryUploadCallback_29 == 'f') \
&& (TC_IMPL_TC_Trilobite_Eazel_InventoryUploadCallback_30 == 'a') \
&& (TC_IMPL_TC_Trilobite_Eazel_InventoryUploadCallback_31 == 'c') \
&& (TC_IMPL_TC_Trilobite_Eazel_InventoryUploadCallback_32 == 'e') \
) && !defined(TC_DEF_TC_Trilobite_Eazel_InventoryUploadCallback)
#define TC_DEF_TC_Trilobite_Eazel_InventoryUploadCallback 1
const struct CORBA_TypeCode_struct
   TC_Trilobite_Eazel_InventoryUploadCallback_struct = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_objref, "InventoryUploadCallback",
      "IDL:Trilobite/Eazel/InventoryUploadCallback:1.0",
   0, 0,
   NULL,
   NULL,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_Trilobite_Eazel_Inventory_0 == 'e') \
&& (TC_IMPL_TC_Trilobite_Eazel_Inventory_1 == 'a') \
&& (TC_IMPL_TC_Trilobite_Eazel_Inventory_2 == 'z') \
&& (TC_IMPL_TC_Trilobite_Eazel_Inventory_3 == 'e') \
&& (TC_IMPL_TC_Trilobite_Eazel_Inventory_4 == 'l') \
&& (TC_IMPL_TC_Trilobite_Eazel_Inventory_5 == '_') \
&& (TC_IMPL_TC_Trilobite_Eazel_Inventory_6 == 'i') \
&& (TC_IMPL_TC_Trilobite_Eazel_Inventory_7 == 'n') \
&& (TC_IMPL_TC_Trilobite_Eazel_Inventory_8 == 'v') \
&& (TC_IMPL_TC_Trilobite_Eazel_Inventory_9 == 'e') \
&& (TC_IMPL_TC_Trilobite_Eazel_Inventory_10 == 'n') \
&& (TC_IMPL_TC_Trilobite_Eazel_Inventory_11 == 't') \
&& (TC_IMPL_TC_Trilobite_Eazel_Inventory_12 == 'o') \
&& (TC_IMPL_TC_Trilobite_Eazel_Inventory_13 == 'r') \
&& (TC_IMPL_TC_Trilobite_Eazel_Inventory_14 == 'y') \
&& (TC_IMPL_TC_Trilobite_Eazel_Inventory_15 == '_') \
&& (TC_IMPL_TC_Trilobite_Eazel_Inventory_16 == 's') \
&& (TC_IMPL_TC_Trilobite_Eazel_Inventory_17 == 'e') \
&& (TC_IMPL_TC_Trilobite_Eazel_Inventory_18 == 'r') \
&& (TC_IMPL_TC_Trilobite_Eazel_Inventory_19 == 'v') \
&& (TC_IMPL_TC_Trilobite_Eazel_Inventory_20 == 'i') \
&& (TC_IMPL_TC_Trilobite_Eazel_Inventory_21 == 'c') \
&& (TC_IMPL_TC_Trilobite_Eazel_Inventory_22 == 'e') \
&& (TC_IMPL_TC_Trilobite_Eazel_Inventory_23 == '_') \
&& (TC_IMPL_TC_Trilobite_Eazel_Inventory_24 == 'i') \
&& (TC_IMPL_TC_Trilobite_Eazel_Inventory_25 == 'n') \
&& (TC_IMPL_TC_Trilobite_Eazel_Inventory_26 == 't') \
&& (TC_IMPL_TC_Trilobite_Eazel_Inventory_27 == 'e') \
&& (TC_IMPL_TC_Trilobite_Eazel_Inventory_28 == 'r') \
&& (TC_IMPL_TC_Trilobite_Eazel_Inventory_29 == 'f') \
&& (TC_IMPL_TC_Trilobite_Eazel_Inventory_30 == 'a') \
&& (TC_IMPL_TC_Trilobite_Eazel_Inventory_31 == 'c') \
&& (TC_IMPL_TC_Trilobite_Eazel_Inventory_32 == 'e') \
) && !defined(TC_DEF_TC_Trilobite_Eazel_Inventory)
#define TC_DEF_TC_Trilobite_Eazel_Inventory 1
const struct CORBA_TypeCode_struct TC_Trilobite_Eazel_Inventory_struct = {
   
      {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},

   CORBA_tk_objref, "Inventory", "IDL:Trilobite/Eazel/Inventory:1.0",
   0, 0,
   NULL,
   NULL,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
CORBA_unsigned_long Trilobite_Eazel_InventoryUploadCallback__classid = 0;
CORBA_unsigned_long Trilobite_Eazel_Inventory__classid = 0;
