.TH ELMER 8 "4 June 1996"
.ds ]W MIT Athena
.SH NAME
elmer \- set up user environment and run global Xsession
.SH SYNOPSIS
.nf
elmer
.fi
.SH DESCRIPTION
In order to fit the Athena login model into SGI's login model, the
Athena login process had to be broken into pieces. When not encumbered
with worrying about a vendor login system, xlogin could simply exec
Xsession, passing on all of the important pieces of the login
environment. This is not possible when maintaining SGI's
model. Therefore \fIelmer\fR exists to reproduce the appropriate
environment. It sits between \fIxdm\fR and Athena's global Xsession
file, and is only run by \fIxdm\fR. It performs the following tasks:
.TP
* It informs \fInanny\fR that the user is logging in, and acquires
assorted information needed to start the login.
.TP
* It acquires a new AFS PAG.
.TP
* It redirects the standard output and error to the
console window tty.
.TP
* It sets up the environment.
.TP
* It execs Xsession.
.TP
* It waits for Xsession to exit, then tells \fInanny\fR the user
is logging out, and exits.
.SH FILES
.PP
/etc/athena/login/Xsession   global Xsession script
.SH "SEE ALSO"
xdm(1), xlogin(8), nanny(8)
.SH AUTHOR
Craig Fields, MIT I/S DCNS
.br
Copyright (c) 1996 Massachusetts Institute of Technology
