# $Id: Makefile.athena,v 1.1 1997-02-25 21:05:08 ghudson Exp $

SHELL=/bin/sh

prepare:
	imake "-I$$XCONFIGDIR" -DUseInstalled "-DCONFIGDIR=$$XCONFIGDIR"
	${MAKE} Makefiles

clean:
	${MAKE} clean

all:
	${MAKE} includes depend all

check:

install:
	${MAKE} install DESTDIR="$$SRVD"
