# $Id: Makefile.athena,v 1.7 2004-10-28 16:17:28 ghudson Exp $

dist:

prepare:
	PATH=${sprobin}:${PATH} PERL=/usr/athena/bin/perl ./config shared --prefix=/usr/athena

clean:
	${MAKE} clean

all:
	${MAKE} PATH=${sprobin}:${PATH}

check:
	${MAKE} test

install:
	${MAKE} install INSTALL_PREFIX="$$SRVD"
