# $Id: Makefile.athena,v 1.8 2005-04-15 16:26:15 ghudson Exp $

dist:

prepare:
	PATH=${sprobin}:${PATH} PERL=/usr/athena/bin/perl ./config shared --prefix=/usr/athena

clean:
	${MAKE} clean

all:
	${MAKE} PATH=${sprobin}:${PATH}

check:
	${MAKE} test

install:
	${MAKE} install INSTALL_PREFIX="$$SRVD" PATH=${sprobin}:${PATH}
