.TH MH 1
.SH NAME
mh \- Message Handler
.SH DESCRIPTION
\fIMH\fR is the name of a powerful message handling system.
Rather then being a single comprehensive program,
\fIMH\fR consists of a collection of fairly simple 
single-purpose programs to send, receive, save, 
and retrieve messages.

As of release 8.3, Athena uses \fInmh\fR ("new MH"). For a general
overview of \fInmh\fR commands, see the \fInmh\fR man page.
.SH "SEE ALSO"
nmh(1)
