.TH SIS 1 "April 23, 1992"
.UC
.SH NAME
sis \- Student Information Services
.SH SYNOPSIS
.B sis

.SH DESCRIPTION
This program gives a student access to their grades, as well as 
other registration information contained in the Registrar's Database. There
is more help available from within the application.
