.TH XINFO 1 "December 17, 1990"
.UC 4
.SH NAME
xinfo \- display MIT map, give info about MIT campus
.SH SYNOPSIS
.B xinfo
[-inactive {timeout}]
.PP
.SH DESCRIPTION
.I Xinfo
displays a map of the MIT campus and a menu-bar below it containing
topic headings for information that may be of use to students or
visitors at MIT.  The user is presented with a list of sub-topics by
clicking on one of the topic headings.  These sub-topics can also lead
to further sub-topics.  Once the user has chosen an item of interest,
some text is displayed in a window below the menu-bar.  The location of
the selected item is also displayed on the map, if applicable.
.PP
.SH OPTIONS
.PD 0
.TP 25
.B \-inactive {timeout}
exit after
.I timeout
seconds of inactivity (no default).
.PD 1
.PP
Since xinfo was written with the Motif toolkit, it accepts most other
toolkit options.
.PP
.SH FILES
.PD 0
.TP 36
.B \/usr/lib/X11/bitmaps/mitmap
bitmap of MIT
.TP 36
.B \/usr/lib/X11/bitmaps/owl
bitmap of Athena owl
.PD 1
.PP
.SH "SEE ALSO"
X(1)    for discussion of X geometry, resources, and toolkit options
