#! /bin/sh
# Run x3270 from the current directory

# Bomb on any error
set -e
d=`pwd`/

# Say what you're doing
set -x

# Set up the fonts
mkfontdir .
xset +fp $d
xset fp rehash

# Run x3270
set +e
./x3270 "$@"

# Clean up
xset -fp $d
xset fp rehash
