# $Id: Makefile.athena,v 1.2 1996-11-20 15:45:17 ghudson Exp $

SHELL=/bin/sh

prepare:
	imake "-I$$XCONFIGDIR" -DUseInstalled "-DSRCDIR=$$SOURCE"
	${MAKE} Makefiles

clean:
	${MAKE} clean

all:
	${MAKE} includes depend all

check:

install:
	${MAKE} install install.man "DESTDIR=$$SRVD"
