# $Id: Makefile.athena,v 1.6 2000-03-29 19:54:47 ghudson Exp $

SHELL=/bin/sh

dist:

prepare:
	imake "-I$$XCONFIGDIR" -DUseInstalled "-DXCONFIGDIR=$$XCONFIGDIR"
	${MAKE} Makefiles

clean:
	${MAKE} clean

all:
	${MAKE} includes depend all

check:

install:
	mkdir -p $$SRVD/usr/athena/lib/X11/fonts/misc
	touch $$SRVD/usr/athena/lib/X11/fonts/misc/fonts.dir
	${MAKE} install install.man "DESTDIR=$$SRVD"
