# $Id: Makefile.athena,v 1.4 1999-11-07 22:27:36 tb Exp $

SHELL=/bin/sh

prepare:
	imake "-I$$XCONFIGDIR" -DUseInstalled "-DCONFIGDIR=$$XCONFIGDIR"
	${MAKE} Makefiles

clean:
	${MAKE} clean

all:
	${MAKE} includes depend all

check:

install:
	mkdir -p $$SRVD/usr/athena/lib/X11/fonts/misc
	touch $$SRVD/usr/athena/lib/X11/fonts/misc/fonts.dir
	${MAKE} install install.man "DESTDIR=$$SRVD"
