/*
 * This file was generated by orbit-idl - DO NOT EDIT!
 */

#include <string.h>
#include "Evolution-Wombat.h"

#if ( (TC_IMPL_TC_GNOME_Evolution_WombatClient_0 == 'E') \
&& (TC_IMPL_TC_GNOME_Evolution_WombatClient_1 == 'v') \
&& (TC_IMPL_TC_GNOME_Evolution_WombatClient_2 == 'o') \
&& (TC_IMPL_TC_GNOME_Evolution_WombatClient_3 == 'l') \
&& (TC_IMPL_TC_GNOME_Evolution_WombatClient_4 == 'u') \
&& (TC_IMPL_TC_GNOME_Evolution_WombatClient_5 == 't') \
&& (TC_IMPL_TC_GNOME_Evolution_WombatClient_6 == 'i') \
&& (TC_IMPL_TC_GNOME_Evolution_WombatClient_7 == 'o') \
&& (TC_IMPL_TC_GNOME_Evolution_WombatClient_8 == 'n') \
&& (TC_IMPL_TC_GNOME_Evolution_WombatClient_9 == '_') \
&& (TC_IMPL_TC_GNOME_Evolution_WombatClient_10 == 'W') \
&& (TC_IMPL_TC_GNOME_Evolution_WombatClient_11 == 'o') \
&& (TC_IMPL_TC_GNOME_Evolution_WombatClient_12 == 'm') \
&& (TC_IMPL_TC_GNOME_Evolution_WombatClient_13 == 'b') \
&& (TC_IMPL_TC_GNOME_Evolution_WombatClient_14 == 'a') \
&& (TC_IMPL_TC_GNOME_Evolution_WombatClient_15 == 't') \
) && !defined(TC_DEF_TC_GNOME_Evolution_WombatClient)
#define TC_DEF_TC_GNOME_Evolution_WombatClient 1
const struct CORBA_TypeCode_struct TC_GNOME_Evolution_WombatClient_struct = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_objref, "WombatClient", "IDL:GNOME/Evolution/WombatClient:1.0",
   0, 0,
   NULL,
   NULL,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_GNOME_Evolution_Config_0 == 'E') \
&& (TC_IMPL_TC_GNOME_Evolution_Config_1 == 'v') \
&& (TC_IMPL_TC_GNOME_Evolution_Config_2 == 'o') \
&& (TC_IMPL_TC_GNOME_Evolution_Config_3 == 'l') \
&& (TC_IMPL_TC_GNOME_Evolution_Config_4 == 'u') \
&& (TC_IMPL_TC_GNOME_Evolution_Config_5 == 't') \
&& (TC_IMPL_TC_GNOME_Evolution_Config_6 == 'i') \
&& (TC_IMPL_TC_GNOME_Evolution_Config_7 == 'o') \
&& (TC_IMPL_TC_GNOME_Evolution_Config_8 == 'n') \
&& (TC_IMPL_TC_GNOME_Evolution_Config_9 == '_') \
&& (TC_IMPL_TC_GNOME_Evolution_Config_10 == 'W') \
&& (TC_IMPL_TC_GNOME_Evolution_Config_11 == 'o') \
&& (TC_IMPL_TC_GNOME_Evolution_Config_12 == 'm') \
&& (TC_IMPL_TC_GNOME_Evolution_Config_13 == 'b') \
&& (TC_IMPL_TC_GNOME_Evolution_Config_14 == 'a') \
&& (TC_IMPL_TC_GNOME_Evolution_Config_15 == 't') \
) && !defined(TC_DEF_TC_GNOME_Evolution_Config)
#define TC_DEF_TC_GNOME_Evolution_Config 1
const struct CORBA_TypeCode_struct TC_GNOME_Evolution_Config_struct = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_objref, "Config", "IDL:GNOME/Evolution/Config:1.0",
   0, 0,
   NULL,
   NULL,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_GNOME_Evolution_WombatInterfaceCheck_0 == 'E') \
&& (TC_IMPL_TC_GNOME_Evolution_WombatInterfaceCheck_1 == 'v') \
&& (TC_IMPL_TC_GNOME_Evolution_WombatInterfaceCheck_2 == 'o') \
&& (TC_IMPL_TC_GNOME_Evolution_WombatInterfaceCheck_3 == 'l') \
&& (TC_IMPL_TC_GNOME_Evolution_WombatInterfaceCheck_4 == 'u') \
&& (TC_IMPL_TC_GNOME_Evolution_WombatInterfaceCheck_5 == 't') \
&& (TC_IMPL_TC_GNOME_Evolution_WombatInterfaceCheck_6 == 'i') \
&& (TC_IMPL_TC_GNOME_Evolution_WombatInterfaceCheck_7 == 'o') \
&& (TC_IMPL_TC_GNOME_Evolution_WombatInterfaceCheck_8 == 'n') \
&& (TC_IMPL_TC_GNOME_Evolution_WombatInterfaceCheck_9 == '_') \
&& (TC_IMPL_TC_GNOME_Evolution_WombatInterfaceCheck_10 == 'W') \
&& (TC_IMPL_TC_GNOME_Evolution_WombatInterfaceCheck_11 == 'o') \
&& (TC_IMPL_TC_GNOME_Evolution_WombatInterfaceCheck_12 == 'm') \
&& (TC_IMPL_TC_GNOME_Evolution_WombatInterfaceCheck_13 == 'b') \
&& (TC_IMPL_TC_GNOME_Evolution_WombatInterfaceCheck_14 == 'a') \
&& (TC_IMPL_TC_GNOME_Evolution_WombatInterfaceCheck_15 == 't') \
) && !defined(TC_DEF_TC_GNOME_Evolution_WombatInterfaceCheck)
#define TC_DEF_TC_GNOME_Evolution_WombatInterfaceCheck 1
const struct CORBA_TypeCode_struct
   TC_GNOME_Evolution_WombatInterfaceCheck_struct = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_objref, "WombatInterfaceCheck",
      "IDL:GNOME/Evolution/WombatInterfaceCheck:1.0",
   0, 0,
   NULL,
   NULL,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
CORBA_unsigned_long GNOME_Evolution_WombatClient__classid = 0;
CORBA_unsigned_long GNOME_Evolution_Config__classid = 0;
CORBA_unsigned_long GNOME_Evolution_WombatInterfaceCheck__classid = 0;
