.TH NEWSYSLOG 8 "November 30, 1995" "MIT Athena"
.SH NAME
newsyslog \- maintain system log files to manageable sizes
.SH SYNOPSIS
.B /etc/athena/newsyslog
.RB [ \-vnr ]
[\fB\-f \fIconfig-file\fR] [\fB\-t \fIsleep\fR]
.SH DESCRIPTION
.I Newsyslog
is a program that should be scheduled to run periodically by
.IR crontab .
When it is executed, it archives and processes log files if necessary.
Processes writing to the log file (usually
.IR syslogd )
are signalled so they can start using the new log file.
.PP
There are two possible conditions for
.I newsyslog
to turn over the log file: the file may have grown bigger than a
preset size in kilobytes, or a preset number of hours may have elapsed
since the last log archive.  The granularity of
.I newsyslog
is dependent on how often it is scheduled to run in crontab.  Since
the program is quite fast, it may be scheduled to run every hour
without any ill effects.
.PP
If a log file is determined to require archiving,
.I newsyslog
usually rearranges the files so that ``logfile'' is empty,
``logfile.0'' has the last period's logs in it, ``logfile.1'' has the
next to last period's logs in it, and so on, up to a user-specified
number of archived logs.
If the log files are to be archived indefinitely, it is sometimes more
convenient to label the filenames with the date when the file was
turned over.  In this case, the files will be named
``logfile.YYYYMMDD'' instead of ``logfile.N'', but the number of
log files stored can still be specified by the user.
.PP
When starting up, 
.I newsyslog
reads in a configuration file to determine which logs should be looked
at.  By default, this configuration file is 
.IR /etc/athena/newsyslog.conf .
The syntax of this file is described in a separate manpage.
.PP
.SH OPTIONS
The following options can be used with newsyslog:
.TP
.B \-f \fIconfig-file
instructs newsyslog to use 
.I config-file
instead of /etc/athena/newsyslog.conf for its configuration file.
.TP
.B \-t \fIsleep
tells newsyslog to sleep for the specified number of seconds after
sending a signal to a process, in order to give it time to clean up.
(The default is 1.)
.TP
.B \-v
places 
.I newsyslog
in verbose mode.  In this mode it will print out each log and its
reasons for either trimming that log or skipping it.
.TP
.B \-n
causes
.I newsyslog 
not to trim the logs, but to print out what it would do if this option
were not specified.
.TP
.B \-r
removes the restriction that
.I newsyslog 
must be running as root.  Of course, 
.I newsyslog
will not be able to send a signal to the processes controlling
the log files (such as
.IR syslogd )
if they were started by a different user, so this option is probably
most useful in debugging.
.SH FILES
/etc/athena/newsyslog.conf
.SH BUGS
Doesn't yet automatically read the logs to find security breaches.
.SH AUTHORS
Newsyslog was written by Theodore Ts'o, MIT Project Athena.
.br
bert Dvornik, MIT IS/DCNS-Dev, added some new features.
.br
Copyright 1987,1995 Massachusetts Institute of Technology
.SH "SEE ALSO"
newsyslog.conf(5), syslogd(8), compress(1)
