#
# Copyright 2002 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
#ident	"$Id: Makefile,v 1.1.1.2 2003-07-08 16:47:17 rbasch Exp $"
#

CORE_DEPTH = ../../../..
include ../Makefile.com

DATAFILES +=

all:: $(FILES)
publish:: all pkg

include ../Makefile.targ
