#
# Copyright 2002 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
#ident	"$Id: Makefile,v 1.1.1.1.2.3 2004-03-06 19:30:43 ghudson Exp $"
#

CORE_DEPTH = ../../../..
include ../Makefile.com

DATAFILES +=

all:: $(FILES)
publish:: all pkg

include ../Makefile.targ
