#undef SOUP_MAJOR_VERSION
#undef SOUP_MINOR_VERSION
#undef SOUP_MICRO_VERSION
#undef SOUP_INTERFACE_AGE
#undef SOUP_BINARY_AGE

#undef SOUP_GLIB2

#undef PACKAGE_SOURCE_DIR

#undef HAVE_OPENSSL
#undef HAVE_NSS
#undef SSL_PROXY_NAME

#undef HAVE_GETHOSTBYNAME_R_GLIBC
#undef HAVE_GETHOSTBYNAME_R_SOLARIS
#undef HAVE_GETHOSTBYNAME_R_HPUX
#undef HAVE_GETHOSTBYNAME_R_GLIB_MUTEX

#undef ALIGNOF_GBOOLEAN
#undef ALIGNOF_GCHAR
#undef ALIGNOF_GUCHAR
#undef ALIGNOF_GINT
#undef ALIGNOF_GUINT
#undef ALIGNOF_GSHORT
#undef ALIGNOF_GUSHORT
#undef ALIGNOF_GLONG
#undef ALIGNOF_GULONG
#undef ALIGNOF_GINT8
#undef ALIGNOF_GUINT8
#undef ALIGNOF_GINT16
#undef ALIGNOF_GUINT16
#undef ALIGNOF_GINT32
#undef ALIGNOF_GUINT32
#undef ALIGNOF_GFLOAT
#undef ALIGNOF_GDOUBLE
#undef ALIGNOF_GPOINTER
#undef ALIGNOF_GSTRUCT

