.\"
.\" $Id: sq.1,v 1.1.1.2 2007-02-01 19:49:55 ghudson Exp $
.\"
.\" Copyright 1992, 1993, 1999, 2001, Geoff Kuenning, Claremont, CA
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\"
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. All modifications to the source code must be clearly marked as
.\"    such.  Binary redistributions based on modified source code
.\"    must be clearly marked as modified versions in the documentation
.\"    and/or other materials provided with the distribution.
.\" 4. The code that causes the 'ispell -v' command to display a prominent
.\"    link to the official ispell Web site may not be removed.
.\" 5. The name of Geoff Kuenning may not be used to endorse or promote
.\"    products derived from this software without specific prior
.\"    written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY GEOFF KUENNING AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL GEOFF KUENNING OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\" $Log: not supported by cvs2svn $
.\" Revision 1.12  2005/04/14 14:38:23  geoff
.\" Update license.
.\"
.\" Revision 1.11  2001/07/25 21:51:46  geoff
.\" Minor license update.
.\"
.\" Revision 1.10  2001/07/23 20:24:04  geoff
.\" Update the copyright and the license.
.\"
.\" Revision 1.9  2000/07/19 23:30:12  geoff
.\" Add a bugs section, and mention gzip instead of compress
.\"
.\" Revision 1.8  1999/01/07 01:57:39  geoff
.\" Update the copyright.
.\"
.\" Revision 1.7  1995/11/08  05:09:25  geoff
.\" Put the synopsis on one line so some versions of "makewhatis" don't
.\" break.
.\"
.\" Revision 1.6  1994/01/25  07:12:07  geoff
.\" Get rid of all old RCS log lines in preparation for the 3.1 release.
.\"
.\"
.TH SQ 1 LOCAL
.SH NAME
sq, unsq \- squeeze or unsqueeze a sorted word list
.SH SYNOPSIS
.B sq
< infile > outfile
.PP
.B unsq
< infile > outfile
.SH DESCRIPTION
.I sq
compresses a sorted list of words (a dictionary). 
For example:
.RS
sort -u /usr/dict/words | sq | gzip -9 > words.sq.Z
.RE
will compress dict by about a factor of 5.
.PP
.I unsq
uncompress the output of
.I sq.
For example:
.RS
gunzip < words.sq.gz | unsq | sort -f -o words
.RE
will uncompress a dictionary compressed with
.I sq.
.P
The squeezing is achieved by eliminating common prefixes, and replacing
them with a single character which encodes the number of characters
shared with the preceding word.
The prefix size is encoded as a single printable character:
0-9 represent 0-9, A-Z represent 10-35, and a-z represent 36-61.
.SH BUGS
.I sq
and
.I unsq
can only handle words of up to 256 characters.
The input must be sorted, and duplicates must be suppressed.
.SH AUTHOR
Mike Wexler
.SH SEE ALSO
compress(1), sort(1).
