<gnome-cd>
	<display>
		<image location="top-left">top-left.png</image>
		<image location="top-right">top-right.png</image>
		<image location="bottom-left">bottom-left.png</image>
		<image location="bottom-right">bottom-right.png</image>

		<image location="left">middle-left.png</image>
		<image location="right">middle-right.png</image>
		<image location="top">top.png</image>
		<image location="bottom">bottom.png</image>

		<image location="middle">middle.png</image>
	</display>
</gnome-cd>
