/*
 * This file was generated by orbit-idl - DO NOT EDIT!
 */

#include <string.h>
#include "gnome-vfs-slave.h"

#if ( (TC_IMPL_TC_CORBA_sequence_CORBA_octet_0 == 'g') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_octet_1 == 'n') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_octet_2 == 'o') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_octet_3 == 'm') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_octet_4 == 'e') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_octet_5 == '_') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_octet_6 == 'v') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_octet_7 == 'f') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_octet_8 == 's') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_octet_9 == '_') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_octet_10 == 's') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_octet_11 == 'l') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_octet_12 == 'a') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_octet_13 == 'v') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_octet_14 == 'e') \
) && !defined(TC_DEF_TC_CORBA_sequence_CORBA_octet)
#define TC_DEF_TC_CORBA_sequence_CORBA_octet 1
static const CORBA_TypeCode anon_subtypes_array2[] =
   { (CORBA_TypeCode) & TC_CORBA_octet_struct };
const struct CORBA_TypeCode_struct TC_CORBA_sequence_CORBA_octet_struct = {
   
      {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},

   CORBA_tk_sequence, NULL, NULL,
   0, 1,
   NULL,
   (CORBA_TypeCode *) anon_subtypes_array2,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_CORBA_sequence_CORBA_octet_0 == 'g') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_octet_1 == 'n') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_octet_2 == 'o') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_octet_3 == 'm') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_octet_4 == 'e') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_octet_5 == '_') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_octet_6 == 'v') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_octet_7 == 'f') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_octet_8 == 's') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_octet_9 == '_') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_octet_10 == 's') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_octet_11 == 'l') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_octet_12 == 'a') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_octet_13 == 'v') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_octet_14 == 'e') \
) && !defined(TC_DEF_TC_CORBA_sequence_CORBA_octet)
#define TC_DEF_TC_CORBA_sequence_CORBA_octet 1
static const CORBA_TypeCode anon_subtypes_array11[] =
   { (CORBA_TypeCode) & TC_CORBA_octet_struct };
const struct CORBA_TypeCode_struct TC_CORBA_sequence_CORBA_octet_struct = {
   
      {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},

   CORBA_tk_sequence, NULL, NULL,
   0, 1,
   NULL,
   (CORBA_TypeCode *) anon_subtypes_array11,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_GNOME_VFS_Buffer_0 == 'g') \
&& (TC_IMPL_TC_GNOME_VFS_Buffer_1 == 'n') \
&& (TC_IMPL_TC_GNOME_VFS_Buffer_2 == 'o') \
&& (TC_IMPL_TC_GNOME_VFS_Buffer_3 == 'm') \
&& (TC_IMPL_TC_GNOME_VFS_Buffer_4 == 'e') \
&& (TC_IMPL_TC_GNOME_VFS_Buffer_5 == '_') \
&& (TC_IMPL_TC_GNOME_VFS_Buffer_6 == 'v') \
&& (TC_IMPL_TC_GNOME_VFS_Buffer_7 == 'f') \
&& (TC_IMPL_TC_GNOME_VFS_Buffer_8 == 's') \
&& (TC_IMPL_TC_GNOME_VFS_Buffer_9 == '_') \
&& (TC_IMPL_TC_GNOME_VFS_Buffer_10 == 's') \
&& (TC_IMPL_TC_GNOME_VFS_Buffer_11 == 'l') \
&& (TC_IMPL_TC_GNOME_VFS_Buffer_12 == 'a') \
&& (TC_IMPL_TC_GNOME_VFS_Buffer_13 == 'v') \
&& (TC_IMPL_TC_GNOME_VFS_Buffer_14 == 'e') \
) && !defined(TC_DEF_TC_GNOME_VFS_Buffer)
#define TC_DEF_TC_GNOME_VFS_Buffer 1
static const CORBA_TypeCode anon_subtypes_array15[] =
   { (CORBA_TypeCode) & TC_CORBA_sequence_CORBA_octet_struct };
const struct CORBA_TypeCode_struct TC_GNOME_VFS_Buffer_struct = {
   
      {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},

   CORBA_tk_alias, "Buffer", "IDL:GNOME/VFS/Buffer:1.0",
   0, 1,
   NULL,
   (CORBA_TypeCode *) anon_subtypes_array15,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_GNOME_VFS_Result_0 == 'g') \
&& (TC_IMPL_TC_GNOME_VFS_Result_1 == 'n') \
&& (TC_IMPL_TC_GNOME_VFS_Result_2 == 'o') \
&& (TC_IMPL_TC_GNOME_VFS_Result_3 == 'm') \
&& (TC_IMPL_TC_GNOME_VFS_Result_4 == 'e') \
&& (TC_IMPL_TC_GNOME_VFS_Result_5 == '_') \
&& (TC_IMPL_TC_GNOME_VFS_Result_6 == 'v') \
&& (TC_IMPL_TC_GNOME_VFS_Result_7 == 'f') \
&& (TC_IMPL_TC_GNOME_VFS_Result_8 == 's') \
&& (TC_IMPL_TC_GNOME_VFS_Result_9 == '_') \
&& (TC_IMPL_TC_GNOME_VFS_Result_10 == 's') \
&& (TC_IMPL_TC_GNOME_VFS_Result_11 == 'l') \
&& (TC_IMPL_TC_GNOME_VFS_Result_12 == 'a') \
&& (TC_IMPL_TC_GNOME_VFS_Result_13 == 'v') \
&& (TC_IMPL_TC_GNOME_VFS_Result_14 == 'e') \
) && !defined(TC_DEF_TC_GNOME_VFS_Result)
#define TC_DEF_TC_GNOME_VFS_Result 1
static const CORBA_TypeCode anon_subtypes_array24[] =
   { (CORBA_TypeCode) & TC_CORBA_unsigned_short_struct };
const struct CORBA_TypeCode_struct TC_GNOME_VFS_Result_struct = {
   
      {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},

   CORBA_tk_alias, "Result", "IDL:GNOME/VFS/Result:1.0",
   0, 1,
   NULL,
   (CORBA_TypeCode *) anon_subtypes_array24,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_GNOME_VFS_OpenMode_0 == 'g') \
&& (TC_IMPL_TC_GNOME_VFS_OpenMode_1 == 'n') \
&& (TC_IMPL_TC_GNOME_VFS_OpenMode_2 == 'o') \
&& (TC_IMPL_TC_GNOME_VFS_OpenMode_3 == 'm') \
&& (TC_IMPL_TC_GNOME_VFS_OpenMode_4 == 'e') \
&& (TC_IMPL_TC_GNOME_VFS_OpenMode_5 == '_') \
&& (TC_IMPL_TC_GNOME_VFS_OpenMode_6 == 'v') \
&& (TC_IMPL_TC_GNOME_VFS_OpenMode_7 == 'f') \
&& (TC_IMPL_TC_GNOME_VFS_OpenMode_8 == 's') \
&& (TC_IMPL_TC_GNOME_VFS_OpenMode_9 == '_') \
&& (TC_IMPL_TC_GNOME_VFS_OpenMode_10 == 's') \
&& (TC_IMPL_TC_GNOME_VFS_OpenMode_11 == 'l') \
&& (TC_IMPL_TC_GNOME_VFS_OpenMode_12 == 'a') \
&& (TC_IMPL_TC_GNOME_VFS_OpenMode_13 == 'v') \
&& (TC_IMPL_TC_GNOME_VFS_OpenMode_14 == 'e') \
) && !defined(TC_DEF_TC_GNOME_VFS_OpenMode)
#define TC_DEF_TC_GNOME_VFS_OpenMode 1
static const CORBA_TypeCode anon_subtypes_array33[] =
   { (CORBA_TypeCode) & TC_CORBA_unsigned_long_struct };
const struct CORBA_TypeCode_struct TC_GNOME_VFS_OpenMode_struct = {
   
      {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},

   CORBA_tk_alias, "OpenMode", "IDL:GNOME/VFS/OpenMode:1.0",
   0, 1,
   NULL,
   (CORBA_TypeCode *) anon_subtypes_array33,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_GNOME_VFS_Permission_0 == 'g') \
&& (TC_IMPL_TC_GNOME_VFS_Permission_1 == 'n') \
&& (TC_IMPL_TC_GNOME_VFS_Permission_2 == 'o') \
&& (TC_IMPL_TC_GNOME_VFS_Permission_3 == 'm') \
&& (TC_IMPL_TC_GNOME_VFS_Permission_4 == 'e') \
&& (TC_IMPL_TC_GNOME_VFS_Permission_5 == '_') \
&& (TC_IMPL_TC_GNOME_VFS_Permission_6 == 'v') \
&& (TC_IMPL_TC_GNOME_VFS_Permission_7 == 'f') \
&& (TC_IMPL_TC_GNOME_VFS_Permission_8 == 's') \
&& (TC_IMPL_TC_GNOME_VFS_Permission_9 == '_') \
&& (TC_IMPL_TC_GNOME_VFS_Permission_10 == 's') \
&& (TC_IMPL_TC_GNOME_VFS_Permission_11 == 'l') \
&& (TC_IMPL_TC_GNOME_VFS_Permission_12 == 'a') \
&& (TC_IMPL_TC_GNOME_VFS_Permission_13 == 'v') \
&& (TC_IMPL_TC_GNOME_VFS_Permission_14 == 'e') \
) && !defined(TC_DEF_TC_GNOME_VFS_Permission)
#define TC_DEF_TC_GNOME_VFS_Permission 1
static const CORBA_TypeCode anon_subtypes_array42[] =
   { (CORBA_TypeCode) & TC_CORBA_unsigned_short_struct };
const struct CORBA_TypeCode_struct TC_GNOME_VFS_Permission_struct = {
   
      {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},

   CORBA_tk_alias, "Permission", "IDL:GNOME/VFS/Permission:1.0",
   0, 1,
   NULL,
   (CORBA_TypeCode *) anon_subtypes_array42,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_GNOME_VFS_Slave_FileInfo_0 == 'g') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_FileInfo_1 == 'n') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_FileInfo_2 == 'o') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_FileInfo_3 == 'm') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_FileInfo_4 == 'e') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_FileInfo_5 == '_') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_FileInfo_6 == 'v') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_FileInfo_7 == 'f') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_FileInfo_8 == 's') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_FileInfo_9 == '_') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_FileInfo_10 == 's') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_FileInfo_11 == 'l') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_FileInfo_12 == 'a') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_FileInfo_13 == 'v') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_FileInfo_14 == 'e') \
) && !defined(TC_DEF_TC_GNOME_VFS_Slave_FileInfo)
#define TC_DEF_TC_GNOME_VFS_Slave_FileInfo 1
static const char *anon_subnames_array45[] =
   { "data", "name", "symlink_name", "mime_type" };
static const CORBA_TypeCode anon_subtypes_array46[] =
   { (CORBA_TypeCode) & TC_GNOME_VFS_Buffer_struct,
      (CORBA_TypeCode) & TC_CORBA_string_struct,
      (CORBA_TypeCode) & TC_CORBA_string_struct,
      (CORBA_TypeCode) & TC_CORBA_string_struct };
const struct CORBA_TypeCode_struct TC_GNOME_VFS_Slave_FileInfo_struct = {
   
      {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},

   CORBA_tk_struct, "FileInfo", "IDL:GNOME/VFS/Slave/FileInfo:1.0",
   0, 4,
   (const char **) anon_subnames_array45,
   (CORBA_TypeCode *) anon_subtypes_array46,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_CORBA_sequence_GNOME_VFS_Slave_FileInfo_0 == 'g') \
&& (TC_IMPL_TC_CORBA_sequence_GNOME_VFS_Slave_FileInfo_1 == 'n') \
&& (TC_IMPL_TC_CORBA_sequence_GNOME_VFS_Slave_FileInfo_2 == 'o') \
&& (TC_IMPL_TC_CORBA_sequence_GNOME_VFS_Slave_FileInfo_3 == 'm') \
&& (TC_IMPL_TC_CORBA_sequence_GNOME_VFS_Slave_FileInfo_4 == 'e') \
&& (TC_IMPL_TC_CORBA_sequence_GNOME_VFS_Slave_FileInfo_5 == '_') \
&& (TC_IMPL_TC_CORBA_sequence_GNOME_VFS_Slave_FileInfo_6 == 'v') \
&& (TC_IMPL_TC_CORBA_sequence_GNOME_VFS_Slave_FileInfo_7 == 'f') \
&& (TC_IMPL_TC_CORBA_sequence_GNOME_VFS_Slave_FileInfo_8 == 's') \
&& (TC_IMPL_TC_CORBA_sequence_GNOME_VFS_Slave_FileInfo_9 == '_') \
&& (TC_IMPL_TC_CORBA_sequence_GNOME_VFS_Slave_FileInfo_10 == 's') \
&& (TC_IMPL_TC_CORBA_sequence_GNOME_VFS_Slave_FileInfo_11 == 'l') \
&& (TC_IMPL_TC_CORBA_sequence_GNOME_VFS_Slave_FileInfo_12 == 'a') \
&& (TC_IMPL_TC_CORBA_sequence_GNOME_VFS_Slave_FileInfo_13 == 'v') \
&& (TC_IMPL_TC_CORBA_sequence_GNOME_VFS_Slave_FileInfo_14 == 'e') \
) && !defined(TC_DEF_TC_CORBA_sequence_GNOME_VFS_Slave_FileInfo)
#define TC_DEF_TC_CORBA_sequence_GNOME_VFS_Slave_FileInfo 1
static const CORBA_TypeCode anon_subtypes_array50[] =
   { (CORBA_TypeCode) & TC_GNOME_VFS_Slave_FileInfo_struct };
const struct CORBA_TypeCode_struct
   TC_CORBA_sequence_GNOME_VFS_Slave_FileInfo_struct = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_sequence, NULL, NULL,
   0, 1,
   NULL,
   (CORBA_TypeCode *) anon_subtypes_array50,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_CORBA_sequence_GNOME_VFS_Slave_FileInfo_0 == 'g') \
&& (TC_IMPL_TC_CORBA_sequence_GNOME_VFS_Slave_FileInfo_1 == 'n') \
&& (TC_IMPL_TC_CORBA_sequence_GNOME_VFS_Slave_FileInfo_2 == 'o') \
&& (TC_IMPL_TC_CORBA_sequence_GNOME_VFS_Slave_FileInfo_3 == 'm') \
&& (TC_IMPL_TC_CORBA_sequence_GNOME_VFS_Slave_FileInfo_4 == 'e') \
&& (TC_IMPL_TC_CORBA_sequence_GNOME_VFS_Slave_FileInfo_5 == '_') \
&& (TC_IMPL_TC_CORBA_sequence_GNOME_VFS_Slave_FileInfo_6 == 'v') \
&& (TC_IMPL_TC_CORBA_sequence_GNOME_VFS_Slave_FileInfo_7 == 'f') \
&& (TC_IMPL_TC_CORBA_sequence_GNOME_VFS_Slave_FileInfo_8 == 's') \
&& (TC_IMPL_TC_CORBA_sequence_GNOME_VFS_Slave_FileInfo_9 == '_') \
&& (TC_IMPL_TC_CORBA_sequence_GNOME_VFS_Slave_FileInfo_10 == 's') \
&& (TC_IMPL_TC_CORBA_sequence_GNOME_VFS_Slave_FileInfo_11 == 'l') \
&& (TC_IMPL_TC_CORBA_sequence_GNOME_VFS_Slave_FileInfo_12 == 'a') \
&& (TC_IMPL_TC_CORBA_sequence_GNOME_VFS_Slave_FileInfo_13 == 'v') \
&& (TC_IMPL_TC_CORBA_sequence_GNOME_VFS_Slave_FileInfo_14 == 'e') \
) && !defined(TC_DEF_TC_CORBA_sequence_GNOME_VFS_Slave_FileInfo)
#define TC_DEF_TC_CORBA_sequence_GNOME_VFS_Slave_FileInfo 1
static const CORBA_TypeCode anon_subtypes_array59[] =
   { (CORBA_TypeCode) & TC_GNOME_VFS_Slave_FileInfo_struct };
const struct CORBA_TypeCode_struct
   TC_CORBA_sequence_GNOME_VFS_Slave_FileInfo_struct = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_sequence, NULL, NULL,
   0, 1,
   NULL,
   (CORBA_TypeCode *) anon_subtypes_array59,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_GNOME_VFS_Slave_FileInfoList_0 == 'g') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_FileInfoList_1 == 'n') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_FileInfoList_2 == 'o') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_FileInfoList_3 == 'm') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_FileInfoList_4 == 'e') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_FileInfoList_5 == '_') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_FileInfoList_6 == 'v') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_FileInfoList_7 == 'f') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_FileInfoList_8 == 's') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_FileInfoList_9 == '_') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_FileInfoList_10 == 's') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_FileInfoList_11 == 'l') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_FileInfoList_12 == 'a') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_FileInfoList_13 == 'v') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_FileInfoList_14 == 'e') \
) && !defined(TC_DEF_TC_GNOME_VFS_Slave_FileInfoList)
#define TC_DEF_TC_GNOME_VFS_Slave_FileInfoList 1
static const CORBA_TypeCode anon_subtypes_array63[] =
   { (CORBA_TypeCode) & TC_CORBA_sequence_GNOME_VFS_Slave_FileInfo_struct };
const struct CORBA_TypeCode_struct TC_GNOME_VFS_Slave_FileInfoList_struct = {
   
      {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},

   CORBA_tk_alias, "FileInfoList", "IDL:GNOME/VFS/Slave/FileInfoList:1.0",
   0, 1,
   NULL,
   (CORBA_TypeCode *) anon_subtypes_array63,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_GNOME_VFS_Slave_FileInfoOptions_0 == 'g') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_FileInfoOptions_1 == 'n') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_FileInfoOptions_2 == 'o') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_FileInfoOptions_3 == 'm') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_FileInfoOptions_4 == 'e') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_FileInfoOptions_5 == '_') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_FileInfoOptions_6 == 'v') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_FileInfoOptions_7 == 'f') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_FileInfoOptions_8 == 's') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_FileInfoOptions_9 == '_') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_FileInfoOptions_10 == 's') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_FileInfoOptions_11 == 'l') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_FileInfoOptions_12 == 'a') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_FileInfoOptions_13 == 'v') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_FileInfoOptions_14 == 'e') \
) && !defined(TC_DEF_TC_GNOME_VFS_Slave_FileInfoOptions)
#define TC_DEF_TC_GNOME_VFS_Slave_FileInfoOptions 1
static const CORBA_TypeCode anon_subtypes_array72[] =
   { (CORBA_TypeCode) & TC_CORBA_unsigned_long_struct };
const struct CORBA_TypeCode_struct TC_GNOME_VFS_Slave_FileInfoOptions_struct = {
   
      {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},

   CORBA_tk_alias, "FileInfoOptions",
      "IDL:GNOME/VFS/Slave/FileInfoOptions:1.0",
   0, 1,
   NULL,
   (CORBA_TypeCode *) anon_subtypes_array72,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_GNOME_VFS_Slave_DirectoryFilterType_0 == 'g') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_DirectoryFilterType_1 == 'n') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_DirectoryFilterType_2 == 'o') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_DirectoryFilterType_3 == 'm') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_DirectoryFilterType_4 == 'e') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_DirectoryFilterType_5 == '_') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_DirectoryFilterType_6 == 'v') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_DirectoryFilterType_7 == 'f') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_DirectoryFilterType_8 == 's') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_DirectoryFilterType_9 == '_') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_DirectoryFilterType_10 == 's') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_DirectoryFilterType_11 == 'l') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_DirectoryFilterType_12 == 'a') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_DirectoryFilterType_13 == 'v') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_DirectoryFilterType_14 == 'e') \
) && !defined(TC_DEF_TC_GNOME_VFS_Slave_DirectoryFilterType)
#define TC_DEF_TC_GNOME_VFS_Slave_DirectoryFilterType 1
static const CORBA_TypeCode anon_subtypes_array81[] =
   { (CORBA_TypeCode) & TC_CORBA_unsigned_short_struct };
const struct CORBA_TypeCode_struct
   TC_GNOME_VFS_Slave_DirectoryFilterType_struct = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_alias, "DirectoryFilterType",
      "IDL:GNOME/VFS/Slave/DirectoryFilterType:1.0",
   0, 1,
   NULL,
   (CORBA_TypeCode *) anon_subtypes_array81,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_GNOME_VFS_Slave_DirectoryFilterOptions_0 == 'g') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_DirectoryFilterOptions_1 == 'n') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_DirectoryFilterOptions_2 == 'o') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_DirectoryFilterOptions_3 == 'm') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_DirectoryFilterOptions_4 == 'e') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_DirectoryFilterOptions_5 == '_') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_DirectoryFilterOptions_6 == 'v') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_DirectoryFilterOptions_7 == 'f') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_DirectoryFilterOptions_8 == 's') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_DirectoryFilterOptions_9 == '_') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_DirectoryFilterOptions_10 == 's') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_DirectoryFilterOptions_11 == 'l') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_DirectoryFilterOptions_12 == 'a') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_DirectoryFilterOptions_13 == 'v') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_DirectoryFilterOptions_14 == 'e') \
) && !defined(TC_DEF_TC_GNOME_VFS_Slave_DirectoryFilterOptions)
#define TC_DEF_TC_GNOME_VFS_Slave_DirectoryFilterOptions 1
static const CORBA_TypeCode anon_subtypes_array90[] =
   { (CORBA_TypeCode) & TC_CORBA_unsigned_long_struct };
const struct CORBA_TypeCode_struct
   TC_GNOME_VFS_Slave_DirectoryFilterOptions_struct = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_alias, "DirectoryFilterOptions",
      "IDL:GNOME/VFS/Slave/DirectoryFilterOptions:1.0",
   0, 1,
   NULL,
   (CORBA_TypeCode *) anon_subtypes_array90,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_GNOME_VFS_Slave_DirectoryFilter_0 == 'g') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_DirectoryFilter_1 == 'n') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_DirectoryFilter_2 == 'o') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_DirectoryFilter_3 == 'm') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_DirectoryFilter_4 == 'e') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_DirectoryFilter_5 == '_') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_DirectoryFilter_6 == 'v') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_DirectoryFilter_7 == 'f') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_DirectoryFilter_8 == 's') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_DirectoryFilter_9 == '_') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_DirectoryFilter_10 == 's') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_DirectoryFilter_11 == 'l') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_DirectoryFilter_12 == 'a') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_DirectoryFilter_13 == 'v') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_DirectoryFilter_14 == 'e') \
) && !defined(TC_DEF_TC_GNOME_VFS_Slave_DirectoryFilter)
#define TC_DEF_TC_GNOME_VFS_Slave_DirectoryFilter 1
static const char *anon_subnames_array93[] = { "type", "options", "pattern" };
static const CORBA_TypeCode anon_subtypes_array94[] =
   { (CORBA_TypeCode) & TC_GNOME_VFS_Slave_DirectoryFilterType_struct,
      (CORBA_TypeCode) & TC_GNOME_VFS_Slave_DirectoryFilterOptions_struct,
      (CORBA_TypeCode) & TC_CORBA_string_struct };
const struct CORBA_TypeCode_struct TC_GNOME_VFS_Slave_DirectoryFilter_struct = {
   
      {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},

   CORBA_tk_struct, "DirectoryFilter",
      "IDL:GNOME/VFS/Slave/DirectoryFilter:1.0",
   0, 3,
   (const char **) anon_subnames_array93,
   (CORBA_TypeCode *) anon_subtypes_array94,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_GNOME_VFS_Slave_DirectorySortRule_0 == 'g') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_DirectorySortRule_1 == 'n') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_DirectorySortRule_2 == 'o') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_DirectorySortRule_3 == 'm') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_DirectorySortRule_4 == 'e') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_DirectorySortRule_5 == '_') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_DirectorySortRule_6 == 'v') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_DirectorySortRule_7 == 'f') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_DirectorySortRule_8 == 's') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_DirectorySortRule_9 == '_') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_DirectorySortRule_10 == 's') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_DirectorySortRule_11 == 'l') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_DirectorySortRule_12 == 'a') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_DirectorySortRule_13 == 'v') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_DirectorySortRule_14 == 'e') \
) && !defined(TC_DEF_TC_GNOME_VFS_Slave_DirectorySortRule)
#define TC_DEF_TC_GNOME_VFS_Slave_DirectorySortRule 1
static const CORBA_TypeCode anon_subtypes_array103[] =
   { (CORBA_TypeCode) & TC_CORBA_unsigned_short_struct };
const struct CORBA_TypeCode_struct TC_GNOME_VFS_Slave_DirectorySortRule_struct
   = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_alias, "DirectorySortRule",
      "IDL:GNOME/VFS/Slave/DirectorySortRule:1.0",
   0, 1,
   NULL,
   (CORBA_TypeCode *) anon_subtypes_array103,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_CORBA_sequence_GNOME_VFS_Slave_DirectorySortRule_0 == 'g') \
&& (TC_IMPL_TC_CORBA_sequence_GNOME_VFS_Slave_DirectorySortRule_1 == 'n') \
&& (TC_IMPL_TC_CORBA_sequence_GNOME_VFS_Slave_DirectorySortRule_2 == 'o') \
&& (TC_IMPL_TC_CORBA_sequence_GNOME_VFS_Slave_DirectorySortRule_3 == 'm') \
&& (TC_IMPL_TC_CORBA_sequence_GNOME_VFS_Slave_DirectorySortRule_4 == 'e') \
&& (TC_IMPL_TC_CORBA_sequence_GNOME_VFS_Slave_DirectorySortRule_5 == '_') \
&& (TC_IMPL_TC_CORBA_sequence_GNOME_VFS_Slave_DirectorySortRule_6 == 'v') \
&& (TC_IMPL_TC_CORBA_sequence_GNOME_VFS_Slave_DirectorySortRule_7 == 'f') \
&& (TC_IMPL_TC_CORBA_sequence_GNOME_VFS_Slave_DirectorySortRule_8 == 's') \
&& (TC_IMPL_TC_CORBA_sequence_GNOME_VFS_Slave_DirectorySortRule_9 == '_') \
&& (TC_IMPL_TC_CORBA_sequence_GNOME_VFS_Slave_DirectorySortRule_10 == 's') \
&& (TC_IMPL_TC_CORBA_sequence_GNOME_VFS_Slave_DirectorySortRule_11 == 'l') \
&& (TC_IMPL_TC_CORBA_sequence_GNOME_VFS_Slave_DirectorySortRule_12 == 'a') \
&& (TC_IMPL_TC_CORBA_sequence_GNOME_VFS_Slave_DirectorySortRule_13 == 'v') \
&& (TC_IMPL_TC_CORBA_sequence_GNOME_VFS_Slave_DirectorySortRule_14 == 'e') \
) && !defined(TC_DEF_TC_CORBA_sequence_GNOME_VFS_Slave_DirectorySortRule)
#define TC_DEF_TC_CORBA_sequence_GNOME_VFS_Slave_DirectorySortRule 1
static const CORBA_TypeCode anon_subtypes_array107[] =
   { (CORBA_TypeCode) & TC_GNOME_VFS_Slave_DirectorySortRule_struct };
const struct CORBA_TypeCode_struct
   TC_CORBA_sequence_GNOME_VFS_Slave_DirectorySortRule_struct = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_sequence, NULL, NULL,
   0, 1,
   NULL,
   (CORBA_TypeCode *) anon_subtypes_array107,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_CORBA_sequence_GNOME_VFS_Slave_DirectorySortRule_0 == 'g') \
&& (TC_IMPL_TC_CORBA_sequence_GNOME_VFS_Slave_DirectorySortRule_1 == 'n') \
&& (TC_IMPL_TC_CORBA_sequence_GNOME_VFS_Slave_DirectorySortRule_2 == 'o') \
&& (TC_IMPL_TC_CORBA_sequence_GNOME_VFS_Slave_DirectorySortRule_3 == 'm') \
&& (TC_IMPL_TC_CORBA_sequence_GNOME_VFS_Slave_DirectorySortRule_4 == 'e') \
&& (TC_IMPL_TC_CORBA_sequence_GNOME_VFS_Slave_DirectorySortRule_5 == '_') \
&& (TC_IMPL_TC_CORBA_sequence_GNOME_VFS_Slave_DirectorySortRule_6 == 'v') \
&& (TC_IMPL_TC_CORBA_sequence_GNOME_VFS_Slave_DirectorySortRule_7 == 'f') \
&& (TC_IMPL_TC_CORBA_sequence_GNOME_VFS_Slave_DirectorySortRule_8 == 's') \
&& (TC_IMPL_TC_CORBA_sequence_GNOME_VFS_Slave_DirectorySortRule_9 == '_') \
&& (TC_IMPL_TC_CORBA_sequence_GNOME_VFS_Slave_DirectorySortRule_10 == 's') \
&& (TC_IMPL_TC_CORBA_sequence_GNOME_VFS_Slave_DirectorySortRule_11 == 'l') \
&& (TC_IMPL_TC_CORBA_sequence_GNOME_VFS_Slave_DirectorySortRule_12 == 'a') \
&& (TC_IMPL_TC_CORBA_sequence_GNOME_VFS_Slave_DirectorySortRule_13 == 'v') \
&& (TC_IMPL_TC_CORBA_sequence_GNOME_VFS_Slave_DirectorySortRule_14 == 'e') \
) && !defined(TC_DEF_TC_CORBA_sequence_GNOME_VFS_Slave_DirectorySortRule)
#define TC_DEF_TC_CORBA_sequence_GNOME_VFS_Slave_DirectorySortRule 1
static const CORBA_TypeCode anon_subtypes_array116[] =
   { (CORBA_TypeCode) & TC_GNOME_VFS_Slave_DirectorySortRule_struct };
const struct CORBA_TypeCode_struct
   TC_CORBA_sequence_GNOME_VFS_Slave_DirectorySortRule_struct = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_sequence, NULL, NULL,
   0, 1,
   NULL,
   (CORBA_TypeCode *) anon_subtypes_array116,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_GNOME_VFS_Slave_DirectorySortRuleList_0 == 'g') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_DirectorySortRuleList_1 == 'n') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_DirectorySortRuleList_2 == 'o') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_DirectorySortRuleList_3 == 'm') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_DirectorySortRuleList_4 == 'e') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_DirectorySortRuleList_5 == '_') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_DirectorySortRuleList_6 == 'v') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_DirectorySortRuleList_7 == 'f') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_DirectorySortRuleList_8 == 's') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_DirectorySortRuleList_9 == '_') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_DirectorySortRuleList_10 == 's') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_DirectorySortRuleList_11 == 'l') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_DirectorySortRuleList_12 == 'a') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_DirectorySortRuleList_13 == 'v') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_DirectorySortRuleList_14 == 'e') \
) && !defined(TC_DEF_TC_GNOME_VFS_Slave_DirectorySortRuleList)
#define TC_DEF_TC_GNOME_VFS_Slave_DirectorySortRuleList 1
static const CORBA_TypeCode anon_subtypes_array120[] =
   { (CORBA_TypeCode) &

TC_CORBA_sequence_GNOME_VFS_Slave_DirectorySortRule_struct };
const struct CORBA_TypeCode_struct
   TC_GNOME_VFS_Slave_DirectorySortRuleList_struct = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_alias, "DirectorySortRuleList",
      "IDL:GNOME/VFS/Slave/DirectorySortRuleList:1.0",
   0, 1,
   NULL,
   (CORBA_TypeCode *) anon_subtypes_array120,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_GNOME_VFS_Slave_XferPhase_0 == 'g') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_XferPhase_1 == 'n') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_XferPhase_2 == 'o') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_XferPhase_3 == 'm') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_XferPhase_4 == 'e') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_XferPhase_5 == '_') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_XferPhase_6 == 'v') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_XferPhase_7 == 'f') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_XferPhase_8 == 's') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_XferPhase_9 == '_') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_XferPhase_10 == 's') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_XferPhase_11 == 'l') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_XferPhase_12 == 'a') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_XferPhase_13 == 'v') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_XferPhase_14 == 'e') \
) && !defined(TC_DEF_TC_GNOME_VFS_Slave_XferPhase)
#define TC_DEF_TC_GNOME_VFS_Slave_XferPhase 1
static const CORBA_TypeCode anon_subtypes_array129[] =
   { (CORBA_TypeCode) & TC_CORBA_unsigned_short_struct };
const struct CORBA_TypeCode_struct TC_GNOME_VFS_Slave_XferPhase_struct = {
   
      {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},

   CORBA_tk_alias, "XferPhase", "IDL:GNOME/VFS/Slave/XferPhase:1.0",
   0, 1,
   NULL,
   (CORBA_TypeCode *) anon_subtypes_array129,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_GNOME_VFS_Slave_XferOptions_0 == 'g') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_XferOptions_1 == 'n') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_XferOptions_2 == 'o') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_XferOptions_3 == 'm') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_XferOptions_4 == 'e') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_XferOptions_5 == '_') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_XferOptions_6 == 'v') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_XferOptions_7 == 'f') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_XferOptions_8 == 's') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_XferOptions_9 == '_') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_XferOptions_10 == 's') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_XferOptions_11 == 'l') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_XferOptions_12 == 'a') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_XferOptions_13 == 'v') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_XferOptions_14 == 'e') \
) && !defined(TC_DEF_TC_GNOME_VFS_Slave_XferOptions)
#define TC_DEF_TC_GNOME_VFS_Slave_XferOptions 1
static const CORBA_TypeCode anon_subtypes_array138[] =
   { (CORBA_TypeCode) & TC_CORBA_unsigned_long_struct };
const struct CORBA_TypeCode_struct TC_GNOME_VFS_Slave_XferOptions_struct = {
   
      {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},

   CORBA_tk_alias, "XferOptions", "IDL:GNOME/VFS/Slave/XferOptions:1.0",
   0, 1,
   NULL,
   (CORBA_TypeCode *) anon_subtypes_array138,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_GNOME_VFS_Slave_XferErrorMode_0 == 'g') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_XferErrorMode_1 == 'n') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_XferErrorMode_2 == 'o') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_XferErrorMode_3 == 'm') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_XferErrorMode_4 == 'e') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_XferErrorMode_5 == '_') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_XferErrorMode_6 == 'v') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_XferErrorMode_7 == 'f') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_XferErrorMode_8 == 's') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_XferErrorMode_9 == '_') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_XferErrorMode_10 == 's') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_XferErrorMode_11 == 'l') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_XferErrorMode_12 == 'a') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_XferErrorMode_13 == 'v') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_XferErrorMode_14 == 'e') \
) && !defined(TC_DEF_TC_GNOME_VFS_Slave_XferErrorMode)
#define TC_DEF_TC_GNOME_VFS_Slave_XferErrorMode 1
static const CORBA_TypeCode anon_subtypes_array147[] =
   { (CORBA_TypeCode) & TC_CORBA_unsigned_short_struct };
const struct CORBA_TypeCode_struct TC_GNOME_VFS_Slave_XferErrorMode_struct = {
   
      {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},

   CORBA_tk_alias, "XferErrorMode", "IDL:GNOME/VFS/Slave/XferErrorMode:1.0",
   0, 1,
   NULL,
   (CORBA_TypeCode *) anon_subtypes_array147,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_GNOME_VFS_Slave_XferOverwriteMode_0 == 'g') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_XferOverwriteMode_1 == 'n') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_XferOverwriteMode_2 == 'o') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_XferOverwriteMode_3 == 'm') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_XferOverwriteMode_4 == 'e') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_XferOverwriteMode_5 == '_') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_XferOverwriteMode_6 == 'v') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_XferOverwriteMode_7 == 'f') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_XferOverwriteMode_8 == 's') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_XferOverwriteMode_9 == '_') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_XferOverwriteMode_10 == 's') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_XferOverwriteMode_11 == 'l') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_XferOverwriteMode_12 == 'a') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_XferOverwriteMode_13 == 'v') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_XferOverwriteMode_14 == 'e') \
) && !defined(TC_DEF_TC_GNOME_VFS_Slave_XferOverwriteMode)
#define TC_DEF_TC_GNOME_VFS_Slave_XferOverwriteMode 1
static const CORBA_TypeCode anon_subtypes_array156[] =
   { (CORBA_TypeCode) & TC_CORBA_unsigned_short_struct };
const struct CORBA_TypeCode_struct TC_GNOME_VFS_Slave_XferOverwriteMode_struct
   = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_alias, "XferOverwriteMode",
      "IDL:GNOME/VFS/Slave/XferOverwriteMode:1.0",
   0, 1,
   NULL,
   (CORBA_TypeCode *) anon_subtypes_array156,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_CORBA_sequence_CORBA_string_0 == 'g') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_1 == 'n') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_2 == 'o') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_3 == 'm') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_4 == 'e') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_5 == '_') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_6 == 'v') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_7 == 'f') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_8 == 's') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_9 == '_') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_10 == 's') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_11 == 'l') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_12 == 'a') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_13 == 'v') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_14 == 'e') \
) && !defined(TC_DEF_TC_CORBA_sequence_CORBA_string)
#define TC_DEF_TC_CORBA_sequence_CORBA_string 1
static const CORBA_TypeCode anon_subtypes_array160[] =
   { (CORBA_TypeCode) & TC_CORBA_string_struct };
const struct CORBA_TypeCode_struct TC_CORBA_sequence_CORBA_string_struct = {
   
      {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},

   CORBA_tk_sequence, NULL, NULL,
   0, 1,
   NULL,
   (CORBA_TypeCode *) anon_subtypes_array160,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_CORBA_sequence_CORBA_string_0 == 'g') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_1 == 'n') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_2 == 'o') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_3 == 'm') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_4 == 'e') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_5 == '_') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_6 == 'v') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_7 == 'f') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_8 == 's') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_9 == '_') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_10 == 's') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_11 == 'l') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_12 == 'a') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_13 == 'v') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_14 == 'e') \
) && !defined(TC_DEF_TC_CORBA_sequence_CORBA_string)
#define TC_DEF_TC_CORBA_sequence_CORBA_string 1
static const CORBA_TypeCode anon_subtypes_array169[] =
   { (CORBA_TypeCode) & TC_CORBA_string_struct };
const struct CORBA_TypeCode_struct TC_CORBA_sequence_CORBA_string_struct = {
   
      {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},

   CORBA_tk_sequence, NULL, NULL,
   0, 1,
   NULL,
   (CORBA_TypeCode *) anon_subtypes_array169,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_GNOME_VFS_Slave_FileNameList_0 == 'g') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_FileNameList_1 == 'n') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_FileNameList_2 == 'o') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_FileNameList_3 == 'm') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_FileNameList_4 == 'e') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_FileNameList_5 == '_') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_FileNameList_6 == 'v') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_FileNameList_7 == 'f') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_FileNameList_8 == 's') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_FileNameList_9 == '_') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_FileNameList_10 == 's') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_FileNameList_11 == 'l') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_FileNameList_12 == 'a') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_FileNameList_13 == 'v') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_FileNameList_14 == 'e') \
) && !defined(TC_DEF_TC_GNOME_VFS_Slave_FileNameList)
#define TC_DEF_TC_GNOME_VFS_Slave_FileNameList 1
static const CORBA_TypeCode anon_subtypes_array173[] =
   { (CORBA_TypeCode) & TC_CORBA_sequence_CORBA_string_struct };
const struct CORBA_TypeCode_struct TC_GNOME_VFS_Slave_FileNameList_struct = {
   
      {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},

   CORBA_tk_alias, "FileNameList", "IDL:GNOME/VFS/Slave/FileNameList:1.0",
   0, 1,
   NULL,
   (CORBA_TypeCode *) anon_subtypes_array173,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_CORBA_sequence_CORBA_string_0 == 'g') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_1 == 'n') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_2 == 'o') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_3 == 'm') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_4 == 'e') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_5 == '_') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_6 == 'v') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_7 == 'f') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_8 == 's') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_9 == '_') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_10 == 's') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_11 == 'l') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_12 == 'a') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_13 == 'v') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_14 == 'e') \
) && !defined(TC_DEF_TC_CORBA_sequence_CORBA_string)
#define TC_DEF_TC_CORBA_sequence_CORBA_string 1
static const CORBA_TypeCode anon_subtypes_array177[] =
   { (CORBA_TypeCode) & TC_CORBA_string_struct };
const struct CORBA_TypeCode_struct TC_CORBA_sequence_CORBA_string_struct = {
   
      {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},

   CORBA_tk_sequence, NULL, NULL,
   0, 1,
   NULL,
   (CORBA_TypeCode *) anon_subtypes_array177,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_CORBA_sequence_CORBA_string_0 == 'g') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_1 == 'n') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_2 == 'o') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_3 == 'm') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_4 == 'e') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_5 == '_') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_6 == 'v') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_7 == 'f') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_8 == 's') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_9 == '_') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_10 == 's') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_11 == 'l') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_12 == 'a') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_13 == 'v') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_14 == 'e') \
) && !defined(TC_DEF_TC_CORBA_sequence_CORBA_string)
#define TC_DEF_TC_CORBA_sequence_CORBA_string 1
static const CORBA_TypeCode anon_subtypes_array186[] =
   { (CORBA_TypeCode) & TC_CORBA_string_struct };
const struct CORBA_TypeCode_struct TC_CORBA_sequence_CORBA_string_struct = {
   
      {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},

   CORBA_tk_sequence, NULL, NULL,
   0, 1,
   NULL,
   (CORBA_TypeCode *) anon_subtypes_array186,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_GNOME_VFS_Slave_URIList_0 == 'g') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_URIList_1 == 'n') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_URIList_2 == 'o') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_URIList_3 == 'm') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_URIList_4 == 'e') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_URIList_5 == '_') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_URIList_6 == 'v') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_URIList_7 == 'f') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_URIList_8 == 's') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_URIList_9 == '_') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_URIList_10 == 's') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_URIList_11 == 'l') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_URIList_12 == 'a') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_URIList_13 == 'v') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_URIList_14 == 'e') \
) && !defined(TC_DEF_TC_GNOME_VFS_Slave_URIList)
#define TC_DEF_TC_GNOME_VFS_Slave_URIList 1
static const CORBA_TypeCode anon_subtypes_array190[] =
   { (CORBA_TypeCode) & TC_CORBA_sequence_CORBA_string_struct };
const struct CORBA_TypeCode_struct TC_GNOME_VFS_Slave_URIList_struct = {
   
      {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},

   CORBA_tk_alias, "URIList", "IDL:GNOME/VFS/Slave/URIList:1.0",
   0, 1,
   NULL,
   (CORBA_TypeCode *) anon_subtypes_array190,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_GNOME_VFS_Slave_GetFileInfoResult_0 == 'g') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_GetFileInfoResult_1 == 'n') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_GetFileInfoResult_2 == 'o') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_GetFileInfoResult_3 == 'm') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_GetFileInfoResult_4 == 'e') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_GetFileInfoResult_5 == '_') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_GetFileInfoResult_6 == 'v') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_GetFileInfoResult_7 == 'f') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_GetFileInfoResult_8 == 's') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_GetFileInfoResult_9 == '_') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_GetFileInfoResult_10 == 's') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_GetFileInfoResult_11 == 'l') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_GetFileInfoResult_12 == 'a') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_GetFileInfoResult_13 == 'v') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_GetFileInfoResult_14 == 'e') \
) && !defined(TC_DEF_TC_GNOME_VFS_Slave_GetFileInfoResult)
#define TC_DEF_TC_GNOME_VFS_Slave_GetFileInfoResult 1
static const char *anon_subnames_array193[] =

   { "uri", "result", "file_info" };
static const CORBA_TypeCode anon_subtypes_array194[] =
   { (CORBA_TypeCode) & TC_CORBA_string_struct,
      (CORBA_TypeCode) & TC_GNOME_VFS_Result_struct,
      (CORBA_TypeCode) & TC_GNOME_VFS_Slave_FileInfo_struct };
const struct CORBA_TypeCode_struct TC_GNOME_VFS_Slave_GetFileInfoResult_struct
   = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_struct, "GetFileInfoResult",
      "IDL:GNOME/VFS/Slave/GetFileInfoResult:1.0",
   0, 3,
   (const char **) anon_subnames_array193,
   (CORBA_TypeCode *) anon_subtypes_array194,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_CORBA_sequence_GNOME_VFS_Slave_GetFileInfoResult_0 == 'g') \
&& (TC_IMPL_TC_CORBA_sequence_GNOME_VFS_Slave_GetFileInfoResult_1 == 'n') \
&& (TC_IMPL_TC_CORBA_sequence_GNOME_VFS_Slave_GetFileInfoResult_2 == 'o') \
&& (TC_IMPL_TC_CORBA_sequence_GNOME_VFS_Slave_GetFileInfoResult_3 == 'm') \
&& (TC_IMPL_TC_CORBA_sequence_GNOME_VFS_Slave_GetFileInfoResult_4 == 'e') \
&& (TC_IMPL_TC_CORBA_sequence_GNOME_VFS_Slave_GetFileInfoResult_5 == '_') \
&& (TC_IMPL_TC_CORBA_sequence_GNOME_VFS_Slave_GetFileInfoResult_6 == 'v') \
&& (TC_IMPL_TC_CORBA_sequence_GNOME_VFS_Slave_GetFileInfoResult_7 == 'f') \
&& (TC_IMPL_TC_CORBA_sequence_GNOME_VFS_Slave_GetFileInfoResult_8 == 's') \
&& (TC_IMPL_TC_CORBA_sequence_GNOME_VFS_Slave_GetFileInfoResult_9 == '_') \
&& (TC_IMPL_TC_CORBA_sequence_GNOME_VFS_Slave_GetFileInfoResult_10 == 's') \
&& (TC_IMPL_TC_CORBA_sequence_GNOME_VFS_Slave_GetFileInfoResult_11 == 'l') \
&& (TC_IMPL_TC_CORBA_sequence_GNOME_VFS_Slave_GetFileInfoResult_12 == 'a') \
&& (TC_IMPL_TC_CORBA_sequence_GNOME_VFS_Slave_GetFileInfoResult_13 == 'v') \
&& (TC_IMPL_TC_CORBA_sequence_GNOME_VFS_Slave_GetFileInfoResult_14 == 'e') \
) && !defined(TC_DEF_TC_CORBA_sequence_GNOME_VFS_Slave_GetFileInfoResult)
#define TC_DEF_TC_CORBA_sequence_GNOME_VFS_Slave_GetFileInfoResult 1
static const CORBA_TypeCode anon_subtypes_array198[] =
   { (CORBA_TypeCode) & TC_GNOME_VFS_Slave_GetFileInfoResult_struct };
const struct CORBA_TypeCode_struct
   TC_CORBA_sequence_GNOME_VFS_Slave_GetFileInfoResult_struct = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_sequence, NULL, NULL,
   0, 1,
   NULL,
   (CORBA_TypeCode *) anon_subtypes_array198,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_CORBA_sequence_GNOME_VFS_Slave_GetFileInfoResult_0 == 'g') \
&& (TC_IMPL_TC_CORBA_sequence_GNOME_VFS_Slave_GetFileInfoResult_1 == 'n') \
&& (TC_IMPL_TC_CORBA_sequence_GNOME_VFS_Slave_GetFileInfoResult_2 == 'o') \
&& (TC_IMPL_TC_CORBA_sequence_GNOME_VFS_Slave_GetFileInfoResult_3 == 'm') \
&& (TC_IMPL_TC_CORBA_sequence_GNOME_VFS_Slave_GetFileInfoResult_4 == 'e') \
&& (TC_IMPL_TC_CORBA_sequence_GNOME_VFS_Slave_GetFileInfoResult_5 == '_') \
&& (TC_IMPL_TC_CORBA_sequence_GNOME_VFS_Slave_GetFileInfoResult_6 == 'v') \
&& (TC_IMPL_TC_CORBA_sequence_GNOME_VFS_Slave_GetFileInfoResult_7 == 'f') \
&& (TC_IMPL_TC_CORBA_sequence_GNOME_VFS_Slave_GetFileInfoResult_8 == 's') \
&& (TC_IMPL_TC_CORBA_sequence_GNOME_VFS_Slave_GetFileInfoResult_9 == '_') \
&& (TC_IMPL_TC_CORBA_sequence_GNOME_VFS_Slave_GetFileInfoResult_10 == 's') \
&& (TC_IMPL_TC_CORBA_sequence_GNOME_VFS_Slave_GetFileInfoResult_11 == 'l') \
&& (TC_IMPL_TC_CORBA_sequence_GNOME_VFS_Slave_GetFileInfoResult_12 == 'a') \
&& (TC_IMPL_TC_CORBA_sequence_GNOME_VFS_Slave_GetFileInfoResult_13 == 'v') \
&& (TC_IMPL_TC_CORBA_sequence_GNOME_VFS_Slave_GetFileInfoResult_14 == 'e') \
) && !defined(TC_DEF_TC_CORBA_sequence_GNOME_VFS_Slave_GetFileInfoResult)
#define TC_DEF_TC_CORBA_sequence_GNOME_VFS_Slave_GetFileInfoResult 1
static const CORBA_TypeCode anon_subtypes_array207[] =
   { (CORBA_TypeCode) & TC_GNOME_VFS_Slave_GetFileInfoResult_struct };
const struct CORBA_TypeCode_struct
   TC_CORBA_sequence_GNOME_VFS_Slave_GetFileInfoResult_struct = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_sequence, NULL, NULL,
   0, 1,
   NULL,
   (CORBA_TypeCode *) anon_subtypes_array207,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_GNOME_VFS_Slave_GetFileInfoResultList_0 == 'g') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_GetFileInfoResultList_1 == 'n') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_GetFileInfoResultList_2 == 'o') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_GetFileInfoResultList_3 == 'm') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_GetFileInfoResultList_4 == 'e') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_GetFileInfoResultList_5 == '_') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_GetFileInfoResultList_6 == 'v') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_GetFileInfoResultList_7 == 'f') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_GetFileInfoResultList_8 == 's') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_GetFileInfoResultList_9 == '_') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_GetFileInfoResultList_10 == 's') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_GetFileInfoResultList_11 == 'l') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_GetFileInfoResultList_12 == 'a') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_GetFileInfoResultList_13 == 'v') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_GetFileInfoResultList_14 == 'e') \
) && !defined(TC_DEF_TC_GNOME_VFS_Slave_GetFileInfoResultList)
#define TC_DEF_TC_GNOME_VFS_Slave_GetFileInfoResultList 1
static const CORBA_TypeCode anon_subtypes_array211[] =
   { (CORBA_TypeCode) &

TC_CORBA_sequence_GNOME_VFS_Slave_GetFileInfoResult_struct };
const struct CORBA_TypeCode_struct
   TC_GNOME_VFS_Slave_GetFileInfoResultList_struct = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_alias, "GetFileInfoResultList",
      "IDL:GNOME/VFS/Slave/GetFileInfoResultList:1.0",
   0, 1,
   NULL,
   (CORBA_TypeCode *) anon_subtypes_array211,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_GNOME_VFS_Slave_Request_0 == 'g') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_Request_1 == 'n') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_Request_2 == 'o') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_Request_3 == 'm') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_Request_4 == 'e') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_Request_5 == '_') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_Request_6 == 'v') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_Request_7 == 'f') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_Request_8 == 's') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_Request_9 == '_') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_Request_10 == 's') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_Request_11 == 'l') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_Request_12 == 'a') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_Request_13 == 'v') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_Request_14 == 'e') \
) && !defined(TC_DEF_TC_GNOME_VFS_Slave_Request)
#define TC_DEF_TC_GNOME_VFS_Slave_Request 1
const struct CORBA_TypeCode_struct TC_GNOME_VFS_Slave_Request_struct = {
   
      {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},

   CORBA_tk_objref, "Request", "IDL:GNOME/VFS/Slave/Request:1.0",
   0, 0,
   NULL,
   NULL,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_GNOME_VFS_Slave_FileHandle_0 == 'g') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_FileHandle_1 == 'n') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_FileHandle_2 == 'o') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_FileHandle_3 == 'm') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_FileHandle_4 == 'e') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_FileHandle_5 == '_') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_FileHandle_6 == 'v') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_FileHandle_7 == 'f') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_FileHandle_8 == 's') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_FileHandle_9 == '_') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_FileHandle_10 == 's') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_FileHandle_11 == 'l') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_FileHandle_12 == 'a') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_FileHandle_13 == 'v') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_FileHandle_14 == 'e') \
) && !defined(TC_DEF_TC_GNOME_VFS_Slave_FileHandle)
#define TC_DEF_TC_GNOME_VFS_Slave_FileHandle 1
const struct CORBA_TypeCode_struct TC_GNOME_VFS_Slave_FileHandle_struct = {
   
      {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},

   CORBA_tk_objref, "FileHandle", "IDL:GNOME/VFS/Slave/FileHandle:1.0",
   0, 0,
   NULL,
   NULL,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_GNOME_VFS_Slave_Notify_0 == 'g') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_Notify_1 == 'n') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_Notify_2 == 'o') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_Notify_3 == 'm') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_Notify_4 == 'e') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_Notify_5 == '_') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_Notify_6 == 'v') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_Notify_7 == 'f') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_Notify_8 == 's') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_Notify_9 == '_') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_Notify_10 == 's') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_Notify_11 == 'l') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_Notify_12 == 'a') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_Notify_13 == 'v') \
&& (TC_IMPL_TC_GNOME_VFS_Slave_Notify_14 == 'e') \
) && !defined(TC_DEF_TC_GNOME_VFS_Slave_Notify)
#define TC_DEF_TC_GNOME_VFS_Slave_Notify 1
const struct CORBA_TypeCode_struct TC_GNOME_VFS_Slave_Notify_struct = {
   
      {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},

   CORBA_tk_objref, "Notify", "IDL:GNOME/VFS/Slave/Notify:1.0",
   0, 0,
   NULL,
   NULL,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (ORBIT_IMPL_CORBA_sequence_CORBA_octet_0 == 'g') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_octet_1 == 'n') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_octet_2 == 'o') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_octet_3 == 'm') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_octet_4 == 'e') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_octet_5 == '_') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_octet_6 == 'v') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_octet_7 == 'f') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_octet_8 == 's') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_octet_9 == '_') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_octet_10 == 's') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_octet_11 == 'l') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_octet_12 == 'a') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_octet_13 == 'v') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_octet_14 == 'e') \
) && !defined(ORBIT_DEF_CORBA_sequence_CORBA_octet)
#define ORBIT_DEF_CORBA_sequence_CORBA_octet 1

gpointer
CORBA_sequence_CORBA_octet__free(gpointer mem, gpointer dat,
				 CORBA_boolean free_strings)
{
   CORBA_sequence_CORBA_octet *val = mem;

   if (val->_release)
      ORBit_free(val->_buffer, free_strings);
   return (gpointer) (val + 1);
}

CORBA_sequence_CORBA_octet *
CORBA_sequence_CORBA_octet__alloc(void)
{
   CORBA_sequence_CORBA_octet *retval;

   retval =
      ORBit_alloc(sizeof(CORBA_sequence_CORBA_octet),
		  (ORBit_free_childvals) CORBA_sequence_CORBA_octet__free,
		  GUINT_TO_POINTER(1));
   retval->_maximum = 0;
   retval->_length = 0;
   retval->_buffer = NULL;
   retval->_release = CORBA_FALSE;
   return retval;
}

CORBA_octet *
CORBA_sequence_CORBA_octet_allocbuf(CORBA_unsigned_long len)
{
   CORBA_octet *retval =
      ORBit_alloc(sizeof(CORBA_octet) * len, (ORBit_free_childvals) NULL,
		  GUINT_TO_POINTER(len));

   return retval;
}
#endif

gpointer
GNOME_VFS_Buffer__free(gpointer mem, gpointer dat, CORBA_boolean free_strings)
{
   return CORBA_sequence_CORBA_octet__free(mem, dat, free_strings);
}

GNOME_VFS_Buffer *
GNOME_VFS_Buffer__alloc(void)
{
   return CORBA_sequence_CORBA_octet__alloc();
}

#if ( (ORBIT_IMPL_CORBA_sequence_CORBA_octet_0 == 'g') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_octet_1 == 'n') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_octet_2 == 'o') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_octet_3 == 'm') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_octet_4 == 'e') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_octet_5 == '_') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_octet_6 == 'v') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_octet_7 == 'f') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_octet_8 == 's') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_octet_9 == '_') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_octet_10 == 's') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_octet_11 == 'l') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_octet_12 == 'a') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_octet_13 == 'v') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_octet_14 == 'e') \
) && !defined(ORBIT_DEF_CORBA_sequence_CORBA_octet)
#define ORBIT_DEF_CORBA_sequence_CORBA_octet 1

gpointer
CORBA_sequence_CORBA_octet__free(gpointer mem, gpointer dat,
				 CORBA_boolean free_strings)
{
   CORBA_sequence_CORBA_octet *val = mem;

   if (val->_release)
      ORBit_free(val->_buffer, free_strings);
   return (gpointer) (val + 1);
}

CORBA_sequence_CORBA_octet *
CORBA_sequence_CORBA_octet__alloc(void)
{
   CORBA_sequence_CORBA_octet *retval;

   retval =
      ORBit_alloc(sizeof(CORBA_sequence_CORBA_octet),
		  (ORBit_free_childvals) CORBA_sequence_CORBA_octet__free,
		  GUINT_TO_POINTER(1));
   retval->_maximum = 0;
   retval->_length = 0;
   retval->_buffer = NULL;
   retval->_release = CORBA_FALSE;
   return retval;
}

CORBA_octet *
CORBA_sequence_CORBA_octet_allocbuf(CORBA_unsigned_long len)
{
   CORBA_octet *retval =
      ORBit_alloc(sizeof(CORBA_octet) * len, (ORBit_free_childvals) NULL,
		  GUINT_TO_POINTER(len));

   return retval;
}
#endif

gpointer
GNOME_VFS_Slave_FileInfo__free(gpointer mem, gpointer dat,
			       CORBA_boolean free_strings)
{
   GNOME_VFS_Slave_FileInfo *var = mem;

   {
      GNOME_VFS_Buffer__free(&(var->data), NULL, free_strings);
   }
   if (free_strings) {
      CORBA_string__free(&(var->name), NULL, free_strings);
   }
   if (free_strings) {
      CORBA_string__free(&(var->symlink_name), NULL, free_strings);
   }
   if (free_strings) {
      CORBA_string__free(&(var->mime_type), NULL, free_strings);
   }
   return (gpointer) (var + 1);
}

GNOME_VFS_Slave_FileInfo *
GNOME_VFS_Slave_FileInfo__alloc(void)
{
   GNOME_VFS_Slave_FileInfo *retval;

   retval =
      ORBit_alloc(sizeof(GNOME_VFS_Slave_FileInfo),
		  (ORBit_free_childvals) GNOME_VFS_Slave_FileInfo__free,
		  GUINT_TO_POINTER(1));
   memset(&(retval->data), '\0', sizeof(retval->data));
   memset(&(retval->name), '\0', sizeof(retval->name));
   memset(&(retval->symlink_name), '\0', sizeof(retval->symlink_name));
   memset(&(retval->mime_type), '\0', sizeof(retval->mime_type));
   return retval;
}

#if ( (ORBIT_IMPL_CORBA_sequence_GNOME_VFS_Slave_FileInfo_0 == 'g') \
&& (ORBIT_IMPL_CORBA_sequence_GNOME_VFS_Slave_FileInfo_1 == 'n') \
&& (ORBIT_IMPL_CORBA_sequence_GNOME_VFS_Slave_FileInfo_2 == 'o') \
&& (ORBIT_IMPL_CORBA_sequence_GNOME_VFS_Slave_FileInfo_3 == 'm') \
&& (ORBIT_IMPL_CORBA_sequence_GNOME_VFS_Slave_FileInfo_4 == 'e') \
&& (ORBIT_IMPL_CORBA_sequence_GNOME_VFS_Slave_FileInfo_5 == '_') \
&& (ORBIT_IMPL_CORBA_sequence_GNOME_VFS_Slave_FileInfo_6 == 'v') \
&& (ORBIT_IMPL_CORBA_sequence_GNOME_VFS_Slave_FileInfo_7 == 'f') \
&& (ORBIT_IMPL_CORBA_sequence_GNOME_VFS_Slave_FileInfo_8 == 's') \
&& (ORBIT_IMPL_CORBA_sequence_GNOME_VFS_Slave_FileInfo_9 == '_') \
&& (ORBIT_IMPL_CORBA_sequence_GNOME_VFS_Slave_FileInfo_10 == 's') \
&& (ORBIT_IMPL_CORBA_sequence_GNOME_VFS_Slave_FileInfo_11 == 'l') \
&& (ORBIT_IMPL_CORBA_sequence_GNOME_VFS_Slave_FileInfo_12 == 'a') \
&& (ORBIT_IMPL_CORBA_sequence_GNOME_VFS_Slave_FileInfo_13 == 'v') \
&& (ORBIT_IMPL_CORBA_sequence_GNOME_VFS_Slave_FileInfo_14 == 'e') \
) && !defined(ORBIT_DEF_CORBA_sequence_GNOME_VFS_Slave_FileInfo)
#define ORBIT_DEF_CORBA_sequence_GNOME_VFS_Slave_FileInfo 1

gpointer
CORBA_sequence_GNOME_VFS_Slave_FileInfo__free(gpointer mem, gpointer dat,
					      CORBA_boolean free_strings)
{
   CORBA_sequence_GNOME_VFS_Slave_FileInfo *val = mem;

   if (val->_release)
      ORBit_free(val->_buffer, free_strings);
   return (gpointer) (val + 1);
}

CORBA_sequence_GNOME_VFS_Slave_FileInfo *
CORBA_sequence_GNOME_VFS_Slave_FileInfo__alloc(void)
{
   CORBA_sequence_GNOME_VFS_Slave_FileInfo *retval;

   retval =
      ORBit_alloc(sizeof(CORBA_sequence_GNOME_VFS_Slave_FileInfo),
		  (ORBit_free_childvals)
		  CORBA_sequence_GNOME_VFS_Slave_FileInfo__free,
		  GUINT_TO_POINTER(1));
   retval->_maximum = 0;
   retval->_length = 0;
   retval->_buffer = NULL;
   retval->_release = CORBA_FALSE;
   return retval;
}

GNOME_VFS_Slave_FileInfo *
CORBA_sequence_GNOME_VFS_Slave_FileInfo_allocbuf(CORBA_unsigned_long len)
{
   GNOME_VFS_Slave_FileInfo *retval =
      ORBit_alloc(sizeof(GNOME_VFS_Slave_FileInfo) * len,
		  (ORBit_free_childvals) GNOME_VFS_Slave_FileInfo__free,
		  GUINT_TO_POINTER(len));

   memset(retval, '\0', sizeof(GNOME_VFS_Slave_FileInfo) * len);
   return retval;
}
#endif

gpointer
GNOME_VFS_Slave_FileInfoList__free(gpointer mem, gpointer dat,
				   CORBA_boolean free_strings)
{
   return CORBA_sequence_GNOME_VFS_Slave_FileInfo__free(mem, dat,
							free_strings);
}

GNOME_VFS_Slave_FileInfoList *
GNOME_VFS_Slave_FileInfoList__alloc(void)
{
   return CORBA_sequence_GNOME_VFS_Slave_FileInfo__alloc();
}

gpointer
GNOME_VFS_Slave_DirectoryFilter__free(gpointer mem, gpointer dat,
				      CORBA_boolean free_strings)
{
   GNOME_VFS_Slave_DirectoryFilter *var = mem;

   if (free_strings) {
      CORBA_string__free(&(var->pattern), NULL, free_strings);
   }
   return (gpointer) (var + 1);
}

GNOME_VFS_Slave_DirectoryFilter *
GNOME_VFS_Slave_DirectoryFilter__alloc(void)
{
   GNOME_VFS_Slave_DirectoryFilter *retval;

   retval =
      ORBit_alloc(sizeof(GNOME_VFS_Slave_DirectoryFilter),
		  (ORBit_free_childvals)
		  GNOME_VFS_Slave_DirectoryFilter__free, GUINT_TO_POINTER(1));
   memset(&(retval->pattern), '\0', sizeof(retval->pattern));
   return retval;
}

#if ( (ORBIT_IMPL_CORBA_sequence_GNOME_VFS_Slave_DirectorySortRule_0 == 'g') \
&& (ORBIT_IMPL_CORBA_sequence_GNOME_VFS_Slave_DirectorySortRule_1 == 'n') \
&& (ORBIT_IMPL_CORBA_sequence_GNOME_VFS_Slave_DirectorySortRule_2 == 'o') \
&& (ORBIT_IMPL_CORBA_sequence_GNOME_VFS_Slave_DirectorySortRule_3 == 'm') \
&& (ORBIT_IMPL_CORBA_sequence_GNOME_VFS_Slave_DirectorySortRule_4 == 'e') \
&& (ORBIT_IMPL_CORBA_sequence_GNOME_VFS_Slave_DirectorySortRule_5 == '_') \
&& (ORBIT_IMPL_CORBA_sequence_GNOME_VFS_Slave_DirectorySortRule_6 == 'v') \
&& (ORBIT_IMPL_CORBA_sequence_GNOME_VFS_Slave_DirectorySortRule_7 == 'f') \
&& (ORBIT_IMPL_CORBA_sequence_GNOME_VFS_Slave_DirectorySortRule_8 == 's') \
&& (ORBIT_IMPL_CORBA_sequence_GNOME_VFS_Slave_DirectorySortRule_9 == '_') \
&& (ORBIT_IMPL_CORBA_sequence_GNOME_VFS_Slave_DirectorySortRule_10 == 's') \
&& (ORBIT_IMPL_CORBA_sequence_GNOME_VFS_Slave_DirectorySortRule_11 == 'l') \
&& (ORBIT_IMPL_CORBA_sequence_GNOME_VFS_Slave_DirectorySortRule_12 == 'a') \
&& (ORBIT_IMPL_CORBA_sequence_GNOME_VFS_Slave_DirectorySortRule_13 == 'v') \
&& (ORBIT_IMPL_CORBA_sequence_GNOME_VFS_Slave_DirectorySortRule_14 == 'e') \
) && !defined(ORBIT_DEF_CORBA_sequence_GNOME_VFS_Slave_DirectorySortRule)
#define ORBIT_DEF_CORBA_sequence_GNOME_VFS_Slave_DirectorySortRule 1

gpointer
CORBA_sequence_GNOME_VFS_Slave_DirectorySortRule__free(gpointer mem,
						       gpointer dat,
						       CORBA_boolean
						       free_strings)
{
   CORBA_sequence_GNOME_VFS_Slave_DirectorySortRule *val = mem;

   if (val->_release)
      ORBit_free(val->_buffer, free_strings);
   return (gpointer) (val + 1);
}

CORBA_sequence_GNOME_VFS_Slave_DirectorySortRule *
CORBA_sequence_GNOME_VFS_Slave_DirectorySortRule__alloc(void)
{
   CORBA_sequence_GNOME_VFS_Slave_DirectorySortRule *retval;

   retval =
      ORBit_alloc(sizeof(CORBA_sequence_GNOME_VFS_Slave_DirectorySortRule),
		  (ORBit_free_childvals)
		  CORBA_sequence_GNOME_VFS_Slave_DirectorySortRule__free,
		  GUINT_TO_POINTER(1));
   retval->_maximum = 0;
   retval->_length = 0;
   retval->_buffer = NULL;
   retval->_release = CORBA_FALSE;
   return retval;
}

GNOME_VFS_Slave_DirectorySortRule *
CORBA_sequence_GNOME_VFS_Slave_DirectorySortRule_allocbuf(CORBA_unsigned_long
							  len)
{
   GNOME_VFS_Slave_DirectorySortRule *retval =
      ORBit_alloc(sizeof(GNOME_VFS_Slave_DirectorySortRule) * len,
		  (ORBit_free_childvals) NULL, GUINT_TO_POINTER(len));

   return retval;
}
#endif

gpointer
GNOME_VFS_Slave_DirectorySortRuleList__free(gpointer mem, gpointer dat,
					    CORBA_boolean free_strings)
{
   return CORBA_sequence_GNOME_VFS_Slave_DirectorySortRule__free(mem, dat,
								 free_strings);
}

GNOME_VFS_Slave_DirectorySortRuleList *
GNOME_VFS_Slave_DirectorySortRuleList__alloc(void)
{
   return CORBA_sequence_GNOME_VFS_Slave_DirectorySortRule__alloc();
}

#if ( (ORBIT_IMPL_CORBA_sequence_CORBA_string_0 == 'g') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_string_1 == 'n') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_string_2 == 'o') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_string_3 == 'm') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_string_4 == 'e') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_string_5 == '_') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_string_6 == 'v') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_string_7 == 'f') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_string_8 == 's') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_string_9 == '_') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_string_10 == 's') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_string_11 == 'l') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_string_12 == 'a') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_string_13 == 'v') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_string_14 == 'e') \
) && !defined(ORBIT_DEF_CORBA_sequence_CORBA_string)
#define ORBIT_DEF_CORBA_sequence_CORBA_string 1

gpointer
CORBA_sequence_CORBA_string__free(gpointer mem, gpointer dat,
				  CORBA_boolean free_strings)
{
   CORBA_sequence_CORBA_string *val = mem;

   if (val->_release)
      ORBit_free(val->_buffer, free_strings);
   return (gpointer) (val + 1);
}

CORBA_sequence_CORBA_string *
CORBA_sequence_CORBA_string__alloc(void)
{
   CORBA_sequence_CORBA_string *retval;

   retval =
      ORBit_alloc(sizeof(CORBA_sequence_CORBA_string),
		  (ORBit_free_childvals) CORBA_sequence_CORBA_string__free,
		  GUINT_TO_POINTER(1));
   retval->_maximum = 0;
   retval->_length = 0;
   retval->_buffer = NULL;
   retval->_release = CORBA_FALSE;
   return retval;
}

CORBA_char **
CORBA_sequence_CORBA_string_allocbuf(CORBA_unsigned_long len)
{
   CORBA_char **retval =
      ORBit_alloc(sizeof(CORBA_char *) * len,
		  (ORBit_free_childvals) CORBA_string__free,

		  GUINT_TO_POINTER(len));
   memset(retval, '\0', sizeof(CORBA_char *) * len);
   return retval;
}
#endif

gpointer
GNOME_VFS_Slave_FileNameList__free(gpointer mem, gpointer dat,
				   CORBA_boolean free_strings)
{
   return CORBA_sequence_CORBA_string__free(mem, dat, free_strings);
}

GNOME_VFS_Slave_FileNameList *
GNOME_VFS_Slave_FileNameList__alloc(void)
{
   return CORBA_sequence_CORBA_string__alloc();
}

#if ( (ORBIT_IMPL_CORBA_sequence_CORBA_string_0 == 'g') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_string_1 == 'n') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_string_2 == 'o') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_string_3 == 'm') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_string_4 == 'e') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_string_5 == '_') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_string_6 == 'v') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_string_7 == 'f') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_string_8 == 's') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_string_9 == '_') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_string_10 == 's') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_string_11 == 'l') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_string_12 == 'a') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_string_13 == 'v') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_string_14 == 'e') \
) && !defined(ORBIT_DEF_CORBA_sequence_CORBA_string)
#define ORBIT_DEF_CORBA_sequence_CORBA_string 1

gpointer
CORBA_sequence_CORBA_string__free(gpointer mem, gpointer dat,
				  CORBA_boolean free_strings)
{
   CORBA_sequence_CORBA_string *val = mem;

   if (val->_release)
      ORBit_free(val->_buffer, free_strings);
   return (gpointer) (val + 1);
}

CORBA_sequence_CORBA_string *
CORBA_sequence_CORBA_string__alloc(void)
{
   CORBA_sequence_CORBA_string *retval;

   retval =
      ORBit_alloc(sizeof(CORBA_sequence_CORBA_string),
		  (ORBit_free_childvals) CORBA_sequence_CORBA_string__free,
		  GUINT_TO_POINTER(1));
   retval->_maximum = 0;
   retval->_length = 0;
   retval->_buffer = NULL;
   retval->_release = CORBA_FALSE;
   return retval;
}

CORBA_char **
CORBA_sequence_CORBA_string_allocbuf(CORBA_unsigned_long len)
{
   CORBA_char **retval =
      ORBit_alloc(sizeof(CORBA_char *) * len,
		  (ORBit_free_childvals) CORBA_string__free,

		  GUINT_TO_POINTER(len));
   memset(retval, '\0', sizeof(CORBA_char *) * len);
   return retval;
}
#endif

gpointer
GNOME_VFS_Slave_URIList__free(gpointer mem, gpointer dat,
			      CORBA_boolean free_strings)
{
   return CORBA_sequence_CORBA_string__free(mem, dat, free_strings);
}

GNOME_VFS_Slave_URIList *
GNOME_VFS_Slave_URIList__alloc(void)
{
   return CORBA_sequence_CORBA_string__alloc();
}

#if ( (ORBIT_IMPL_CORBA_sequence_CORBA_octet_0 == 'g') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_octet_1 == 'n') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_octet_2 == 'o') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_octet_3 == 'm') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_octet_4 == 'e') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_octet_5 == '_') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_octet_6 == 'v') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_octet_7 == 'f') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_octet_8 == 's') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_octet_9 == '_') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_octet_10 == 's') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_octet_11 == 'l') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_octet_12 == 'a') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_octet_13 == 'v') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_octet_14 == 'e') \
) && !defined(ORBIT_DEF_CORBA_sequence_CORBA_octet)
#define ORBIT_DEF_CORBA_sequence_CORBA_octet 1

gpointer
CORBA_sequence_CORBA_octet__free(gpointer mem, gpointer dat,
				 CORBA_boolean free_strings)
{
   CORBA_sequence_CORBA_octet *val = mem;

   if (val->_release)
      ORBit_free(val->_buffer, free_strings);
   return (gpointer) (val + 1);
}

CORBA_sequence_CORBA_octet *
CORBA_sequence_CORBA_octet__alloc(void)
{
   CORBA_sequence_CORBA_octet *retval;

   retval =
      ORBit_alloc(sizeof(CORBA_sequence_CORBA_octet),
		  (ORBit_free_childvals) CORBA_sequence_CORBA_octet__free,
		  GUINT_TO_POINTER(1));
   retval->_maximum = 0;
   retval->_length = 0;
   retval->_buffer = NULL;
   retval->_release = CORBA_FALSE;
   return retval;
}

CORBA_octet *
CORBA_sequence_CORBA_octet_allocbuf(CORBA_unsigned_long len)
{
   CORBA_octet *retval =
      ORBit_alloc(sizeof(CORBA_octet) * len, (ORBit_free_childvals) NULL,
		  GUINT_TO_POINTER(len));

   return retval;
}
#endif

gpointer
GNOME_VFS_Slave_GetFileInfoResult__free(gpointer mem, gpointer dat,
					CORBA_boolean free_strings)
{
   GNOME_VFS_Slave_GetFileInfoResult *var = mem;

   if (free_strings) {
      CORBA_string__free(&(var->uri), NULL, free_strings);
   }
   {
      GNOME_VFS_Slave_FileInfo__free(&(var->file_info), NULL, free_strings);
   }
   return (gpointer) (var + 1);
}

GNOME_VFS_Slave_GetFileInfoResult *
GNOME_VFS_Slave_GetFileInfoResult__alloc(void)
{
   GNOME_VFS_Slave_GetFileInfoResult *retval;

   retval =
      ORBit_alloc(sizeof(GNOME_VFS_Slave_GetFileInfoResult),
		  (ORBit_free_childvals)
		  GNOME_VFS_Slave_GetFileInfoResult__free,
		  GUINT_TO_POINTER(1));
   memset(&(retval->uri), '\0', sizeof(retval->uri));
   memset(&(retval->file_info), '\0', sizeof(retval->file_info));
   return retval;
}

#if ( (ORBIT_IMPL_CORBA_sequence_GNOME_VFS_Slave_GetFileInfoResult_0 == 'g') \
&& (ORBIT_IMPL_CORBA_sequence_GNOME_VFS_Slave_GetFileInfoResult_1 == 'n') \
&& (ORBIT_IMPL_CORBA_sequence_GNOME_VFS_Slave_GetFileInfoResult_2 == 'o') \
&& (ORBIT_IMPL_CORBA_sequence_GNOME_VFS_Slave_GetFileInfoResult_3 == 'm') \
&& (ORBIT_IMPL_CORBA_sequence_GNOME_VFS_Slave_GetFileInfoResult_4 == 'e') \
&& (ORBIT_IMPL_CORBA_sequence_GNOME_VFS_Slave_GetFileInfoResult_5 == '_') \
&& (ORBIT_IMPL_CORBA_sequence_GNOME_VFS_Slave_GetFileInfoResult_6 == 'v') \
&& (ORBIT_IMPL_CORBA_sequence_GNOME_VFS_Slave_GetFileInfoResult_7 == 'f') \
&& (ORBIT_IMPL_CORBA_sequence_GNOME_VFS_Slave_GetFileInfoResult_8 == 's') \
&& (ORBIT_IMPL_CORBA_sequence_GNOME_VFS_Slave_GetFileInfoResult_9 == '_') \
&& (ORBIT_IMPL_CORBA_sequence_GNOME_VFS_Slave_GetFileInfoResult_10 == 's') \
&& (ORBIT_IMPL_CORBA_sequence_GNOME_VFS_Slave_GetFileInfoResult_11 == 'l') \
&& (ORBIT_IMPL_CORBA_sequence_GNOME_VFS_Slave_GetFileInfoResult_12 == 'a') \
&& (ORBIT_IMPL_CORBA_sequence_GNOME_VFS_Slave_GetFileInfoResult_13 == 'v') \
&& (ORBIT_IMPL_CORBA_sequence_GNOME_VFS_Slave_GetFileInfoResult_14 == 'e') \
) && !defined(ORBIT_DEF_CORBA_sequence_GNOME_VFS_Slave_GetFileInfoResult)
#define ORBIT_DEF_CORBA_sequence_GNOME_VFS_Slave_GetFileInfoResult 1

gpointer
CORBA_sequence_GNOME_VFS_Slave_GetFileInfoResult__free(gpointer mem,
						       gpointer dat,
						       CORBA_boolean
						       free_strings)
{
   CORBA_sequence_GNOME_VFS_Slave_GetFileInfoResult *val = mem;

   if (val->_release)
      ORBit_free(val->_buffer, free_strings);
   return (gpointer) (val + 1);
}

CORBA_sequence_GNOME_VFS_Slave_GetFileInfoResult *
CORBA_sequence_GNOME_VFS_Slave_GetFileInfoResult__alloc(void)
{
   CORBA_sequence_GNOME_VFS_Slave_GetFileInfoResult *retval;

   retval =
      ORBit_alloc(sizeof(CORBA_sequence_GNOME_VFS_Slave_GetFileInfoResult),
		  (ORBit_free_childvals)
		  CORBA_sequence_GNOME_VFS_Slave_GetFileInfoResult__free,
		  GUINT_TO_POINTER(1));
   retval->_maximum = 0;
   retval->_length = 0;
   retval->_buffer = NULL;
   retval->_release = CORBA_FALSE;
   return retval;
}

GNOME_VFS_Slave_GetFileInfoResult *
CORBA_sequence_GNOME_VFS_Slave_GetFileInfoResult_allocbuf(CORBA_unsigned_long
							  len)
{
   GNOME_VFS_Slave_GetFileInfoResult *retval =
      ORBit_alloc(sizeof(GNOME_VFS_Slave_GetFileInfoResult) * len,
		  (ORBit_free_childvals)
		  GNOME_VFS_Slave_GetFileInfoResult__free,

		  GUINT_TO_POINTER(len));
   memset(retval, '\0', sizeof(GNOME_VFS_Slave_GetFileInfoResult) * len);
   return retval;
}
#endif

gpointer
GNOME_VFS_Slave_GetFileInfoResultList__free(gpointer mem, gpointer dat,
					    CORBA_boolean free_strings)
{
   return CORBA_sequence_GNOME_VFS_Slave_GetFileInfoResult__free(mem, dat,
								 free_strings);
}

GNOME_VFS_Slave_GetFileInfoResultList *
GNOME_VFS_Slave_GetFileInfoResultList__alloc(void)
{
   return CORBA_sequence_GNOME_VFS_Slave_GetFileInfoResult__alloc();
}

CORBA_unsigned_long GNOME_VFS_Slave_Request__classid = 0;
CORBA_unsigned_long GNOME_VFS_Slave_FileHandle__classid = 0;
CORBA_unsigned_long GNOME_VFS_Slave_Notify__classid = 0;
