#!/bin/sh
# postinst script for debathena-cupsys-config
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <postinst> `abort-remove'
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package


#DEBHELPER#

case "$1" in
    configure)
	# Handle Debian package name change from cupsys to cups.
	[ -e /etc/init.d/cups ] && rcname=cups || rcname=cupsys
	if hash invoke-rc.d; then
	    invoke-rc.d $rcname restart
	else
	    /etc/init.d/$rcname restart
	fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac
