/*
 * This file was generated by orbit-idl - DO NOT EDIT!
 */

#include <string.h>
#include "Spell.h"

void
_ORBIT_GNOME_Spell_Dictionary_Error_marshal(GIOPSendBuffer *
					    _ORBIT_send_buffer,
					    CORBA_Environment * ev)
{
   register CORBA_unsigned_long _ORBIT_tmpvar_0;
   CORBA_unsigned_long _ORBIT_tmpvar_1;
   GNOME_Spell_Dictionary_Error *_ORBIT_exdata = ev->_params;

   _ORBIT_tmpvar_1 = strlen((*_ORBIT_exdata).error) + 1;
   giop_message_buffer_do_alignment(GIOP_MESSAGE_BUFFER(_ORBIT_send_buffer),
				    4);
   giop_send_buffer_append_mem_indirect(GIOP_SEND_BUFFER(_ORBIT_send_buffer),
					&(_ORBIT_tmpvar_1),
					sizeof(_ORBIT_tmpvar_1));
   giop_message_buffer_append_mem(GIOP_MESSAGE_BUFFER(_ORBIT_send_buffer),
				  ((*_ORBIT_exdata).error),
				  sizeof((*_ORBIT_exdata).
					 error[_ORBIT_tmpvar_0]) *
				  _ORBIT_tmpvar_1);
}

void
_ORBIT_skel_GNOME_Spell_Dictionary_getLanguages(POA_GNOME_Spell_Dictionary *
						_ORBIT_servant,
						GIOPRecvBuffer *
						_ORBIT_recv_buffer,
						CORBA_Environment * ev,
						GNOME_Spell_LanguageSeq *
						(*_impl_getLanguages)
						(PortableServer_Servant
						 _servant,
						 CORBA_Environment * ev))
{
   GNOME_Spell_LanguageSeq *_ORBIT_retval;

   _ORBIT_retval = _impl_getLanguages(_ORBIT_servant, ev);
   {				/* marshalling */
      register GIOPSendBuffer *_ORBIT_send_buffer;

      _ORBIT_send_buffer =
	 giop_send_reply_buffer_use(GIOP_MESSAGE_BUFFER(_ORBIT_recv_buffer)->
				    connection, NULL,
				    _ORBIT_recv_buffer->message.u.request.
				    request_id, ev->_major);
      if (_ORBIT_send_buffer) {
	 if (ev->_major == CORBA_NO_EXCEPTION) {
	    register CORBA_unsigned_long _ORBIT_tmpvar_0;
	    register CORBA_unsigned_long _ORBIT_tmpvar_1;
	    CORBA_unsigned_long _ORBIT_tmpvar_2;
	    register CORBA_unsigned_long _ORBIT_tmpvar_3;
	    CORBA_unsigned_long _ORBIT_tmpvar_4;

	    giop_message_buffer_do_alignment(GIOP_MESSAGE_BUFFER
					     (_ORBIT_send_buffer), 4);
	    {
	       guchar *_ORBIT_t;

	       _ORBIT_t = alloca(sizeof((*_ORBIT_retval)._length));
	       memcpy(_ORBIT_t, &((*_ORBIT_retval)._length),
		      sizeof((*_ORBIT_retval)._length));
	       giop_message_buffer_append_mem(GIOP_MESSAGE_BUFFER
					      (_ORBIT_send_buffer),
					      (_ORBIT_t),
					      sizeof((*_ORBIT_retval).
						     _length));
	    }
	    for (_ORBIT_tmpvar_0 = 0;
		 _ORBIT_tmpvar_0 < (*_ORBIT_retval)._length;
		 _ORBIT_tmpvar_0++) {
	       _ORBIT_tmpvar_2 =
		  strlen((*_ORBIT_retval)._buffer[_ORBIT_tmpvar_0].name) + 1;
	       giop_message_buffer_do_alignment(GIOP_MESSAGE_BUFFER
						(_ORBIT_send_buffer), 4);
	       {
		  guchar *_ORBIT_t;

		  _ORBIT_t = alloca(sizeof(_ORBIT_tmpvar_2));
		  memcpy(_ORBIT_t, &(_ORBIT_tmpvar_2),
			 sizeof(_ORBIT_tmpvar_2));
		  giop_message_buffer_append_mem(GIOP_MESSAGE_BUFFER
						 (_ORBIT_send_buffer),
						 (_ORBIT_t),
						 sizeof(_ORBIT_tmpvar_2));
	       }
	       {
		  guchar *_ORBIT_t;

		  _ORBIT_t =
		     alloca(sizeof
			    ((*_ORBIT_retval)._buffer[_ORBIT_tmpvar_0].
			     name[_ORBIT_tmpvar_1]) * _ORBIT_tmpvar_2);
		  memcpy(_ORBIT_t,
			 ((*_ORBIT_retval)._buffer[_ORBIT_tmpvar_0].name),
			 sizeof((*_ORBIT_retval)._buffer[_ORBIT_tmpvar_0].
				name[_ORBIT_tmpvar_1]) * _ORBIT_tmpvar_2);
		  giop_message_buffer_append_mem(GIOP_MESSAGE_BUFFER
						 (_ORBIT_send_buffer),
						 (_ORBIT_t),
						 sizeof((*_ORBIT_retval).
							_buffer
							[_ORBIT_tmpvar_0].
							name[_ORBIT_tmpvar_1])
						 * _ORBIT_tmpvar_2);
	       }
	       _ORBIT_tmpvar_4 =
		  strlen((*_ORBIT_retval)._buffer[_ORBIT_tmpvar_0].abrev) + 1;
	       giop_message_buffer_do_alignment(GIOP_MESSAGE_BUFFER
						(_ORBIT_send_buffer), 4);
	       {
		  guchar *_ORBIT_t;

		  _ORBIT_t = alloca(sizeof(_ORBIT_tmpvar_4));
		  memcpy(_ORBIT_t, &(_ORBIT_tmpvar_4),
			 sizeof(_ORBIT_tmpvar_4));
		  giop_message_buffer_append_mem(GIOP_MESSAGE_BUFFER
						 (_ORBIT_send_buffer),
						 (_ORBIT_t),
						 sizeof(_ORBIT_tmpvar_4));
	       }
	       {
		  guchar *_ORBIT_t;

		  _ORBIT_t =
		     alloca(sizeof
			    ((*_ORBIT_retval)._buffer[_ORBIT_tmpvar_0].
			     abrev[_ORBIT_tmpvar_3]) * _ORBIT_tmpvar_4);
		  memcpy(_ORBIT_t,
			 ((*_ORBIT_retval)._buffer[_ORBIT_tmpvar_0].abrev),
			 sizeof((*_ORBIT_retval)._buffer[_ORBIT_tmpvar_0].
				abrev[_ORBIT_tmpvar_3]) * _ORBIT_tmpvar_4);
		  giop_message_buffer_append_mem(GIOP_MESSAGE_BUFFER
						 (_ORBIT_send_buffer),
						 (_ORBIT_t),
						 sizeof((*_ORBIT_retval).
							_buffer
							[_ORBIT_tmpvar_0].
							abrev
							[_ORBIT_tmpvar_3]) *
						 _ORBIT_tmpvar_4);
	       }
	    }

	 } else
	    ORBit_send_system_exception(_ORBIT_send_buffer, ev);
	 giop_send_buffer_write(_ORBIT_send_buffer);
	 giop_send_buffer_unuse(_ORBIT_send_buffer);
      }
      if (ev->_major == CORBA_NO_EXCEPTION)
	 CORBA_free(_ORBIT_retval);
   }
}
void
_ORBIT_skel_GNOME_Spell_Dictionary_setLanguage(POA_GNOME_Spell_Dictionary *
					       _ORBIT_servant,
					       GIOPRecvBuffer *
					       _ORBIT_recv_buffer,
					       CORBA_Environment * ev,
					       void (*_impl_setLanguage)
					       (PortableServer_Servant
						_servant,
						const CORBA_char * language,
						CORBA_Environment * ev))
{
   CORBA_char *language;

   {				/* demarshalling */
      guchar *_ORBIT_curptr;
      register CORBA_unsigned_long _ORBIT_tmpvar_2;
      CORBA_unsigned_long _ORBIT_tmpvar_3;

      _ORBIT_curptr = GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur;
      if (giop_msg_conversion_needed(GIOP_MESSAGE_BUFFER(_ORBIT_recv_buffer))) {
	 _ORBIT_curptr = ALIGN_ADDRESS(_ORBIT_curptr, 4);
	 (*((guint32 *) & (_ORBIT_tmpvar_3))) =
	    GUINT32_SWAP_LE_BE(*((guint32 *) _ORBIT_curptr));
	 _ORBIT_curptr += 4;
	 language = (void *) _ORBIT_curptr;
	 _ORBIT_curptr += sizeof(language[_ORBIT_tmpvar_2]) * _ORBIT_tmpvar_3;
      } else {
	 _ORBIT_curptr = ALIGN_ADDRESS(_ORBIT_curptr, 4);
	 _ORBIT_tmpvar_3 = *((CORBA_unsigned_long *) _ORBIT_curptr);
	 _ORBIT_curptr += 4;
	 language = (void *) _ORBIT_curptr;
	 _ORBIT_curptr += sizeof(language[_ORBIT_tmpvar_2]) * _ORBIT_tmpvar_3;
      }
   }
   _impl_setLanguage(_ORBIT_servant, language, ev);
   {				/* marshalling */
      register GIOPSendBuffer *_ORBIT_send_buffer;

      _ORBIT_send_buffer =
	 giop_send_reply_buffer_use(GIOP_MESSAGE_BUFFER(_ORBIT_recv_buffer)->
				    connection, NULL,
				    _ORBIT_recv_buffer->message.u.request.
				    request_id, ev->_major);
      if (_ORBIT_send_buffer) {
	 if (ev->_major == CORBA_NO_EXCEPTION) {
	 } else
	    ORBit_send_system_exception(_ORBIT_send_buffer, ev);
	 giop_send_buffer_write(_ORBIT_send_buffer);
	 giop_send_buffer_unuse(_ORBIT_send_buffer);
      }
   }
}
void
_ORBIT_skel_GNOME_Spell_Dictionary_checkWord(POA_GNOME_Spell_Dictionary *
					     _ORBIT_servant,
					     GIOPRecvBuffer *
					     _ORBIT_recv_buffer,
					     CORBA_Environment * ev,
					     CORBA_boolean(*_impl_checkWord)
					     (PortableServer_Servant _servant,
					      const CORBA_char * word,
					      CORBA_Environment * ev))
{
   CORBA_boolean _ORBIT_retval;
   CORBA_char *word;

   {				/* demarshalling */
      guchar *_ORBIT_curptr;
      register CORBA_unsigned_long _ORBIT_tmpvar_2;
      CORBA_unsigned_long _ORBIT_tmpvar_3;

      _ORBIT_curptr = GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur;
      if (giop_msg_conversion_needed(GIOP_MESSAGE_BUFFER(_ORBIT_recv_buffer))) {
	 _ORBIT_curptr = ALIGN_ADDRESS(_ORBIT_curptr, 4);
	 (*((guint32 *) & (_ORBIT_tmpvar_3))) =
	    GUINT32_SWAP_LE_BE(*((guint32 *) _ORBIT_curptr));
	 _ORBIT_curptr += 4;
	 word = (void *) _ORBIT_curptr;
	 _ORBIT_curptr += sizeof(word[_ORBIT_tmpvar_2]) * _ORBIT_tmpvar_3;
      } else {
	 _ORBIT_curptr = ALIGN_ADDRESS(_ORBIT_curptr, 4);
	 _ORBIT_tmpvar_3 = *((CORBA_unsigned_long *) _ORBIT_curptr);
	 _ORBIT_curptr += 4;
	 word = (void *) _ORBIT_curptr;
	 _ORBIT_curptr += sizeof(word[_ORBIT_tmpvar_2]) * _ORBIT_tmpvar_3;
      }
   }
   _ORBIT_retval = _impl_checkWord(_ORBIT_servant, word, ev);
   {				/* marshalling */
      register GIOPSendBuffer *_ORBIT_send_buffer;

      _ORBIT_send_buffer =
	 giop_send_reply_buffer_use(GIOP_MESSAGE_BUFFER(_ORBIT_recv_buffer)->
				    connection, NULL,
				    _ORBIT_recv_buffer->message.u.request.
				    request_id, ev->_major);
      if (_ORBIT_send_buffer) {
	 if (ev->_major == CORBA_NO_EXCEPTION) {
	    {
	       guchar *_ORBIT_t;

	       _ORBIT_t = alloca(sizeof(_ORBIT_retval));
	       memcpy(_ORBIT_t, &(_ORBIT_retval), sizeof(_ORBIT_retval));
	       giop_message_buffer_append_mem(GIOP_MESSAGE_BUFFER
					      (_ORBIT_send_buffer),
					      (_ORBIT_t),
					      sizeof(_ORBIT_retval));
	    }
	 } else if (ev->_major == CORBA_USER_EXCEPTION) {
	    static const ORBit_exception_marshal_info _ORBIT_user_exceptions[]
	       =
	       { {(const CORBA_TypeCode)
		  &TC_GNOME_Spell_Dictionary_Error_struct,
		  (gpointer) _ORBIT_GNOME_Spell_Dictionary_Error_marshal},
	       {CORBA_OBJECT_NIL, NULL} };
	    ORBit_send_user_exception(_ORBIT_send_buffer, ev,
				      _ORBIT_user_exceptions);
	 } else
	    ORBit_send_system_exception(_ORBIT_send_buffer, ev);
	 giop_send_buffer_write(_ORBIT_send_buffer);
	 giop_send_buffer_unuse(_ORBIT_send_buffer);
      }
   }
}
void
_ORBIT_skel_GNOME_Spell_Dictionary_getSuggestions(POA_GNOME_Spell_Dictionary *
						  _ORBIT_servant,
						  GIOPRecvBuffer *
						  _ORBIT_recv_buffer,
						  CORBA_Environment * ev,
						  GNOME_Spell_StringSeq *
						  (*_impl_getSuggestions)
						  (PortableServer_Servant
						   _servant,
						   const CORBA_char * word,
						   CORBA_Environment * ev))
{
   GNOME_Spell_StringSeq *_ORBIT_retval;
   CORBA_char *word;

   {				/* demarshalling */
      guchar *_ORBIT_curptr;
      register CORBA_unsigned_long _ORBIT_tmpvar_8;
      CORBA_unsigned_long _ORBIT_tmpvar_9;

      _ORBIT_curptr = GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur;
      if (giop_msg_conversion_needed(GIOP_MESSAGE_BUFFER(_ORBIT_recv_buffer))) {
	 _ORBIT_curptr = ALIGN_ADDRESS(_ORBIT_curptr, 4);
	 (*((guint32 *) & (_ORBIT_tmpvar_9))) =
	    GUINT32_SWAP_LE_BE(*((guint32 *) _ORBIT_curptr));
	 _ORBIT_curptr += 4;
	 word = (void *) _ORBIT_curptr;
	 _ORBIT_curptr += sizeof(word[_ORBIT_tmpvar_8]) * _ORBIT_tmpvar_9;
      } else {
	 _ORBIT_curptr = ALIGN_ADDRESS(_ORBIT_curptr, 4);
	 _ORBIT_tmpvar_9 = *((CORBA_unsigned_long *) _ORBIT_curptr);
	 _ORBIT_curptr += 4;
	 word = (void *) _ORBIT_curptr;
	 _ORBIT_curptr += sizeof(word[_ORBIT_tmpvar_8]) * _ORBIT_tmpvar_9;
      }
   }
   _ORBIT_retval = _impl_getSuggestions(_ORBIT_servant, word, ev);
   {				/* marshalling */
      register GIOPSendBuffer *_ORBIT_send_buffer;

      _ORBIT_send_buffer =
	 giop_send_reply_buffer_use(GIOP_MESSAGE_BUFFER(_ORBIT_recv_buffer)->
				    connection, NULL,
				    _ORBIT_recv_buffer->message.u.request.
				    request_id, ev->_major);
      if (_ORBIT_send_buffer) {
	 if (ev->_major == CORBA_NO_EXCEPTION) {
	    register CORBA_unsigned_long _ORBIT_tmpvar_2;
	    register CORBA_unsigned_long _ORBIT_tmpvar_3;
	    CORBA_unsigned_long _ORBIT_tmpvar_4;

	    giop_message_buffer_do_alignment(GIOP_MESSAGE_BUFFER
					     (_ORBIT_send_buffer), 4);
	    {
	       guchar *_ORBIT_t;

	       _ORBIT_t = alloca(sizeof((*_ORBIT_retval)._length));
	       memcpy(_ORBIT_t, &((*_ORBIT_retval)._length),
		      sizeof((*_ORBIT_retval)._length));
	       giop_message_buffer_append_mem(GIOP_MESSAGE_BUFFER
					      (_ORBIT_send_buffer),
					      (_ORBIT_t),
					      sizeof((*_ORBIT_retval).
						     _length));
	    }
	    for (_ORBIT_tmpvar_2 = 0;
		 _ORBIT_tmpvar_2 < (*_ORBIT_retval)._length;
		 _ORBIT_tmpvar_2++) {
	       _ORBIT_tmpvar_4 =
		  strlen((*_ORBIT_retval)._buffer[_ORBIT_tmpvar_2]) + 1;
	       giop_message_buffer_do_alignment(GIOP_MESSAGE_BUFFER
						(_ORBIT_send_buffer), 4);
	       {
		  guchar *_ORBIT_t;

		  _ORBIT_t = alloca(sizeof(_ORBIT_tmpvar_4));
		  memcpy(_ORBIT_t, &(_ORBIT_tmpvar_4),
			 sizeof(_ORBIT_tmpvar_4));
		  giop_message_buffer_append_mem(GIOP_MESSAGE_BUFFER
						 (_ORBIT_send_buffer),
						 (_ORBIT_t),
						 sizeof(_ORBIT_tmpvar_4));
	       }
	       {
		  guchar *_ORBIT_t;

		  _ORBIT_t =
		     alloca(sizeof
			    ((*_ORBIT_retval).
			     _buffer[_ORBIT_tmpvar_2][_ORBIT_tmpvar_3]) *
			    _ORBIT_tmpvar_4);
		  memcpy(_ORBIT_t,
			 ((*_ORBIT_retval)._buffer[_ORBIT_tmpvar_2]),
			 sizeof((*_ORBIT_retval).
				_buffer[_ORBIT_tmpvar_2][_ORBIT_tmpvar_3]) *
			 _ORBIT_tmpvar_4);
		  giop_message_buffer_append_mem(GIOP_MESSAGE_BUFFER
						 (_ORBIT_send_buffer),
						 (_ORBIT_t),
						 sizeof((*_ORBIT_retval).
							_buffer
							[_ORBIT_tmpvar_2]
							[_ORBIT_tmpvar_3]) *
						 _ORBIT_tmpvar_4);
	       }
	    }

	 } else if (ev->_major == CORBA_USER_EXCEPTION) {
	    static const ORBit_exception_marshal_info _ORBIT_user_exceptions[]
	       =
	       { {(const CORBA_TypeCode)
		  &TC_GNOME_Spell_Dictionary_Error_struct,
		  (gpointer) _ORBIT_GNOME_Spell_Dictionary_Error_marshal},
	       {CORBA_OBJECT_NIL, NULL} };
	    ORBit_send_user_exception(_ORBIT_send_buffer, ev,
				      _ORBIT_user_exceptions);
	 } else
	    ORBit_send_system_exception(_ORBIT_send_buffer, ev);
	 giop_send_buffer_write(_ORBIT_send_buffer);
	 giop_send_buffer_unuse(_ORBIT_send_buffer);
      }
      if (ev->_major == CORBA_NO_EXCEPTION)
	 CORBA_free(_ORBIT_retval);
   }
}
void
_ORBIT_skel_GNOME_Spell_Dictionary_addWordToSession(POA_GNOME_Spell_Dictionary
						    * _ORBIT_servant,
						    GIOPRecvBuffer *
						    _ORBIT_recv_buffer,
						    CORBA_Environment * ev,
						    void
						    (*_impl_addWordToSession)
						    (PortableServer_Servant
						     _servant,
						     const CORBA_char * word,
						     CORBA_Environment * ev))
{
   CORBA_char *word;

   {				/* demarshalling */
      guchar *_ORBIT_curptr;
      register CORBA_unsigned_long _ORBIT_tmpvar_2;
      CORBA_unsigned_long _ORBIT_tmpvar_3;

      _ORBIT_curptr = GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur;
      if (giop_msg_conversion_needed(GIOP_MESSAGE_BUFFER(_ORBIT_recv_buffer))) {
	 _ORBIT_curptr = ALIGN_ADDRESS(_ORBIT_curptr, 4);
	 (*((guint32 *) & (_ORBIT_tmpvar_3))) =
	    GUINT32_SWAP_LE_BE(*((guint32 *) _ORBIT_curptr));
	 _ORBIT_curptr += 4;
	 word = (void *) _ORBIT_curptr;
	 _ORBIT_curptr += sizeof(word[_ORBIT_tmpvar_2]) * _ORBIT_tmpvar_3;
      } else {
	 _ORBIT_curptr = ALIGN_ADDRESS(_ORBIT_curptr, 4);
	 _ORBIT_tmpvar_3 = *((CORBA_unsigned_long *) _ORBIT_curptr);
	 _ORBIT_curptr += 4;
	 word = (void *) _ORBIT_curptr;
	 _ORBIT_curptr += sizeof(word[_ORBIT_tmpvar_2]) * _ORBIT_tmpvar_3;
      }
   }
   _impl_addWordToSession(_ORBIT_servant, word, ev);
   {				/* marshalling */
      register GIOPSendBuffer *_ORBIT_send_buffer;

      _ORBIT_send_buffer =
	 giop_send_reply_buffer_use(GIOP_MESSAGE_BUFFER(_ORBIT_recv_buffer)->
				    connection, NULL,
				    _ORBIT_recv_buffer->message.u.request.
				    request_id, ev->_major);
      if (_ORBIT_send_buffer) {
	 if (ev->_major == CORBA_NO_EXCEPTION) {
	 } else if (ev->_major == CORBA_USER_EXCEPTION) {
	    static const ORBit_exception_marshal_info _ORBIT_user_exceptions[]
	       =
	       { {(const CORBA_TypeCode)
		  &TC_GNOME_Spell_Dictionary_Error_struct,
		  (gpointer) _ORBIT_GNOME_Spell_Dictionary_Error_marshal},
	       {CORBA_OBJECT_NIL, NULL} };
	    ORBit_send_user_exception(_ORBIT_send_buffer, ev,
				      _ORBIT_user_exceptions);
	 } else
	    ORBit_send_system_exception(_ORBIT_send_buffer, ev);
	 giop_send_buffer_write(_ORBIT_send_buffer);
	 giop_send_buffer_unuse(_ORBIT_send_buffer);
      }
   }
}
void
_ORBIT_skel_GNOME_Spell_Dictionary_addWordToPersonal
   (POA_GNOME_Spell_Dictionary * _ORBIT_servant,
    GIOPRecvBuffer * _ORBIT_recv_buffer, CORBA_Environment * ev,
    void (*_impl_addWordToPersonal) (PortableServer_Servant _servant,
				     const CORBA_char * word,
				     CORBA_Environment * ev))
{
   CORBA_char *word;

   {				/* demarshalling */
      guchar *_ORBIT_curptr;
      register CORBA_unsigned_long _ORBIT_tmpvar_2;
      CORBA_unsigned_long _ORBIT_tmpvar_3;

      _ORBIT_curptr = GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur;
      if (giop_msg_conversion_needed(GIOP_MESSAGE_BUFFER(_ORBIT_recv_buffer))) {
	 _ORBIT_curptr = ALIGN_ADDRESS(_ORBIT_curptr, 4);
	 (*((guint32 *) & (_ORBIT_tmpvar_3))) =
	    GUINT32_SWAP_LE_BE(*((guint32 *) _ORBIT_curptr));
	 _ORBIT_curptr += 4;
	 word = (void *) _ORBIT_curptr;
	 _ORBIT_curptr += sizeof(word[_ORBIT_tmpvar_2]) * _ORBIT_tmpvar_3;
      } else {
	 _ORBIT_curptr = ALIGN_ADDRESS(_ORBIT_curptr, 4);
	 _ORBIT_tmpvar_3 = *((CORBA_unsigned_long *) _ORBIT_curptr);
	 _ORBIT_curptr += 4;
	 word = (void *) _ORBIT_curptr;
	 _ORBIT_curptr += sizeof(word[_ORBIT_tmpvar_2]) * _ORBIT_tmpvar_3;
      }
   }
   _impl_addWordToPersonal(_ORBIT_servant, word, ev);
   {				/* marshalling */
      register GIOPSendBuffer *_ORBIT_send_buffer;

      _ORBIT_send_buffer =
	 giop_send_reply_buffer_use(GIOP_MESSAGE_BUFFER(_ORBIT_recv_buffer)->
				    connection, NULL,
				    _ORBIT_recv_buffer->message.u.request.
				    request_id, ev->_major);
      if (_ORBIT_send_buffer) {
	 if (ev->_major == CORBA_NO_EXCEPTION) {
	 } else if (ev->_major == CORBA_USER_EXCEPTION) {
	    static const ORBit_exception_marshal_info _ORBIT_user_exceptions[]
	       =
	       { {(const CORBA_TypeCode)
		  &TC_GNOME_Spell_Dictionary_Error_struct,
		  (gpointer) _ORBIT_GNOME_Spell_Dictionary_Error_marshal},
	       {CORBA_OBJECT_NIL, NULL} };
	    ORBit_send_user_exception(_ORBIT_send_buffer, ev,
				      _ORBIT_user_exceptions);
	 } else
	    ORBit_send_system_exception(_ORBIT_send_buffer, ev);
	 giop_send_buffer_write(_ORBIT_send_buffer);
	 giop_send_buffer_unuse(_ORBIT_send_buffer);
      }
   }
}
void
_ORBIT_skel_GNOME_Spell_Dictionary_setCorrection(POA_GNOME_Spell_Dictionary *
						 _ORBIT_servant,
						 GIOPRecvBuffer *
						 _ORBIT_recv_buffer,
						 CORBA_Environment * ev,
						 void (*_impl_setCorrection)
						 (PortableServer_Servant
						  _servant,
						  const CORBA_char * word,
						  const CORBA_char *
						  replacement,
						  CORBA_Environment * ev))
{
   CORBA_char *word;
   CORBA_char *replacement;

   {				/* demarshalling */
      guchar *_ORBIT_curptr;
      register CORBA_unsigned_long _ORBIT_tmpvar_4;
      CORBA_unsigned_long _ORBIT_tmpvar_5;
      register CORBA_unsigned_long _ORBIT_tmpvar_6;
      CORBA_unsigned_long _ORBIT_tmpvar_7;

      _ORBIT_curptr = GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur;
      if (giop_msg_conversion_needed(GIOP_MESSAGE_BUFFER(_ORBIT_recv_buffer))) {
	 _ORBIT_curptr = ALIGN_ADDRESS(_ORBIT_curptr, 4);
	 (*((guint32 *) & (_ORBIT_tmpvar_5))) =
	    GUINT32_SWAP_LE_BE(*((guint32 *) _ORBIT_curptr));
	 _ORBIT_curptr += 4;
	 word = (void *) _ORBIT_curptr;
	 _ORBIT_curptr += sizeof(word[_ORBIT_tmpvar_4]) * _ORBIT_tmpvar_5;
	 _ORBIT_curptr = ALIGN_ADDRESS(_ORBIT_curptr, 4);
	 (*((guint32 *) & (_ORBIT_tmpvar_7))) =
	    GUINT32_SWAP_LE_BE(*((guint32 *) _ORBIT_curptr));
	 _ORBIT_curptr += 4;
	 replacement = (void *) _ORBIT_curptr;
	 _ORBIT_curptr +=
	    sizeof(replacement[_ORBIT_tmpvar_6]) * _ORBIT_tmpvar_7;
      } else {
	 _ORBIT_curptr = ALIGN_ADDRESS(_ORBIT_curptr, 4);
	 _ORBIT_tmpvar_5 = *((CORBA_unsigned_long *) _ORBIT_curptr);
	 _ORBIT_curptr += 4;
	 word = (void *) _ORBIT_curptr;
	 _ORBIT_curptr += sizeof(word[_ORBIT_tmpvar_4]) * _ORBIT_tmpvar_5;
	 _ORBIT_curptr = ALIGN_ADDRESS(_ORBIT_curptr, 4);
	 _ORBIT_tmpvar_7 = *((CORBA_unsigned_long *) _ORBIT_curptr);
	 _ORBIT_curptr += 4;
	 replacement = (void *) _ORBIT_curptr;
	 _ORBIT_curptr +=
	    sizeof(replacement[_ORBIT_tmpvar_6]) * _ORBIT_tmpvar_7;
      }
   }
   _impl_setCorrection(_ORBIT_servant, word, replacement, ev);
   {				/* marshalling */
      register GIOPSendBuffer *_ORBIT_send_buffer;

      _ORBIT_send_buffer =
	 giop_send_reply_buffer_use(GIOP_MESSAGE_BUFFER(_ORBIT_recv_buffer)->
				    connection, NULL,
				    _ORBIT_recv_buffer->message.u.request.
				    request_id, ev->_major);
      if (_ORBIT_send_buffer) {
	 if (ev->_major == CORBA_NO_EXCEPTION) {
	 } else
	    ORBit_send_system_exception(_ORBIT_send_buffer, ev);
	 giop_send_buffer_write(_ORBIT_send_buffer);
	 giop_send_buffer_unuse(_ORBIT_send_buffer);
      }
   }
}
static ORBitSkeleton
get_skel_GNOME_Spell_Dictionary(POA_GNOME_Spell_Dictionary * servant,
				GIOPRecvBuffer * _ORBIT_recv_buffer,
				gpointer * impl)
{
   gchar *opname = _ORBIT_recv_buffer->message.u.request.operation;

   switch (opname[0]) {
     case 'a':
	switch (opname[1]) {
	  case 'd':
	     switch (opname[2]) {
	       case 'd':
		  switch (opname[3]) {
		    case 'W':
		       switch (opname[4]) {
			 case 'o':
			    switch (opname[5]) {
			      case 'r':
				 switch (opname[6]) {
				   case 'd':
				      switch (opname[7]) {
					case 'T':
					   switch (opname[8]) {
					     case 'o':
						switch (opname[9]) {
						  case 'P':
						     if (strcmp
							 ((opname + 10),
							  "ersonal"))
							break;
						     *impl =
							(gpointer) servant->
							vepv->
							GNOME_Spell_Dictionary_epv->
							addWordToPersonal;
						     return (ORBitSkeleton)
							_ORBIT_skel_GNOME_Spell_Dictionary_addWordToPersonal;
						     break;
						  case 'S':
						     if (strcmp
							 ((opname + 10),
							  "ession"))
							break;
						     *impl =
							(gpointer) servant->
							vepv->
							GNOME_Spell_Dictionary_epv->
							addWordToSession;
						     return (ORBitSkeleton)
							_ORBIT_skel_GNOME_Spell_Dictionary_addWordToSession;
						     break;
						  default:
						     break;
						}
						break;
					     default:
						break;
					   }
					   break;
					default:
					   break;
				      }
				      break;
				   default:
				      break;
				 }
				 break;
			      default:
				 break;
			    }
			    break;
			 default:
			    break;
		       }
		       break;
		    default:
		       break;
		  }
		  break;
	       default:
		  break;
	     }
	     break;
	  default:
	     break;
	}
	break;
     case 'c':
	if (strcmp((opname + 1), "heckWord"))
	   break;
	*impl =
	   (gpointer) servant->vepv->GNOME_Spell_Dictionary_epv->checkWord;
	return (ORBitSkeleton) _ORBIT_skel_GNOME_Spell_Dictionary_checkWord;
	break;
     case 'g':
	switch (opname[1]) {
	  case 'e':
	     switch (opname[2]) {
	       case 't':
		  switch (opname[3]) {
		    case 'L':
		       if (strcmp((opname + 4), "anguages"))
			  break;
		       *impl =
			  (gpointer) servant->vepv->
			  GNOME_Spell_Dictionary_epv->getLanguages;
		       return (ORBitSkeleton)
			  _ORBIT_skel_GNOME_Spell_Dictionary_getLanguages;
		       break;
		    case 'S':
		       if (strcmp((opname + 4), "uggestions"))
			  break;
		       *impl =
			  (gpointer) servant->vepv->
			  GNOME_Spell_Dictionary_epv->getSuggestions;
		       return (ORBitSkeleton)
			  _ORBIT_skel_GNOME_Spell_Dictionary_getSuggestions;
		       break;
		    default:
		       break;
		  }
		  break;
	       default:
		  break;
	     }
	     break;
	  default:
	     break;
	}
	break;
     case 'q':
	if (strcmp((opname + 1), "ueryInterface"))
	   break;
	*impl = (gpointer) servant->vepv->Bonobo_Unknown_epv->queryInterface;
	return (ORBitSkeleton) _ORBIT_skel_Bonobo_Unknown_queryInterface;
	break;
     case 'r':
	if (strcmp((opname + 1), "ef"))
	   break;
	*impl = (gpointer) servant->vepv->Bonobo_Unknown_epv->ref;
	return (ORBitSkeleton) _ORBIT_skel_Bonobo_Unknown_ref;
	break;
     case 's':
	switch (opname[1]) {
	  case 'e':
	     switch (opname[2]) {
	       case 't':
		  switch (opname[3]) {
		    case 'C':
		       if (strcmp((opname + 4), "orrection"))
			  break;
		       *impl =
			  (gpointer) servant->vepv->
			  GNOME_Spell_Dictionary_epv->setCorrection;
		       return (ORBitSkeleton)
			  _ORBIT_skel_GNOME_Spell_Dictionary_setCorrection;
		       break;
		    case 'L':
		       if (strcmp((opname + 4), "anguage"))
			  break;
		       *impl =
			  (gpointer) servant->vepv->
			  GNOME_Spell_Dictionary_epv->setLanguage;
		       return (ORBitSkeleton)
			  _ORBIT_skel_GNOME_Spell_Dictionary_setLanguage;
		       break;
		    default:
		       break;
		  }
		  break;
	       default:
		  break;
	     }
	     break;
	  default:
	     break;
	}
	break;
     case 'u':
	if (strcmp((opname + 1), "nref"))
	   break;
	*impl = (gpointer) servant->vepv->Bonobo_Unknown_epv->unref;
	return (ORBitSkeleton) _ORBIT_skel_Bonobo_Unknown_unref;
	break;
     default:
	break;
   }
   return NULL;
}

static void
init_local_objref_GNOME_Spell_Dictionary(CORBA_Object obj,
					 POA_GNOME_Spell_Dictionary * servant)
{
   obj->vepv[Bonobo_Unknown__classid] = servant->vepv->Bonobo_Unknown_epv;
   obj->vepv[GNOME_Spell_Dictionary__classid] =
      servant->vepv->GNOME_Spell_Dictionary_epv;
}

void
POA_GNOME_Spell_Dictionary__init(PortableServer_Servant servant,
				 CORBA_Environment * env)
{
   static const PortableServer_ClassInfo class_info =
      { (ORBit_impl_finder) & get_skel_GNOME_Spell_Dictionary,
"IDL:GNOME/Spell/Dictionary:1.0", (ORBit_local_objref_init) & init_local_objref_GNOME_Spell_Dictionary };
   PortableServer_ServantBase__init(((PortableServer_ServantBase *) servant),
				    env);
   POA_Bonobo_Unknown__init(servant, env);
   ORBIT_OBJECT_KEY(((PortableServer_ServantBase *) servant)->_private)->
      class_info = (PortableServer_ClassInfo *) & class_info;
   if (!GNOME_Spell_Dictionary__classid)
      GNOME_Spell_Dictionary__classid = ORBit_register_class(&class_info);
}

void
POA_GNOME_Spell_Dictionary__fini(PortableServer_Servant servant,
				 CORBA_Environment * env)
{
   POA_Bonobo_Unknown__fini(servant, env);
   PortableServer_ServantBase__fini(servant, env);
}
