/*
 * This file was generated by orbit-idl - DO NOT EDIT!
 */

#include <string.h>
#include "nautilus-distributed-undo.h"

#if ( (TC_IMPL_TC_Nautilus_Undo_MenuItem_0 == 'n') \
&& (TC_IMPL_TC_Nautilus_Undo_MenuItem_1 == 'a') \
&& (TC_IMPL_TC_Nautilus_Undo_MenuItem_2 == 'u') \
&& (TC_IMPL_TC_Nautilus_Undo_MenuItem_3 == 't') \
&& (TC_IMPL_TC_Nautilus_Undo_MenuItem_4 == 'i') \
&& (TC_IMPL_TC_Nautilus_Undo_MenuItem_5 == 'l') \
&& (TC_IMPL_TC_Nautilus_Undo_MenuItem_6 == 'u') \
&& (TC_IMPL_TC_Nautilus_Undo_MenuItem_7 == 's') \
&& (TC_IMPL_TC_Nautilus_Undo_MenuItem_8 == '_') \
&& (TC_IMPL_TC_Nautilus_Undo_MenuItem_9 == 'd') \
&& (TC_IMPL_TC_Nautilus_Undo_MenuItem_10 == 'i') \
&& (TC_IMPL_TC_Nautilus_Undo_MenuItem_11 == 's') \
&& (TC_IMPL_TC_Nautilus_Undo_MenuItem_12 == 't') \
&& (TC_IMPL_TC_Nautilus_Undo_MenuItem_13 == 'r') \
&& (TC_IMPL_TC_Nautilus_Undo_MenuItem_14 == 'i') \
&& (TC_IMPL_TC_Nautilus_Undo_MenuItem_15 == 'b') \
&& (TC_IMPL_TC_Nautilus_Undo_MenuItem_16 == 'u') \
&& (TC_IMPL_TC_Nautilus_Undo_MenuItem_17 == 't') \
&& (TC_IMPL_TC_Nautilus_Undo_MenuItem_18 == 'e') \
&& (TC_IMPL_TC_Nautilus_Undo_MenuItem_19 == 'd') \
&& (TC_IMPL_TC_Nautilus_Undo_MenuItem_20 == '_') \
&& (TC_IMPL_TC_Nautilus_Undo_MenuItem_21 == 'u') \
&& (TC_IMPL_TC_Nautilus_Undo_MenuItem_22 == 'n') \
&& (TC_IMPL_TC_Nautilus_Undo_MenuItem_23 == 'd') \
&& (TC_IMPL_TC_Nautilus_Undo_MenuItem_24 == 'o') \
) && !defined(TC_DEF_TC_Nautilus_Undo_MenuItem)
#define TC_DEF_TC_Nautilus_Undo_MenuItem 1
static const char *anon_subnames_array1[] = { "label", "hint" };
static const CORBA_TypeCode anon_subtypes_array2[] =
   { (CORBA_TypeCode) & TC_CORBA_string_struct,
      (CORBA_TypeCode) & TC_CORBA_string_struct };
const struct CORBA_TypeCode_struct TC_Nautilus_Undo_MenuItem_struct = {
   
      {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},

   CORBA_tk_struct, "MenuItem", "IDL:Nautilus/Undo/MenuItem:1.0",
   0, 2,
   (const char **) anon_subnames_array1,
   (CORBA_TypeCode *) anon_subtypes_array2,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_Nautilus_Undo_Transaction_0 == 'n') \
&& (TC_IMPL_TC_Nautilus_Undo_Transaction_1 == 'a') \
&& (TC_IMPL_TC_Nautilus_Undo_Transaction_2 == 'u') \
&& (TC_IMPL_TC_Nautilus_Undo_Transaction_3 == 't') \
&& (TC_IMPL_TC_Nautilus_Undo_Transaction_4 == 'i') \
&& (TC_IMPL_TC_Nautilus_Undo_Transaction_5 == 'l') \
&& (TC_IMPL_TC_Nautilus_Undo_Transaction_6 == 'u') \
&& (TC_IMPL_TC_Nautilus_Undo_Transaction_7 == 's') \
&& (TC_IMPL_TC_Nautilus_Undo_Transaction_8 == '_') \
&& (TC_IMPL_TC_Nautilus_Undo_Transaction_9 == 'd') \
&& (TC_IMPL_TC_Nautilus_Undo_Transaction_10 == 'i') \
&& (TC_IMPL_TC_Nautilus_Undo_Transaction_11 == 's') \
&& (TC_IMPL_TC_Nautilus_Undo_Transaction_12 == 't') \
&& (TC_IMPL_TC_Nautilus_Undo_Transaction_13 == 'r') \
&& (TC_IMPL_TC_Nautilus_Undo_Transaction_14 == 'i') \
&& (TC_IMPL_TC_Nautilus_Undo_Transaction_15 == 'b') \
&& (TC_IMPL_TC_Nautilus_Undo_Transaction_16 == 'u') \
&& (TC_IMPL_TC_Nautilus_Undo_Transaction_17 == 't') \
&& (TC_IMPL_TC_Nautilus_Undo_Transaction_18 == 'e') \
&& (TC_IMPL_TC_Nautilus_Undo_Transaction_19 == 'd') \
&& (TC_IMPL_TC_Nautilus_Undo_Transaction_20 == '_') \
&& (TC_IMPL_TC_Nautilus_Undo_Transaction_21 == 'u') \
&& (TC_IMPL_TC_Nautilus_Undo_Transaction_22 == 'n') \
&& (TC_IMPL_TC_Nautilus_Undo_Transaction_23 == 'd') \
&& (TC_IMPL_TC_Nautilus_Undo_Transaction_24 == 'o') \
) && !defined(TC_DEF_TC_Nautilus_Undo_Transaction)
#define TC_DEF_TC_Nautilus_Undo_Transaction 1
const struct CORBA_TypeCode_struct TC_Nautilus_Undo_Transaction_struct = {
   
      {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},

   CORBA_tk_objref, "Transaction", "IDL:Nautilus/Undo/Transaction:1.0",
   0, 0,
   NULL,
   NULL,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_Nautilus_Undo_Manager_0 == 'n') \
&& (TC_IMPL_TC_Nautilus_Undo_Manager_1 == 'a') \
&& (TC_IMPL_TC_Nautilus_Undo_Manager_2 == 'u') \
&& (TC_IMPL_TC_Nautilus_Undo_Manager_3 == 't') \
&& (TC_IMPL_TC_Nautilus_Undo_Manager_4 == 'i') \
&& (TC_IMPL_TC_Nautilus_Undo_Manager_5 == 'l') \
&& (TC_IMPL_TC_Nautilus_Undo_Manager_6 == 'u') \
&& (TC_IMPL_TC_Nautilus_Undo_Manager_7 == 's') \
&& (TC_IMPL_TC_Nautilus_Undo_Manager_8 == '_') \
&& (TC_IMPL_TC_Nautilus_Undo_Manager_9 == 'd') \
&& (TC_IMPL_TC_Nautilus_Undo_Manager_10 == 'i') \
&& (TC_IMPL_TC_Nautilus_Undo_Manager_11 == 's') \
&& (TC_IMPL_TC_Nautilus_Undo_Manager_12 == 't') \
&& (TC_IMPL_TC_Nautilus_Undo_Manager_13 == 'r') \
&& (TC_IMPL_TC_Nautilus_Undo_Manager_14 == 'i') \
&& (TC_IMPL_TC_Nautilus_Undo_Manager_15 == 'b') \
&& (TC_IMPL_TC_Nautilus_Undo_Manager_16 == 'u') \
&& (TC_IMPL_TC_Nautilus_Undo_Manager_17 == 't') \
&& (TC_IMPL_TC_Nautilus_Undo_Manager_18 == 'e') \
&& (TC_IMPL_TC_Nautilus_Undo_Manager_19 == 'd') \
&& (TC_IMPL_TC_Nautilus_Undo_Manager_20 == '_') \
&& (TC_IMPL_TC_Nautilus_Undo_Manager_21 == 'u') \
&& (TC_IMPL_TC_Nautilus_Undo_Manager_22 == 'n') \
&& (TC_IMPL_TC_Nautilus_Undo_Manager_23 == 'd') \
&& (TC_IMPL_TC_Nautilus_Undo_Manager_24 == 'o') \
) && !defined(TC_DEF_TC_Nautilus_Undo_Manager)
#define TC_DEF_TC_Nautilus_Undo_Manager 1
const struct CORBA_TypeCode_struct TC_Nautilus_Undo_Manager_struct = {
   
      {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},

   CORBA_tk_objref, "Manager", "IDL:Nautilus/Undo/Manager:1.0",
   0, 0,
   NULL,
   NULL,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_Nautilus_Undo_Context_0 == 'n') \
&& (TC_IMPL_TC_Nautilus_Undo_Context_1 == 'a') \
&& (TC_IMPL_TC_Nautilus_Undo_Context_2 == 'u') \
&& (TC_IMPL_TC_Nautilus_Undo_Context_3 == 't') \
&& (TC_IMPL_TC_Nautilus_Undo_Context_4 == 'i') \
&& (TC_IMPL_TC_Nautilus_Undo_Context_5 == 'l') \
&& (TC_IMPL_TC_Nautilus_Undo_Context_6 == 'u') \
&& (TC_IMPL_TC_Nautilus_Undo_Context_7 == 's') \
&& (TC_IMPL_TC_Nautilus_Undo_Context_8 == '_') \
&& (TC_IMPL_TC_Nautilus_Undo_Context_9 == 'd') \
&& (TC_IMPL_TC_Nautilus_Undo_Context_10 == 'i') \
&& (TC_IMPL_TC_Nautilus_Undo_Context_11 == 's') \
&& (TC_IMPL_TC_Nautilus_Undo_Context_12 == 't') \
&& (TC_IMPL_TC_Nautilus_Undo_Context_13 == 'r') \
&& (TC_IMPL_TC_Nautilus_Undo_Context_14 == 'i') \
&& (TC_IMPL_TC_Nautilus_Undo_Context_15 == 'b') \
&& (TC_IMPL_TC_Nautilus_Undo_Context_16 == 'u') \
&& (TC_IMPL_TC_Nautilus_Undo_Context_17 == 't') \
&& (TC_IMPL_TC_Nautilus_Undo_Context_18 == 'e') \
&& (TC_IMPL_TC_Nautilus_Undo_Context_19 == 'd') \
&& (TC_IMPL_TC_Nautilus_Undo_Context_20 == '_') \
&& (TC_IMPL_TC_Nautilus_Undo_Context_21 == 'u') \
&& (TC_IMPL_TC_Nautilus_Undo_Context_22 == 'n') \
&& (TC_IMPL_TC_Nautilus_Undo_Context_23 == 'd') \
&& (TC_IMPL_TC_Nautilus_Undo_Context_24 == 'o') \
) && !defined(TC_DEF_TC_Nautilus_Undo_Context)
#define TC_DEF_TC_Nautilus_Undo_Context 1
const struct CORBA_TypeCode_struct TC_Nautilus_Undo_Context_struct = {
   
      {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},

   CORBA_tk_objref, "Context", "IDL:Nautilus/Undo/Context:1.0",
   0, 0,
   NULL,
   NULL,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
gpointer
Nautilus_Undo_MenuItem__free(gpointer mem, gpointer dat,
			     CORBA_boolean free_strings)
{
   Nautilus_Undo_MenuItem *var = mem;

   if (free_strings) {
      CORBA_string__free(&(var->label), NULL, free_strings);
   }
   if (free_strings) {
      CORBA_string__free(&(var->hint), NULL, free_strings);
   }
   return (gpointer) (var + 1);
}

Nautilus_Undo_MenuItem *
Nautilus_Undo_MenuItem__alloc(void)
{
   Nautilus_Undo_MenuItem *retval;

   retval =
      ORBit_alloc(sizeof(Nautilus_Undo_MenuItem),
		  (ORBit_free_childvals) Nautilus_Undo_MenuItem__free,
		  GUINT_TO_POINTER(1));
   memset(&(retval->label), '\0', sizeof(retval->label));
   memset(&(retval->hint), '\0', sizeof(retval->hint));
   return retval;
}

CORBA_unsigned_long Nautilus_Undo_Transaction__classid = 0;
CORBA_unsigned_long Nautilus_Undo_Manager__classid = 0;
CORBA_unsigned_long Nautilus_Undo_Context__classid = 0;
