/*
 * This file was generated by orbit-idl - DO NOT EDIT!
 */

#include <string.h>
#include "nautilus-distributed-undo.h"

void
_ORBIT_skel_Nautilus_Undo_Transaction__get_undo_menu_item
   (POA_Nautilus_Undo_Transaction * _ORBIT_servant,
    GIOPRecvBuffer * _ORBIT_recv_buffer, CORBA_Environment * ev,
    Nautilus_Undo_MenuItem *
    (*_impl__get_undo_menu_item) (PortableServer_Servant _servant,
				  CORBA_Environment * ev))
{
   Nautilus_Undo_MenuItem *_ORBIT_retval;

   _ORBIT_retval = _impl__get_undo_menu_item(_ORBIT_servant, ev);
   {				/* marshalling */
      register GIOPSendBuffer *_ORBIT_send_buffer;

      _ORBIT_send_buffer =
	 giop_send_reply_buffer_use(GIOP_MESSAGE_BUFFER(_ORBIT_recv_buffer)->
				    connection, NULL,
				    _ORBIT_recv_buffer->message.u.request.
				    request_id, ev->_major);
      if (_ORBIT_send_buffer) {
	 if (ev->_major == CORBA_NO_EXCEPTION) {
	    register CORBA_unsigned_long _ORBIT_tmpvar_0;
	    CORBA_unsigned_long _ORBIT_tmpvar_1;
	    register CORBA_unsigned_long _ORBIT_tmpvar_2;
	    CORBA_unsigned_long _ORBIT_tmpvar_3;

	    _ORBIT_tmpvar_1 = strlen((*_ORBIT_retval).label) + 1;
	    giop_message_buffer_do_alignment(GIOP_MESSAGE_BUFFER
					     (_ORBIT_send_buffer), 4);
	    {
	       guchar *_ORBIT_t;

	       _ORBIT_t = alloca(sizeof(_ORBIT_tmpvar_1));
	       memcpy(_ORBIT_t, &(_ORBIT_tmpvar_1), sizeof(_ORBIT_tmpvar_1));
	       giop_message_buffer_append_mem(GIOP_MESSAGE_BUFFER
					      (_ORBIT_send_buffer),
					      (_ORBIT_t),
					      sizeof(_ORBIT_tmpvar_1));
	    }
	    giop_message_buffer_append_mem(GIOP_MESSAGE_BUFFER
					   (_ORBIT_send_buffer),
					   ((*_ORBIT_retval).label),
					   sizeof((*_ORBIT_retval).
						  label[_ORBIT_tmpvar_0]) *
					   _ORBIT_tmpvar_1);
	    _ORBIT_tmpvar_3 = strlen((*_ORBIT_retval).hint) + 1;
	    giop_message_buffer_do_alignment(GIOP_MESSAGE_BUFFER
					     (_ORBIT_send_buffer), 4);
	    {
	       guchar *_ORBIT_t;

	       _ORBIT_t = alloca(sizeof(_ORBIT_tmpvar_3));
	       memcpy(_ORBIT_t, &(_ORBIT_tmpvar_3), sizeof(_ORBIT_tmpvar_3));
	       giop_message_buffer_append_mem(GIOP_MESSAGE_BUFFER
					      (_ORBIT_send_buffer),
					      (_ORBIT_t),
					      sizeof(_ORBIT_tmpvar_3));
	    }
	    giop_message_buffer_append_mem(GIOP_MESSAGE_BUFFER
					   (_ORBIT_send_buffer),
					   ((*_ORBIT_retval).hint),
					   sizeof((*_ORBIT_retval).
						  hint[_ORBIT_tmpvar_2]) *
					   _ORBIT_tmpvar_3);
	 } else
	    ORBit_send_system_exception(_ORBIT_send_buffer, ev);
	 giop_send_buffer_write(_ORBIT_send_buffer);
	 giop_send_buffer_unuse(_ORBIT_send_buffer);
      }
      if (ev->_major == CORBA_NO_EXCEPTION)
	 CORBA_free(_ORBIT_retval);
   }
}
void
_ORBIT_skel_Nautilus_Undo_Transaction__get_redo_menu_item
   (POA_Nautilus_Undo_Transaction * _ORBIT_servant,
    GIOPRecvBuffer * _ORBIT_recv_buffer, CORBA_Environment * ev,
    Nautilus_Undo_MenuItem *
    (*_impl__get_redo_menu_item) (PortableServer_Servant _servant,
				  CORBA_Environment * ev))
{
   Nautilus_Undo_MenuItem *_ORBIT_retval;

   _ORBIT_retval = _impl__get_redo_menu_item(_ORBIT_servant, ev);
   {				/* marshalling */
      register GIOPSendBuffer *_ORBIT_send_buffer;

      _ORBIT_send_buffer =
	 giop_send_reply_buffer_use(GIOP_MESSAGE_BUFFER(_ORBIT_recv_buffer)->
				    connection, NULL,
				    _ORBIT_recv_buffer->message.u.request.
				    request_id, ev->_major);
      if (_ORBIT_send_buffer) {
	 if (ev->_major == CORBA_NO_EXCEPTION) {
	    register CORBA_unsigned_long _ORBIT_tmpvar_0;
	    CORBA_unsigned_long _ORBIT_tmpvar_1;
	    register CORBA_unsigned_long _ORBIT_tmpvar_2;
	    CORBA_unsigned_long _ORBIT_tmpvar_3;

	    _ORBIT_tmpvar_1 = strlen((*_ORBIT_retval).label) + 1;
	    giop_message_buffer_do_alignment(GIOP_MESSAGE_BUFFER
					     (_ORBIT_send_buffer), 4);
	    {
	       guchar *_ORBIT_t;

	       _ORBIT_t = alloca(sizeof(_ORBIT_tmpvar_1));
	       memcpy(_ORBIT_t, &(_ORBIT_tmpvar_1), sizeof(_ORBIT_tmpvar_1));
	       giop_message_buffer_append_mem(GIOP_MESSAGE_BUFFER
					      (_ORBIT_send_buffer),
					      (_ORBIT_t),
					      sizeof(_ORBIT_tmpvar_1));
	    }
	    giop_message_buffer_append_mem(GIOP_MESSAGE_BUFFER
					   (_ORBIT_send_buffer),
					   ((*_ORBIT_retval).label),
					   sizeof((*_ORBIT_retval).
						  label[_ORBIT_tmpvar_0]) *
					   _ORBIT_tmpvar_1);
	    _ORBIT_tmpvar_3 = strlen((*_ORBIT_retval).hint) + 1;
	    giop_message_buffer_do_alignment(GIOP_MESSAGE_BUFFER
					     (_ORBIT_send_buffer), 4);
	    {
	       guchar *_ORBIT_t;

	       _ORBIT_t = alloca(sizeof(_ORBIT_tmpvar_3));
	       memcpy(_ORBIT_t, &(_ORBIT_tmpvar_3), sizeof(_ORBIT_tmpvar_3));
	       giop_message_buffer_append_mem(GIOP_MESSAGE_BUFFER
					      (_ORBIT_send_buffer),
					      (_ORBIT_t),
					      sizeof(_ORBIT_tmpvar_3));
	    }
	    giop_message_buffer_append_mem(GIOP_MESSAGE_BUFFER
					   (_ORBIT_send_buffer),
					   ((*_ORBIT_retval).hint),
					   sizeof((*_ORBIT_retval).
						  hint[_ORBIT_tmpvar_2]) *
					   _ORBIT_tmpvar_3);
	 } else
	    ORBit_send_system_exception(_ORBIT_send_buffer, ev);
	 giop_send_buffer_write(_ORBIT_send_buffer);
	 giop_send_buffer_unuse(_ORBIT_send_buffer);
      }
      if (ev->_major == CORBA_NO_EXCEPTION)
	 CORBA_free(_ORBIT_retval);
   }
}
void
_ORBIT_skel_Nautilus_Undo_Transaction__get_operation_name
   (POA_Nautilus_Undo_Transaction * _ORBIT_servant,
    GIOPRecvBuffer * _ORBIT_recv_buffer, CORBA_Environment * ev,
    CORBA_char *
    (*_impl__get_operation_name) (PortableServer_Servant _servant,
				  CORBA_Environment * ev))
{
   CORBA_char *_ORBIT_retval;

   _ORBIT_retval = _impl__get_operation_name(_ORBIT_servant, ev);
   {				/* marshalling */
      register GIOPSendBuffer *_ORBIT_send_buffer;

      _ORBIT_send_buffer =
	 giop_send_reply_buffer_use(GIOP_MESSAGE_BUFFER(_ORBIT_recv_buffer)->
				    connection, NULL,
				    _ORBIT_recv_buffer->message.u.request.
				    request_id, ev->_major);
      if (_ORBIT_send_buffer) {
	 if (ev->_major == CORBA_NO_EXCEPTION) {
	    register CORBA_unsigned_long _ORBIT_tmpvar_0;
	    CORBA_unsigned_long _ORBIT_tmpvar_1;

	    _ORBIT_tmpvar_1 = strlen(_ORBIT_retval) + 1;
	    giop_message_buffer_do_alignment(GIOP_MESSAGE_BUFFER
					     (_ORBIT_send_buffer), 4);
	    {
	       guchar *_ORBIT_t;

	       _ORBIT_t = alloca(sizeof(_ORBIT_tmpvar_1));
	       memcpy(_ORBIT_t, &(_ORBIT_tmpvar_1), sizeof(_ORBIT_tmpvar_1));
	       giop_message_buffer_append_mem(GIOP_MESSAGE_BUFFER
					      (_ORBIT_send_buffer),
					      (_ORBIT_t),
					      sizeof(_ORBIT_tmpvar_1));
	    }
	    giop_message_buffer_append_mem(GIOP_MESSAGE_BUFFER
					   (_ORBIT_send_buffer),
					   (_ORBIT_retval),
					   sizeof(_ORBIT_retval
						  [_ORBIT_tmpvar_0]) *
					   _ORBIT_tmpvar_1);
	 } else
	    ORBit_send_system_exception(_ORBIT_send_buffer, ev);
	 giop_send_buffer_write(_ORBIT_send_buffer);
	 giop_send_buffer_unuse(_ORBIT_send_buffer);
      }
      if (ev->_major == CORBA_NO_EXCEPTION)
	 CORBA_free(_ORBIT_retval);
   }
}
void
_ORBIT_skel_Nautilus_Undo_Transaction_undo(POA_Nautilus_Undo_Transaction *
					   _ORBIT_servant,
					   GIOPRecvBuffer *
					   _ORBIT_recv_buffer,
					   CORBA_Environment * ev,
					   void (*_impl_undo)
					   (PortableServer_Servant _servant,
					    CORBA_Environment * ev))
{
   _impl_undo(_ORBIT_servant, ev);
   {				/* marshalling */
      register GIOPSendBuffer *_ORBIT_send_buffer;

      _ORBIT_send_buffer =
	 giop_send_reply_buffer_use(GIOP_MESSAGE_BUFFER(_ORBIT_recv_buffer)->
				    connection, NULL,
				    _ORBIT_recv_buffer->message.u.request.
				    request_id, ev->_major);
      if (_ORBIT_send_buffer) {
	 if (ev->_major == CORBA_NO_EXCEPTION) {
	 } else
	    ORBit_send_system_exception(_ORBIT_send_buffer, ev);
	 giop_send_buffer_write(_ORBIT_send_buffer);
	 giop_send_buffer_unuse(_ORBIT_send_buffer);
      }
   }
}
void
_ORBIT_skel_Nautilus_Undo_Manager_append(POA_Nautilus_Undo_Manager *
					 _ORBIT_servant,
					 GIOPRecvBuffer * _ORBIT_recv_buffer,
					 CORBA_Environment * ev,
					 void (*_impl_append)
					 (PortableServer_Servant _servant,
					  const Nautilus_Undo_Transaction
					  transaction,
					  CORBA_Environment * ev))
{
   Nautilus_Undo_Transaction transaction;

   {				/* demarshalling */
      guchar *_ORBIT_curptr;

      _ORBIT_curptr = GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur;
      if (giop_msg_conversion_needed(GIOP_MESSAGE_BUFFER(_ORBIT_recv_buffer))) {
	 GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur = _ORBIT_curptr;
	 transaction =
	    ORBit_demarshal_object(_ORBIT_recv_buffer,
				   (((ORBit_ObjectKey
				      *) _ORBIT_servant->_private)->object->
				    orb));
	 _ORBIT_curptr = GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur;
      } else {
	 GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur = _ORBIT_curptr;
	 transaction =
	    ORBit_demarshal_object(_ORBIT_recv_buffer,
				   (((ORBit_ObjectKey
				      *) _ORBIT_servant->_private)->object->
				    orb));
	 _ORBIT_curptr = GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur;
      }
   }
   _impl_append(_ORBIT_servant, transaction, ev);
   {				/* marshalling */
      register GIOPSendBuffer *_ORBIT_send_buffer;

      _ORBIT_send_buffer =
	 giop_send_reply_buffer_use(GIOP_MESSAGE_BUFFER(_ORBIT_recv_buffer)->
				    connection, NULL,
				    _ORBIT_recv_buffer->message.u.request.
				    request_id, ev->_major);
      if (_ORBIT_send_buffer) {
	 if (ev->_major == CORBA_NO_EXCEPTION) {
	 } else
	    ORBit_send_system_exception(_ORBIT_send_buffer, ev);
	 giop_send_buffer_write(_ORBIT_send_buffer);
	 giop_send_buffer_unuse(_ORBIT_send_buffer);
      }
      CORBA_Object_release(transaction, ev);
   }
}
void
_ORBIT_skel_Nautilus_Undo_Manager_forget(POA_Nautilus_Undo_Manager *
					 _ORBIT_servant,
					 GIOPRecvBuffer * _ORBIT_recv_buffer,
					 CORBA_Environment * ev,
					 void (*_impl_forget)
					 (PortableServer_Servant _servant,
					  const Nautilus_Undo_Transaction
					  transaction,
					  CORBA_Environment * ev))
{
   Nautilus_Undo_Transaction transaction;

   {				/* demarshalling */
      guchar *_ORBIT_curptr;

      _ORBIT_curptr = GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur;
      if (giop_msg_conversion_needed(GIOP_MESSAGE_BUFFER(_ORBIT_recv_buffer))) {
	 GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur = _ORBIT_curptr;
	 transaction =
	    ORBit_demarshal_object(_ORBIT_recv_buffer,
				   (((ORBit_ObjectKey
				      *) _ORBIT_servant->_private)->object->
				    orb));
	 _ORBIT_curptr = GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur;
      } else {
	 GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur = _ORBIT_curptr;
	 transaction =
	    ORBit_demarshal_object(_ORBIT_recv_buffer,
				   (((ORBit_ObjectKey
				      *) _ORBIT_servant->_private)->object->
				    orb));
	 _ORBIT_curptr = GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur;
      }
   }
   _impl_forget(_ORBIT_servant, transaction, ev);
   {				/* marshalling */
      register GIOPSendBuffer *_ORBIT_send_buffer;

      _ORBIT_send_buffer =
	 giop_send_reply_buffer_use(GIOP_MESSAGE_BUFFER(_ORBIT_recv_buffer)->
				    connection, NULL,
				    _ORBIT_recv_buffer->message.u.request.
				    request_id, ev->_major);
      if (_ORBIT_send_buffer) {
	 if (ev->_major == CORBA_NO_EXCEPTION) {
	 } else
	    ORBit_send_system_exception(_ORBIT_send_buffer, ev);
	 giop_send_buffer_write(_ORBIT_send_buffer);
	 giop_send_buffer_unuse(_ORBIT_send_buffer);
      }
      CORBA_Object_release(transaction, ev);
   }
}
void
_ORBIT_skel_Nautilus_Undo_Manager_undo(POA_Nautilus_Undo_Manager *
				       _ORBIT_servant,
				       GIOPRecvBuffer * _ORBIT_recv_buffer,
				       CORBA_Environment * ev,
				       void (*_impl_undo)
				       (PortableServer_Servant _servant,
					CORBA_Environment * ev))
{
   _impl_undo(_ORBIT_servant, ev);
   {				/* marshalling */
      register GIOPSendBuffer *_ORBIT_send_buffer;

      _ORBIT_send_buffer =
	 giop_send_reply_buffer_use(GIOP_MESSAGE_BUFFER(_ORBIT_recv_buffer)->
				    connection, NULL,
				    _ORBIT_recv_buffer->message.u.request.
				    request_id, ev->_major);
      if (_ORBIT_send_buffer) {
	 if (ev->_major == CORBA_NO_EXCEPTION) {
	 } else
	    ORBit_send_system_exception(_ORBIT_send_buffer, ev);
	 giop_send_buffer_write(_ORBIT_send_buffer);
	 giop_send_buffer_unuse(_ORBIT_send_buffer);
      }
   }
}
void
_ORBIT_skel_Nautilus_Undo_Context__get_undo_manager(POA_Nautilus_Undo_Context
						    * _ORBIT_servant,
						    GIOPRecvBuffer *
						    _ORBIT_recv_buffer,
						    CORBA_Environment * ev,
						    Nautilus_Undo_Manager
						    (*_impl__get_undo_manager)
						    (PortableServer_Servant
						     _servant,
						     CORBA_Environment * ev))
{
   Nautilus_Undo_Manager _ORBIT_retval;

   _ORBIT_retval = _impl__get_undo_manager(_ORBIT_servant, ev);
   {				/* marshalling */
      register GIOPSendBuffer *_ORBIT_send_buffer;

      _ORBIT_send_buffer =
	 giop_send_reply_buffer_use(GIOP_MESSAGE_BUFFER(_ORBIT_recv_buffer)->
				    connection, NULL,
				    _ORBIT_recv_buffer->message.u.request.
				    request_id, ev->_major);
      if (_ORBIT_send_buffer) {
	 if (ev->_major == CORBA_NO_EXCEPTION) {
	    ORBit_marshal_object(_ORBIT_send_buffer, _ORBIT_retval);
	 } else
	    ORBit_send_system_exception(_ORBIT_send_buffer, ev);
	 giop_send_buffer_write(_ORBIT_send_buffer);
	 giop_send_buffer_unuse(_ORBIT_send_buffer);
      }
      if (ev->_major == CORBA_NO_EXCEPTION)
	 CORBA_Object_release(_ORBIT_retval, ev);
   }
}
static ORBitSkeleton
get_skel_Nautilus_Undo_Transaction(POA_Nautilus_Undo_Transaction * servant,
				   GIOPRecvBuffer * _ORBIT_recv_buffer,
				   gpointer * impl)
{
   gchar *opname = _ORBIT_recv_buffer->message.u.request.operation;

   switch (opname[0]) {
     case '_':
	switch (opname[1]) {
	  case 'g':
	     switch (opname[2]) {
	       case 'e':
		  switch (opname[3]) {
		    case 't':
		       switch (opname[4]) {
			 case '_':
			    switch (opname[5]) {
			      case 'o':
				 if (strcmp((opname + 6), "peration_name"))
				    break;
				 *impl =
				    (gpointer) servant->vepv->
				    Nautilus_Undo_Transaction_epv->
				    _get_operation_name;
				 return (ORBitSkeleton)
				    _ORBIT_skel_Nautilus_Undo_Transaction__get_operation_name;
				 break;
			      case 'r':
				 if (strcmp((opname + 6), "edo_menu_item"))
				    break;
				 *impl =
				    (gpointer) servant->vepv->
				    Nautilus_Undo_Transaction_epv->
				    _get_redo_menu_item;
				 return (ORBitSkeleton)
				    _ORBIT_skel_Nautilus_Undo_Transaction__get_redo_menu_item;
				 break;
			      case 'u':
				 if (strcmp((opname + 6), "ndo_menu_item"))
				    break;
				 *impl =
				    (gpointer) servant->vepv->
				    Nautilus_Undo_Transaction_epv->
				    _get_undo_menu_item;
				 return (ORBitSkeleton)
				    _ORBIT_skel_Nautilus_Undo_Transaction__get_undo_menu_item;
				 break;
			      default:
				 break;
			    }
			    break;
			 default:
			    break;
		       }
		       break;
		    default:
		       break;
		  }
		  break;
	       default:
		  break;
	     }
	     break;
	  default:
	     break;
	}
	break;
     case 'q':
	if (strcmp((opname + 1), "ueryInterface"))
	   break;
	*impl = (gpointer) servant->vepv->Bonobo_Unknown_epv->queryInterface;
	return (ORBitSkeleton) _ORBIT_skel_Bonobo_Unknown_queryInterface;
	break;
     case 'r':
	if (strcmp((opname + 1), "ef"))
	   break;
	*impl = (gpointer) servant->vepv->Bonobo_Unknown_epv->ref;
	return (ORBitSkeleton) _ORBIT_skel_Bonobo_Unknown_ref;
	break;
     case 'u':
	switch (opname[1]) {
	  case 'n':
	     switch (opname[2]) {
	       case 'd':
		  if (strcmp((opname + 3), "o"))
		     break;
		  *impl =
		     (gpointer) servant->vepv->Nautilus_Undo_Transaction_epv->
		     undo;
		  return (ORBitSkeleton)
		     _ORBIT_skel_Nautilus_Undo_Transaction_undo;
		  break;
	       case 'r':
		  if (strcmp((opname + 3), "ef"))
		     break;
		  *impl = (gpointer) servant->vepv->Bonobo_Unknown_epv->unref;
		  return (ORBitSkeleton) _ORBIT_skel_Bonobo_Unknown_unref;
		  break;
	       default:
		  break;
	     }
	     break;
	  default:
	     break;
	}
	break;
     default:
	break;
   }
   return NULL;
}

static void
init_local_objref_Nautilus_Undo_Transaction(CORBA_Object obj,
					    POA_Nautilus_Undo_Transaction *
					    servant)
{
   obj->vepv[Bonobo_Unknown__classid] = servant->vepv->Bonobo_Unknown_epv;
   obj->vepv[Nautilus_Undo_Transaction__classid] =
      servant->vepv->Nautilus_Undo_Transaction_epv;
}

void
POA_Nautilus_Undo_Transaction__init(PortableServer_Servant servant,
				    CORBA_Environment * env)
{
   static const PortableServer_ClassInfo class_info =
      { (ORBit_impl_finder) & get_skel_Nautilus_Undo_Transaction,
	 "IDL:Nautilus/Undo/Transaction:1.0",
	 (ORBit_local_objref_init) &

	 init_local_objref_Nautilus_Undo_Transaction };
   PortableServer_ServantBase__init(((PortableServer_ServantBase *) servant),
				    env);
   POA_Bonobo_Unknown__init(servant, env);
   ORBIT_OBJECT_KEY(((PortableServer_ServantBase *) servant)->_private)->
      class_info = (PortableServer_ClassInfo *) & class_info;
   if (!Nautilus_Undo_Transaction__classid)
      Nautilus_Undo_Transaction__classid = ORBit_register_class(&class_info);
}

void
POA_Nautilus_Undo_Transaction__fini(PortableServer_Servant servant,
				    CORBA_Environment * env)
{
   POA_Bonobo_Unknown__fini(servant, env);
   PortableServer_ServantBase__fini(servant, env);
}

static ORBitSkeleton
get_skel_Nautilus_Undo_Manager(POA_Nautilus_Undo_Manager * servant,
			       GIOPRecvBuffer * _ORBIT_recv_buffer,
			       gpointer * impl)
{
   gchar *opname = _ORBIT_recv_buffer->message.u.request.operation;

   switch (opname[0]) {
     case 'a':
	if (strcmp((opname + 1), "ppend"))
	   break;
	*impl = (gpointer) servant->vepv->Nautilus_Undo_Manager_epv->append;
	return (ORBitSkeleton) _ORBIT_skel_Nautilus_Undo_Manager_append;
	break;
     case 'f':
	if (strcmp((opname + 1), "orget"))
	   break;
	*impl = (gpointer) servant->vepv->Nautilus_Undo_Manager_epv->forget;
	return (ORBitSkeleton) _ORBIT_skel_Nautilus_Undo_Manager_forget;
	break;
     case 'q':
	if (strcmp((opname + 1), "ueryInterface"))
	   break;
	*impl = (gpointer) servant->vepv->Bonobo_Unknown_epv->queryInterface;
	return (ORBitSkeleton) _ORBIT_skel_Bonobo_Unknown_queryInterface;
	break;
     case 'r':
	if (strcmp((opname + 1), "ef"))
	   break;
	*impl = (gpointer) servant->vepv->Bonobo_Unknown_epv->ref;
	return (ORBitSkeleton) _ORBIT_skel_Bonobo_Unknown_ref;
	break;
     case 'u':
	switch (opname[1]) {
	  case 'n':
	     switch (opname[2]) {
	       case 'd':
		  if (strcmp((opname + 3), "o"))
		     break;
		  *impl =
		     (gpointer) servant->vepv->Nautilus_Undo_Manager_epv->
		     undo;
		  return (ORBitSkeleton)
		     _ORBIT_skel_Nautilus_Undo_Manager_undo;
		  break;
	       case 'r':
		  if (strcmp((opname + 3), "ef"))
		     break;
		  *impl = (gpointer) servant->vepv->Bonobo_Unknown_epv->unref;
		  return (ORBitSkeleton) _ORBIT_skel_Bonobo_Unknown_unref;
		  break;
	       default:
		  break;
	     }
	     break;
	  default:
	     break;
	}
	break;
     default:
	break;
   }
   return NULL;
}

static void
init_local_objref_Nautilus_Undo_Manager(CORBA_Object obj,
					POA_Nautilus_Undo_Manager * servant)
{
   obj->vepv[Bonobo_Unknown__classid] = servant->vepv->Bonobo_Unknown_epv;
   obj->vepv[Nautilus_Undo_Manager__classid] =
      servant->vepv->Nautilus_Undo_Manager_epv;
}

void
POA_Nautilus_Undo_Manager__init(PortableServer_Servant servant,
				CORBA_Environment * env)
{
   static const PortableServer_ClassInfo class_info =
      { (ORBit_impl_finder) & get_skel_Nautilus_Undo_Manager,
	 "IDL:Nautilus/Undo/Manager:1.0",
	 (ORBit_local_objref_init) & init_local_objref_Nautilus_Undo_Manager

      };
   PortableServer_ServantBase__init(((PortableServer_ServantBase *) servant),
				    env);
   POA_Bonobo_Unknown__init(servant, env);
   ORBIT_OBJECT_KEY(((PortableServer_ServantBase *) servant)->_private)->
      class_info = (PortableServer_ClassInfo *) & class_info;
   if (!Nautilus_Undo_Manager__classid)
      Nautilus_Undo_Manager__classid = ORBit_register_class(&class_info);
}

void
POA_Nautilus_Undo_Manager__fini(PortableServer_Servant servant,
				CORBA_Environment * env)
{
   POA_Bonobo_Unknown__fini(servant, env);
   PortableServer_ServantBase__fini(servant, env);
}

static ORBitSkeleton
get_skel_Nautilus_Undo_Context(POA_Nautilus_Undo_Context * servant,
			       GIOPRecvBuffer * _ORBIT_recv_buffer,
			       gpointer * impl)
{
   gchar *opname = _ORBIT_recv_buffer->message.u.request.operation;

   switch (opname[0]) {
     case '_':
	if (strcmp((opname + 1), "get_undo_manager"))
	   break;
	*impl =
	   (gpointer) servant->vepv->Nautilus_Undo_Context_epv->
	   _get_undo_manager;
	return (ORBitSkeleton)
	   _ORBIT_skel_Nautilus_Undo_Context__get_undo_manager;
	break;
     case 'q':
	if (strcmp((opname + 1), "ueryInterface"))
	   break;
	*impl = (gpointer) servant->vepv->Bonobo_Unknown_epv->queryInterface;
	return (ORBitSkeleton) _ORBIT_skel_Bonobo_Unknown_queryInterface;
	break;
     case 'r':
	if (strcmp((opname + 1), "ef"))
	   break;
	*impl = (gpointer) servant->vepv->Bonobo_Unknown_epv->ref;
	return (ORBitSkeleton) _ORBIT_skel_Bonobo_Unknown_ref;
	break;
     case 'u':
	if (strcmp((opname + 1), "nref"))
	   break;
	*impl = (gpointer) servant->vepv->Bonobo_Unknown_epv->unref;
	return (ORBitSkeleton) _ORBIT_skel_Bonobo_Unknown_unref;
	break;
     default:
	break;
   }
   return NULL;
}

static void
init_local_objref_Nautilus_Undo_Context(CORBA_Object obj,
					POA_Nautilus_Undo_Context * servant)
{
   obj->vepv[Bonobo_Unknown__classid] = servant->vepv->Bonobo_Unknown_epv;
   obj->vepv[Nautilus_Undo_Context__classid] =
      servant->vepv->Nautilus_Undo_Context_epv;
}

void
POA_Nautilus_Undo_Context__init(PortableServer_Servant servant,
				CORBA_Environment * env)
{
   static const PortableServer_ClassInfo class_info =
      { (ORBit_impl_finder) & get_skel_Nautilus_Undo_Context,
	 "IDL:Nautilus/Undo/Context:1.0",
	 (ORBit_local_objref_init) & init_local_objref_Nautilus_Undo_Context

      };
   PortableServer_ServantBase__init(((PortableServer_ServantBase *) servant),
				    env);
   POA_Bonobo_Unknown__init(servant, env);
   ORBIT_OBJECT_KEY(((PortableServer_ServantBase *) servant)->_private)->
      class_info = (PortableServer_ClassInfo *) & class_info;
   if (!Nautilus_Undo_Context__classid)
      Nautilus_Undo_Context__classid = ORBit_register_class(&class_info);
}

void
POA_Nautilus_Undo_Context__fini(PortableServer_Servant servant,
				CORBA_Environment * env)
{
   POA_Bonobo_Unknown__fini(servant, env);
   PortableServer_ServantBase__fini(servant, env);
}
