#!/bin/sh
# $Id: build-emacs,v 1.1.1.2 2005-03-10 20:32:56 zacheiss Exp $
if test "X$FAST" != "X" ; then echo "Not running $0" ;  exit 0 ; fi
$SHELL $SHELLVERBOSE $srcdir/generic-build $AFSROOT/stacken.kth.se/ftp/pub/gnu/emacs/emacs-20.7.tar.gz emacs-20.7
