#!/bin/sh
# $Id: mkdir,v 1.1.1.2 2005-03-10 20:32:56 zacheiss Exp $
mkdir foo || exit 1
echo hej > foo/1 || exit 1
rmdir foo >/dev/null 2>&1 
test -d foo || exit 1
rm -f foo/1 || exit 1
rmdir foo || exit 1
test -d foo && exit 1
exit 0
