/*
 * afs_AdminPtsErrors.h:
 * This file is automatically generated; please do not edit it.
 */
#define ADMPTSSERVERNULL                         (20480L)
#define ADMPTSUSERNAMENULL                       (20481L)
#define ADMPTSUSERNAMETOOLONG                    (20482L)
#define ADMPTSGROUPNAMENULL                      (20483L)
#define ADMPTSGROUPNAMETOOLONG                   (20484L)
#define ADMPTSFAILEDNAMETRANSLATE                (20485L)
#define ADMPTSNEWOWNERNULL                       (20486L)
#define ADMPTSNEWOWNERTOOLONG                    (20487L)
#define ADMPTSNEWGROUPNULL                       (20488L)
#define ADMPTSNEWGROUPIDPOSITIVE                 (20489L)
#define ADMPTSTARGETGROUPNULL                    (20490L)
#define ADMPTSTARGETGROUPTOOLONG                 (20491L)
#define ADMPTSGROUPPNULL                         (20492L)
#define ADMPTSGROUPMEMEXCEEDED                   (20493L)
#define ADMPTSMEMBERNAMENULL                     (20494L)
#define ADMPTSOLDNAMENULL                        (20495L)
#define ADMPTSOLDNAMETOOLONG                     (20496L)
#define ADMPTSNEWNAMENULL                        (20497L)
#define ADMPTSNEWNAMETOOLONG                     (20498L)
#define ADMPTSINVALIDGROUPDELETEPERM             (20499L)
#define ADMPTSINVALIDGROUPSOWNEDPERM             (20500L)
#define ADMPTSINVALIDGROUPSOWNEDPERM2            (20501L)
#define ADMPTSNEWENTRYPNULL                      (20502L)
#define ADMPTSUSERPNULL                          (20503L)
#define ADMPTSNEWGROUPIDNULL                     (20504L)
#define ADMPTSMAXGROUPIDNULL                     (20505L)
#define ADMPTSNEWUSERIDNULL                      (20506L)
#define ADMPTSMAXUSERIDNULL                      (20507L)
extern void initialize_ap_error_table ();
#define ERROR_TABLE_BASE_ap (20480L)

/* for compatibility with older versions... */
#define init_ap_err_tbl initialize_ap_error_table
#define ap_err_base ERROR_TABLE_BASE_ap
