#!/bin/sh
#
# $Id: dhclient-enter-hooks,v 1.1.4.1 2003-07-02 23:57:06 ghudson Exp $

function make_resolv_conf() {
  echo "dhclient not updating /etc/resolv.conf."
}

# Overwrite NTP servers we got from the DHCP server so
# dhclient doesn't trash our /etc/ntp.conf.
new_ntp_servers=""
