# $Id: Makefile.athena,v 1.4 1996-11-20 15:46:36 ghudson Exp $

SHELL=/bin/sh

prepare:
	rm -f .defaults
	cp "defaults.$$HOSTTYPE" .defaults
	module=`sed -n "s/^set module = '\(.*\)'$$/\1/p" .defaults`; \
	./Configure "$$module"

clean:
	${MAKE} clean

all:
	${MAKE} all

check:

install:
	${MAKE} install "DESTDIR=$$SRVD"
