.TH PERMISSIONS 5 "3 November 1986"
.UC 4
.SH NAME
permissions \- a list of subscribers and the statfiles that they are
allowed to access
.SH DESCRIPTION
A
.I permissions
contains the names of the machines that are allowed to
access files via
.B track.
Permissions are specified as pairs of
.I subscribers and subscriptionlists
If the
.I permissions
file does not exist, then the system is
wide open (i.e. anyone that can execute
.B track
will be able
to access all the files that
.B track
can access.)
Conversely, if the
.I permissions
file exists, but is empty, the system
is completly closed (i.e. nobody can access anything via
.B track.)
The
.I permissions
file contains one line for each
.I subscriber/subscriptionlist
pair.
Each line is made up of the
.I subscriber's
name, an arbitrary number of tabs
and/or spaces,  then the
.I subscriptionlist
name.
.PP
The keyword
.B ALL
can be used instead of either a machine name or a file
name.  If
.B ALL
appears instead of a machine name, then all
.I subscribers
will have access to the associated
.I subscriptionlist.
Similarly, if
.B ALL
appears as file name, then the associated
.I subscriber
will have access to all
.I subscriptionlists.
Having a line with the keyword
.B ALL
for both the
.I subscriber
and
.I subscriptionlist
makes the system wide open (i.e. the same thing as not having
the
.I permissions
file exist at all.)
.SH EXAMPLES
foo hourly --  Permit the
.I subscriber
named foo to access the
.I subscriptionlist
name hourly.
.PP
foo ALL -- Permit the
.I subscriber
named foo to access all
.I subscriptionlists.
.PP
ALL hourly -- Permit all
.I subscribers
to access the
.I subscriptionlist
name hourly.
.PP
ALL ALL -- Permit all
.I subscribers
to access all
.I subscriptionlists.
.SH FILES
 .../track/permissions
.SH BUGS
There is no allowance made for either a
.I
subscriber
or
.I subscriptionlist
named
.B ALL.
.SH "SEE ALSO"
track(1), subscriptionlist(5)
.br
When Network File Systems Aren't Enough. Automatic Software Distribution
Revisited.  Proceedings of the Summer USENIX Conference. June 16-18, 1986.
Atlanta, GA.
