.ll 6i
.TH STATFILE 5 "4 November 1986"
.UC 4
.SH NAME
statfile \- list type, name, and currentness of files for track
.SH DESCRIPTION
A
.I statfile
is a listing of objects to be handled by the
.B track
system.
Objects are either ordinary files, directories, or symbolic links.
.I Statfiles
contain one line for each object.  The format of the lines
is as follows:
.PP
The first character on the line describes the type of object being handled.
This character must be either "f" for ordinary files, "d" for directories, or
"l" for symbolic links.
.PP
Immediately following the first character (i.e. with NO white space separation), is the full
path name of the object.
.PP
Whitespace -- space(s) and/or tab(s) --  must follow the pathname.  The last item
on the line is a string that describes the
.I currentness
of the object.  For ordinary files, this string is the modification date of the
file expressed in number of seconds since the epoch.
For directories, this string consists of the name of the directory's owner,
followed by a period ("."), then the name of the directory's group, another period,
and finally the mode bits of the directory (in octal).
For symbolic links,  the string consists of the name of the file towards which
the link is pointing.
.SH EXAMPLES
d/bin root.root.40755
.br
f/bin/df 476233823
.br
l/usr/ucb/newaliases /usr/lib/sendmail
.PP
The above three lines tell
.B track
that the directory "/bin" is available and it is owned by "root" as well as group "root"
and has modes "40755" (Normally written by the
.B ls
command as "drwxr-xr-x").
Similarly, the ordinary file named "/bin/df" is available to
.I subscribers
and its modification date is "476233823 seconds since the epoch" (Normally written
by the 
.B ls
command as 6:10:23 on February 2, 1985).
The symbolic link "/usr/ucb/newaliases" is also available, and is pointing to
"/usr/lib/sendmail".
.SH FILES
 .../track/stats/
.I subscriptionlist_name . librarian_machine_name
.SH BUGS
Mode bits as well as owner and group should probably be included in the
.I currentness
string for ordinary files.
Also, the "40" that preceeds the other mode bits for directories is redundant with the
initial type specifier.  One of them should be removed.
.SH "SEE ALSO"
track(1), subscriptionlist(5)
.br
When Network File Systems Aren't Enough: Automatic File Distribution Revisited
.br
.ti 5
by Daniel Nachbar
