# $Id: Makefile.athena,v 1.1 1999-02-26 23:27:08 danw Exp $

SHELL=/bin/sh
BUILD=`pwd`/BuildTools/bin/Build

prepare:

clean:
	make BUILD=$(BUILD) clean

all:
	make BUILD=$(BUILD) all

check:

install:
	make BUILD=$(BUILD) DESTDIR=$$SRVD install
