#!/bin/sh
# $Id: Xreset,v 1.1.4.1 2001-09-16 17:54:38 ghudson Exp $

# Xreset
#
# This program is run as root by xlogin to reclaim ownership of the
# devices granted to the user in Xstartup.

cd /dev

# Reclaim the audio devices.
chown root:sys dsp* audio* midi* mixer* sequencer
chmod      640 dsp* audio* midi* mixer* sequencer

# Turn off power saving.
/usr/X11R6/bin/xset -display :0.0 -dpms

exit 0
