#!/bin/sh
# $Id: Xstartup,v 1.2 2002-09-17 22:11:45 zacheiss Exp $

# Xstartup
#
# This program is run as root by xlogin after the user is verified,
# with $USER set to the name of the user logging in.  It is used to
# claim various devices for the user logging in on the console.

cd /dev

# Claim the audio devices.
chown $USER dsp* audio* midi* mixer* sequencer
chmod   600 dsp* audio* midi* mixer* sequencer

# Claim the cdrom and floppy devices
chown --dereference $USER cdrom fd0*
chmod 600 cdrom fd0*

exit 0
