.TH TELLME 1 "17 June 2009"
.SH NAME
tellme \- Display Athena-specific information and witticisms
.SH SYNOPSIS
.nf
.B tellme [\fIidentifier\fP...]
.sp
.SH DESCRIPTION
.BR tellme
can be queried to provide Athena-specific information, such as the
current public root password and the cluster combination.  It can 
also help to unravel the mysteries of life, the universe, and 
everything.  If
.IR identifier
is not specified, a usage message will be displayed.
.SH EXAMPLES
.B tellme root

.B tellme combo

.B tellme 42

.SH AUTHOR
Massachusetts Institute of Technology
.br
Copyright 2009 by the Massachusetts Institute of Technology.
