ATHRETCDIR=/etc/athena

dist:

prep:

clean:
	${MAKE} clean

all:
	${MAKE}

check:

install:
	mkdir -p $$SRVD${ATHRETCDIR}
	install -c -m 555 get-edid $$SRVD${ATHRETCDIR}
	install -c -m 555 parse-edid $$SRVD${ATHRETCDIR}
