.TH VERIFY_WS 8 "13 July 2012" "debathena-verify" "Public Workstation Verification"
.SH NAME
verify_ws \- A public workstation verification script
.SH SYNOPSIS
.nf
.B verify_ws [-d] [-s check1,check2,]
.sp
.SH DESCRIPTION
.BR verify_ws
attempts to do some verification of public workstations.

.I -d 
will enable debug mode.

.I -s 
will enable you to provide a list comma-separated checks to skip.

.SH AUTHOR
Jonathan Reed <jdreed@mit.edu>, Debathena Project

