# $Id: Makefile.athena,v 1.2 2005-05-02 19:22:35 ghudson Exp $

FONTDIR=/usr/athena/share/fonts/redhat
CONFIGDIR=/etc/fonts/fonts.conf

dist:

prepare:

clean:

all:

check:

install:
	mkdir -p "$$SRVD${FONTDIR}"
	mkdir -p "$$SRVD${CONFIGDIR}"
	gzip -cd redhat-fonts-el4.tar.gz | (cd "$$SRVD${FONTDIR}" && tar xf -)
	chown -R root "$$SRVD${FONTDIR}"
	install -c -m 644 fonts.conf "$$SRVD${CONFIGDIR}"
