# $Id: Makefile.athena,v 1.1 1998-05-07 21:49:04 ghudson Exp $

SHELL=/bin/sh

prepare:

clean:
	cd src && ${MAKE} clean

all:
	cd src && ${MAKE} "CC=$$COMPILER" CDEBUG=-g \
		INSTALL=/usr/athena/bin/install \
		DESTBIN=/usr/athena/bin \
		DESTSBIN=/etc/athena \
		DESTEXEC=/etc/athena \
		DESTMAN=/usr/athena/man \
		DESTHELP=/usr/athena/lib

check:

install:
	cd src && ${MAKE} install "DESTDIR=$$SRVD"

