# This is pretty dangerous in a bunch of ways.  Approach with caution.
DEST=/afs/athena.mit.edu/system/athena10/installer/athinfod

default:
	: Use "make install" to move this from where the installer will fetch it.

install: 
	cp -f athinfod ${DEST}

