# $Id: Makefile.athena,v 1.2 2005-08-09 19:19:31 ghudson Exp $

dist:
	cp "$$CONFIG_SITE" config.site.athena

prepare:
	rm -f config.cache
	CONFIG_SITE=`pwd`/config.site.athena ./configure \
	  --without-saslauthd --with-plugindir=/usr/athena/lib/sasl2

clean:
	${MAKE} clean

all:
	LD_RUN_PATH=/usr/athena/lib ${MAKE} all

check:

install:
	LD_RUN_PATH=/usr/athena/lib ${MAKE} install DESTDIR="$$SRVD"
