#
# Copyright 2004 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
#ident	"$Id: Makefile,v 1.1.1.1 2005-04-01 15:01:25 rbasch Exp $"
#

CORE_DEPTH = ../../../..
include ../Makefile-tlsu.com

DATAFILES +=

all:: $(FILES)
publish:: all pkg

include ../Makefile-tlsu.targ
