.TH REACTIVATE 8 "24 June 1991"
.FM mit
.SH NAME
reactivate \- reset the state of an idle workstation
.SH SYNOPSIS
.B /etc/athena/reactivate
[
.B \-detach
]
.SH DESCRIPTION
The
.I xlogin(8)
program uses the
.I reactivate
script to both initialize the workstation for users and to reset the
state after a user has logged out.  It should only be run when no one
is logged in.

The
.I reactivate
script performs six tasks:

+ it detaches all attached filesystems and flushes all filesystem
authentication from the workstation 

+ it cleans out /tmp

+ it resets the password and group files to their default contents

+ it attaches the appropriate system packs

+ it invokes an automatic software update if available

+ it turns off remote network access to the workstation.

This last step closes the workstation from
unexpected and possibly hostile
remote connections.
After logging in, you can use the
.I access_on
command to allow remote access.

If the file
.I /etc/athena/reactivate.local
is present, it will be executed as the last thing
.B reactivate
does.  This allows local customization to a workstation's
configuration.

.SH OPTIONS
.TP
.B \-detach
causes reactivate to detach all attached filesystems.  This is not
done on every invocation to cut down on the network traffic from idle
workstations.

.SH FILES
.DT
.nf
/etc/athena/clusterinfo		These files contain the information
/etc/athena/clusterinfo.bsh	received from the nameserver.
/etc/athena/rc.conf		Contains configuration variables
/etc/passwd.local		Default contents of password file
/etc/group.local		Default contents of group file
/etc/athena/reactivate.local	Optional local additions
.fi
.SH SEE ALSO
dm(8), xlogin(8), save_cluster_info(8), access_on(1) and access_off(1),
attach(1) and detach(1), hesiod(3)
