#!/bin/sh
# $Id: sendmail-relay-select,v 1.3 2003-10-26 20:04:24 ghudson Exp $

if [ -n "$DIRECT_DELIVERY" ]; then
  exit 0
elif [ -f /etc/athena/sendmail.conf ]; then
  awk '/relay/ {print $2}' /etc/athena/sendmail.conf
  exit 0
fi

exit 0
