# $Id: Makefile.athena,v 1.2 1996-11-20 15:45:53 ghudson Exp $

SHELL=/bin/sh

prepare:

clean:
	${MAKE} clean

all:
	${MAKE} "CC=$$COMPILER"

check:

install:
	${MAKE} install install.man "DESTDIR=$$SRVD"
