# $Id: Makefile.athena,v 1.3 1999-01-16 21:34:52 rbasch Exp $

SHELL=/bin/sh

prepare:

clean:
	${MAKE} clean

all:
	${MAKE} "CC=$$COMPILER"

check:

install:
	${MAKE} install install.man "DESTDIR=$$SRVD" "LIBDIR="
