.TH XMOIRA 1 "25 March 2010" "debathena-moira-gui" "Moira Database"
.SH NAME
xmoira \- A GUI interface to common moira operations
.SH SYNOPSIS
.nf
.B xmoira
.sp
.SH DESCRIPTION
.BR xmoira
provides a graphical interface to common moira operations,
specifically those used by the chpobox, chfn, and chsh commands.  With
xmoira, users can change where their mail is being forwarded to, what
shell they want, and their finger information.

.SH SEE ALSO
chpobox(1), moira(1)

.SH AUTHOR
Jonathan Reed <jdreed@mit.edu>, Debathena Project

