.\" e
.TH MAG 1 UMFT
.SH NAME
mag \- computes fontsizes and magsteps

.de Ex
.sp
.RS
.nf
.ft C
..
.de Xe
.RE
.sp
.fi
..
.SH SYNOPSIS 
.B
mag
[-\fBR\fIdpi\fP\fP] magstep . . .

.B
mag
[-\fBr\fP] [-\fBR\fP\fIdpi\fP] fontsize . . .

.SH DESCRIPTION
.EQ
delim $$
.EN
This tool calculates fontsizes given magsteps.  TeXfonts are provided as
true sized fonts or as magnifications.  The fontsize of a true sized
font equals the resolution of the printer (ex.  300).  The fontsize
of a font magnified $n$ \fImagsteps\fP equals:
.EQ
1.2 sup{n} times 300
delim off
.EN
rounded to its nearest integer value.  Fontnames for TeX fonts normally
consists of the name (\fIcmr\fP), pointsize (\fI10\fP), type (\fIpk\fP)
and fontsize (\fI360\fP), for example: \fIcmr10.360pk\fP. 

.SH EXAMPLES
The result of \fImag -R240 -2 0 0.5 1\fP will be: 
.Ex 
167 240 263 288 
.Xe

The inverse function is computed with the \fI-r\fP option. The result of
\fImag -r -R240 167 240 263 288\fP
will be the fontsteps:
.Ex
-2 0 0.5 1
.Xe

The UNIX shells allow command substitution. One can write:
.Ex
mag -r -R240 `mag -R240 -2 0 0.5 1`
.Xe

.SH DATE
18 December, 1989

.SH AUTHOR
.nf
Piet Tutelaers
University of Technology Eindhoven
rcpt@urc.tue.nl

