#!/bin/sh

# Get standard options from command line or defaults.
. ais-options

localize()
{
    mv $1 $1.symlink
    if [ $? -eq 0 ]; then
	cp -p $1.symlink $1
	if [ $? -eq 0 ]; then
	    rm -f $1.symlink
	else
	    echo "localize: copying file for $1 failed"
	    mv $1.symlink $1
	fi
    else
	echo "localize: renaming $1 failed"
    fi
}

# Athena "customizations" to OS. Need to be done whenever inst updates
# the OS. This is stuff that can't be done by track. This code is needed
# both by the installation software and the update software.

# SGI's getty runs scheme instead of /usr/bin/login, if it exists.
# We don't want this, so we move it out of the way if we have just
# installed the SGI version.  (The showfiles command used here will
# only output something if the scheme file matches what is in the
# inst database).
scheme=/usr/lib/iaf/scheme
if [ -f ${AIS_ROOT}$scheme \
     -a -n "`showfiles -r ${AIS_ROOT} -u -- $scheme`" ]; then
    mv ${AIS_ROOT}$scheme ${AIS_ROOT}$scheme.old
fi

# Note that for rc?.d scripts, we use test -l instead of -f. This
# is because sometimes there are absolute symlinks involved, while
# absolute paths during an install really live under ${AIS_ROOT},
# so that test -f may fail even if there is a link there.

# xdm has an /etc/config option, but it runs regardless when
# windowsystem is on.  And we need windowsystem on in order to
# run X.
if [ -l ${AIS_ROOT}/etc/rc2.d/S98xdm ]; then
    mv ${AIS_ROOT}/etc/rc2.d/S98xdm ${AIS_ROOT}/etc/rc2.d/s98xdm
fi

if [ -l ${AIS_ROOT}/etc/rc0.d/K02xdm ]; then
    mv ${AIS_ROOT}/etc/rc0.d/K02xdm ${AIS_ROOT}/etc/rc0.d/k02xdm
fi

# ns_admin runs a config script (and therefore makes noise) whether
# its /etc/config file shuts it off or not. SIGH.
if [ -l ${AIS_ROOT}/etc/rc2.d/S60ns_admin ]; then
    mv ${AIS_ROOT}/etc/rc2.d/S60ns_admin ${AIS_ROOT}/etc/rc2.d/s60ns_admin
fi

if [ -l ${AIS_ROOT}/etc/rc0.d/K30ns_admin ]; then
    mv ${AIS_ROOT}/etc/rc0.d/K30ns_admin ${AIS_ROOT}/etc/rc0.d/k30ns_admin
fi

# So, setsym and all of the objects in IP*boot need to be installed
# locally for the proper functioning of autoconfig. Or, more
# specifically, to enable autoconfig to function well enough to tweak
# all the devices. Or, more specifically, to enable autoconfig to
# function well enough to tweak the camera device. Because the camera
# doesn't work unless you've run autoconfig since you last booted. So
# the only reason I'm doing this hack at the moment is so that the
# camera will work. (Actually, setsym is not needed under 6.2, but
# what the heck.)
localize ${AIS_ROOT}/usr/sbin/setsym

sysgendir=${AIS_ROOT}/usr/cpu/sysgen/${AIS_CPUBOARD}boot
for i in `find $sysgendir -follow -fstype afs -print`; do
    localize $i
done

case ${AIS_OSVERSION} in
    6.2)
	# bsdlpr startup doesn't have an /etc/config option in 6.2
	if [ -l ${AIS_ROOT}/etc/rc2.d/S61bsdlpr ]; then
	    mv ${AIS_ROOT}/etc/rc2.d/S61bsdlpr ${AIS_ROOT}/etc/rc2.d/s61bsdlpr
	fi
	if [ -l ${AIS_ROOT}/etc/rc0.d/K26bsdlpr ]; then
	    mv ${AIS_ROOT}/etc/rc0.d/K26bsdlpr ${AIS_ROOT}/etc/rc0.d/k26bsdlpr
	fi
	;;

    6.3)
	# This particular file is the only nonlocal one in sysgen/system. Its
	# absence causes autoconfig to complain at boot time, though doesn't
	# prevent the camera from working.
	localize ${AIS_ROOT}/var/sysgen/system/fddi.sm
	;;

    6.5)
	# iforls and iforncs don't have /etc/config options
	if [ -l ${AIS_ROOT}/etc/rc2.d/S71iforls ]; then
	    mv ${AIS_ROOT}/etc/rc2.d/S71iforls ${AIS_ROOT}/etc/rc2.d/s71iforls
	fi
	if [ -l ${AIS_ROOT}/etc/rc0.d/K26iforls ]; then
	    mv ${AIS_ROOT}/etc/rc0.d/K26iforls ${AIS_ROOT}/etc/rc0.d/k26iforls
	fi
	if [ -l ${AIS_ROOT}/etc/rc2.d/S72iforncs ]; then
	    mv ${AIS_ROOT}/etc/rc2.d/S72iforncs \
		    ${AIS_ROOT}/etc/rc2.d/s72iforncs
	fi
	if [ -l ${AIS_ROOT}/etc/rc0.d/K27iforncs ]; then
	    mv ${AIS_ROOT}/etc/rc0.d/K27iforncs \
		    ${AIS_ROOT}/etc/rc0.d/k27iforncs
	fi
	# motif_eoe.sw.eoe invokes a script mksymlinks as an exit
	# command, which leaves the following superseded directory
	# around.  Clean it up.
	rm -rf ${AIS_ROOT}/usr/include/Vk.O
	;;
esac

# Set the video refresh rate to 75 hz on the O2 (CRM graphics),
# 72 hz on Indy (XL or XZ graphics), if not already set.
case "${AIS_GRAPHICS}" in
    GR3-XZ)
	gfxname=GR2
	format=72hz
	;;
    Indy)
	gfxname=NG1
	format=72hz
	;;
    CRM)
	gfxname=Crm
	format=75hz
	;;
    *)
	gfxname=
	;;
esac
if [ -n "$gfxname" ]; then
    if [ ! -f "${AIS_ROOT}/var/X11/Xvc/${gfxname}0_TimingTable" ]; then
	# Make sure DISPLAY is not set, as setmon looks at it even
	# when -p0 is specified.
	# setmon -x actually stores the format in the above file, hence
	# the chroot.
	unset DISPLAY
	chroot ${AIS_ROOT} /usr/gfx/setmon -x -p0 "$format"
    fi
fi

# The SGI Netscape app-defaults file has some settings that we don't
# want, e.g. for menu mnemonics.  Since any desired SGI-specific settings
# should be in the infoagents file, just nuke it from the OS.
rm -rf ${AIS_ROOT}/usr/lib/X11/app-defaults/Netscape

# The IRIX 6.5.7 X server has a bug which can crash it when running
# in 24-bit mode.  Though the bug was fixed in 6.5.10, no patch was
# issued for the problem.  So, we extracted the fixed binaries from
# the 6.5.10 distribution and installed them in the OS volume.
# The following makes sure that the fixes are installed locally, for
# each machine graphics type.

verify()
{
    cmp -s /os$1 ${AIS_ROOT}$1 || {
	rm -rf ${AIS_ROOT}$1
	cp -p /os$1 ${AIS_ROOT}$1
	if [ $? -ne 0 ]; then
	    echo "verify: failed to copy $1 "
	fi
    }
}

case "${AIS_GRAPHICS}" in
    CRM)
	verify /usr/gfx/arch/GENERIC/Xsgi
	verify /usr/lib/X11/dyDDX/crm.so
	;;
    GR3-XZ)
	verify /usr/gfx/arch/GENERIC/Xsgi
	verify /usr/lib/X11/dyDDX/gr2.so
	;;
    Indy)
	verify /usr/gfx/arch/IP22NG1/Xsgi
	;;
esac

# We have installed the syslogd binary from IRIX 6.5.15, and the nsd
# and libmdbm.so binaries from SGI patch 4236, in the OS volume, in
# order to deal with security vulnerabilities in those programs in
# IRIX 6.5.7.  Make sure that these are installed locally.
verify /usr/etc/syslogd
verify /usr/etc/nsd
verify /usr/lib32/libmdbm.so

# Work around a reported vulnerability, which could be exploited by a
# non-root user to read any file, by changing the permissions on a
# world-writable appletalk directory.
chmod o-w ${AIS_ROOT}/var/adm/appletalk/icons

exit 0
